import json
import os

STATES_DIR = "/home/volmarr/.gemini/antigravity/scratch/Camping_Nomad_Life/states"

def load_state(name):
    path = os.path.join(STATES_DIR, f"{name}.json")
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f), path

def save_state(data, path):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")

# 1. North Carolina (+5 sites -> 10 total)
nc, nc_path = load_state("north_carolina")
nc.extend([
  {
    "id": "north_carolina-006",
    "name": "Fires Creek Dispersed Area - Nantahala National Forest",
    "state": "North Carolina",
    "county": "Clay",
    "coordinates": {"latitude": 35.1412, "longitude": -83.8412, "elevation_ft": 2200.0},
    "management_agency": {"name": "U.S. Forest Service - National Forests in North Carolina", "type": "Federal", "phone": "(828) 837-5152", "website": "https://www.fs.usda.gov/nfsnc"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free primitive dispersed camping on national forest pullouts along Fires Creek Road (FS 340). Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Fires Creek. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy. Bear safety mandatory."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 2, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low to Moderate in stream valley", "distance_from_tower_corridor_miles": 6.5, "cellular_internet_dependable": True},
    "amenities": ["Fires Creek Native Trout Fishing", "Rim Trail Access", "Appalachian Hardwood Canopy", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Hayesville / Murphy, NC", "distance_miles": 12.0, "services_available": ["Grocery Stores", "Hospital", "Gas Stations", "Hardware", "Outfitters", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush mountain spring (60-72°F).", "summer": "Cool mountain breezes (76-84°F) with stream pools.", "fall": "Spectacular Blue Ridge autumn foliage.", "winter": "Cool winter (32-45°F)."},
    "dangers_and_hazards": ["Black Bear Habitat", "Copperhead Snakes"],
    "acoustic_environment": {"quietness_rating": "Appalachian Stream Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Fires Creek stream flow", "Songbird calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Hemlock", "Tulip Poplar", "White Pine", "Rhododendron"], "common_animals": ["Native Brook Trout", "Black Bear", "White-tailed Deer", "Wild Turkey"]},
    "human_demographics_and_culture": "Cherokee ancestral lands and Western North Carolina mountain trout culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Fires Creek Rim Trail encircles a horseshoe ridge of 4,000-foot peaks protecting the native trout watershed.", "energetic_and_spiritual_features": "Crystal clear mountain stream cascading through ancient Blue Ridge cove forests."},
    "nearby_hiking_trails": [{"trail_name": "Fires Creek Rim Trail", "length_miles": 6.0, "difficulty": "Strenuous", "features": "Horseshoe ridge walk, 4,000-foot peaks, native trout stream vistas"}],
    "public_reviews_summary": "Top choice free trout stream camping near Hayesville with reliable cell service.",
    "other_data": "Part of the Leatherwood Horse Trail system.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "north_carolina-007",
    "name": "Wilson Creek Dispersed Area - Pisgah National Forest",
    "state": "North Carolina",
    "county": "Caldwell",
    "coordinates": {"latitude": 35.9812, "longitude": -81.7812, "elevation_ft": 1400.0},
    "management_agency": {"name": "U.S. Forest Service - Grandfather Ranger District", "type": "Federal", "phone": "(828) 652-2144", "website": "https://www.fs.usda.gov/nfsnc"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside day-use fee zones)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along Brown Mountain Beach Road / FS 192. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Wilson Creek. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road along river gorge; smooth when dry.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 2, "road_terrain_difficulty": 3, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low to Moderate along river gorge corridor", "distance_from_tower_corridor_miles": 6.5, "cellular_internet_dependable": True},
    "amenities": ["Wilson Creek National Wild & Scenic River", "Granite Gorge Swimming Holes", "Kayaking & Canoeing", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 5, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Lenoir / Morganton, NC", "distance_miles": 14.0, "services_available": ["Full City Services", "Hospital", "Walmart", "Gas Stations", "Hardware", "Outfitters"]}],
    "seasonal_weather_effects": {"spring": "Lush mountain spring (60-72°F).", "summer": "Warm summer (80-86°F) with granite bedrock river swimming.", "fall": "Spectacular Blue Ridge autumn foliage.", "winter": "Cool winter (35-48°F)."},
    "dangers_and_hazards": ["Flash Floods in Granite River Gorge", "Rapid Water Currents"],
    "acoustic_environment": {"quietness_rating": "Granite Gorge River Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Wilson Creek water roar", "Kayaker shouts"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Eastern Hemlock", "Tulip Poplar", "White Pine", "Rhododendron"], "common_animals": ["Rainbow Trout", "Black Bear", "White-tailed Deer", "Green Salamander"]},
    "human_demographics_and_culture": "Cherokee ancestral lands and Wilson Creek National Wild & Scenic River gorge culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Wilson Creek National Wild and Scenic River cuts through a 500-million-year-old crystalline granite gorge.", "energetic_and_spiritual_features": "Crystal clear mountain river cascading over smooth granite bedrock pools."},
    "nearby_hiking_trails": [{"trail_name": "Wilson Creek Gorge Trail", "length_miles": 4.0, "difficulty": "Moderate", "features": "Granite gorge cliffs, turquoise swimming holes, waterfalls"}],
    "public_reviews_summary": "World-class granite river swimming hole country near Morganton with dependable cell service.",
    "other_data": "Extremely popular for summer river swimming.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "north_carolina-008",
    "name": "Slickrock Wilderness Edge Dispersed - Nantahala NF",
    "state": "North Carolina",
    "county": "Graham",
    "coordinates": {"latitude": 35.3812, "longitude": -83.9812, "elevation_ft": 2400.0},
    "management_agency": {"name": "U.S. Forest Service - Cheoah Ranger District", "type": "Federal", "phone": "(828) 479-6431", "website": "https://www.fs.usda.gov/nfsnc"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside wilderness boundary)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along FS Road 81 outside Joyce Kilmer-Slickrock Wilderness boundary. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from mountain streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy. Bear canister mandatory."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel mountain forest road", "road_conditions": "Graded gravel Forest Service road climbing mountain ridge; smooth when dry.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 3, "road_terrain_difficulty": 3, "supply_run_pain": 4}},
    "nomad_connectivity_rating": {"overall_rating": "Great on Ridge (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low to Moderate on 2,400-foot mountain ridge pullouts", "distance_from_tower_corridor_miles": 7.5, "cellular_internet_dependable": True},
    "amenities": ["Joyce Kilmer Old-Growth Poplar Grove Proximity", "Slickrock Wilderness Access", "Appalachian Mountain Views", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 10, "quietness_score": 10},
    "nearest_supply_towns": [{"town_name": "Robbinsville, NC", "distance_miles": 16.0, "services_available": ["Grocery Store", "Gas Stations", "Hardware", "Outfitters", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush mountain spring (58-70°F).", "summer": "Cool mountain ridge breezes (76-84°F).", "fall": "Spectacular Great Smoky autumn foliage.", "winter": "Cool winter (32-45°F)."},
    "dangers_and_hazards": ["Black Bear Habitat", "Remote Wilderness Isolation"],
    "acoustic_environment": {"quietness_rating": "Old-Growth Wilderness Silence (Quietness Score: 10/10)", "common_human_made_sounds": ["Wind through old-growth poplars", "Songbird calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Giant Tulip Poplar (400+ yrs)", "White Pine", "Eastern Hemlock", "Trillium"], "common_animals": ["Black Bear", "White-tailed Deer", "Wild Boar", "Wild Turkey", "Trout"]},
    "human_demographics_and_culture": "Cherokee ancestral lands and Joyce Kilmer old-growth forest conservation heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Joyce Kilmer Memorial Forest protects 3,800 acres of virgin old-growth hardwood forest with trees over 400 years old.", "energetic_and_spiritual_features": "Giant ancient tulip trees over 20 feet in circumference towering into the mountain canopy."},
    "nearby_hiking_trails": [{"trail_name": "Joyce Kilmer Memorial Loop Trail", "length_miles": 2.0, "difficulty": "Easy to Moderate", "features": "Virgin old-growth tulip poplars, Poplar Cove stream, historic memorial stone"}],
    "public_reviews_summary": "Humble and profound old-growth forest basecamp near Robbinsville with reliable cell service on ridge pullouts.",
    "other_data": "Trees over 400 years old in Joyce Kilmer grove.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "north_carolina-009",
    "name": "Badin Lake Dispersed Area - Uwharrie National Forest",
    "state": "North Carolina",
    "county": "Montgomery",
    "coordinates": {"latitude": 35.4123, "longitude": -80.0812, "elevation_ft": 550.0},
    "management_agency": {"name": "U.S. Forest Service - Uwharrie Ranger District", "type": "Federal", "phone": "(910) 576-6391", "website": "https://www.fs.usda.gov/nfsnc"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside developed fee campgrounds)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along FR 576 / Badin Lake access roads outside fee zones. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Badin Lake. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low along Badin Lake shoreline", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["Badin Lake Shoreline", "Uwharrie Trailhead Proximity", "Boating & Swimming", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 7, "distance_to_gym_score": 6, "terrain_score": 8, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Troy / Albemarle, NC", "distance_miles": 12.0, "services_available": ["Grocery Stores", "Hospital", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush Piedmont spring (65-75°F).", "summer": "Warm summer (85-92°F) with lake swimming.", "fall": "Crisp autumn foliage.", "winter": "Mild winter (45-56°F)."},
    "dangers_and_hazards": ["Lake Water Hazards", "Copperhead Snakes"],
    "acoustic_environment": {"quietness_rating": "Piedmont Lake Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Badin Lake wave lap", "Pine wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Loblolly Pine", "Shortleaf Pine", "Post Oak", "Dogwood"], "common_animals": ["White-tailed Deer", "Bald Eagle", "Large-mouth Bass", "Wild Turkey"]},
    "human_demographics_and_culture": "Catawba ancestral lands and ancient Uwharrie Mountain geology heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Uwharrie Mountains are among the oldest mountain ranges in North America, formed over 500 million years ago.", "energetic_and_spiritual_features": "Peaceful pine-covered ancient mountain hills surrounding blue Badin Lake waters."},
    "nearby_hiking_trails": [{"trail_name": "Uwharrie National Recreation Trail (Badin Lake Section)", "length_miles": 4.0, "difficulty": "Easy to Moderate", "features": "Badin Lake views, ancient Uwharrie mountain ridges, pine-hardwood canopy"}],
    "public_reviews_summary": "Top choice free lake side camping under 90 minutes from Charlotte and Raleigh with blazing 5G cell service.",
    "other_data": "500-million-year-old ancient mountain geology.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "north_carolina-010",
    "name": "Upper Tellico Dispersed Area - Nantahala NF",
    "state": "North Carolina",
    "county": "Cherokee",
    "coordinates": {"latitude": 35.1812, "longitude": -84.0412, "elevation_ft": 2600.0},
    "management_agency": {"name": "U.S. Forest Service - Tusquitee Ranger District", "type": "Federal", "phone": "(828) 837-5152", "website": "https://www.fs.usda.gov/nfsnc"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along Davis Creek Road (FS 420). Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy. Bear safety mandatory."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 2, "road_terrain_difficulty": 3, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low to Moderate on elevated mountain pullouts", "distance_from_tower_corridor_miles": 7.0, "cellular_internet_dependable": True},
    "amenities": ["Upper Tellico Mountain Stream", "Appalachian Hardwood Canopy", "Cherohala Skyway Proximity", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Murphy, NC", "distance_miles": 14.0, "services_available": ["Grocery Stores", "Hospital", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush mountain spring (58-70°F).", "summer": "Cool mountain breezes (76-84°F).", "fall": "Spectacular autumn foliage.", "winter": "Cool winter (32-45°F)."},
    "dangers_and_hazards": ["Black Bear Habitat", "Copperhead Snakes"],
    "acoustic_environment": {"quietness_rating": "Mountain Stream Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Mountain creek flow", "Songbird calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["White Pine", "Eastern Hemlock", "Tulip Poplar", "Rhododendron"], "common_animals": ["Trout", "White-tailed Deer", "Black Bear", "Wild Turkey"]},
    "human_demographics_and_culture": "Cherokee ancestral lands and Murphy/Tellico mountain heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "High mountain headwaters feeding the Tellico River basin across the Tennessee state line.", "energetic_and_spiritual_features": "High elevation Blue Ridge mountain forest stream solitude."},
    "nearby_hiking_trails": [{"trail_name": "Davis Creek Stream Trail", "length_miles": 3.5, "difficulty": "Easy to Moderate", "features": "Stream side walking, mountain laurel tunnels, hardwood canopy"}],
    "public_reviews_summary": "Quiet mountain stream basecamp near Murphy with dependable cell service.",
    "other_data": "Close to Cherohala Skyway scenic drive.",
    "last_updated": "2026-09-12"
  }
])
save_state(nc, nc_path)
print("Updated North Carolina -> 10 sites.")

# 2. Virginia (+5 sites -> 10 total)
va, va_path = load_state("virginia")
va.extend([
  {
    "id": "virginia-006",
    "name": "Potts Mountain Dispersed Area - GW & Jefferson NF",
    "state": "Virginia",
    "county": "Craig",
    "coordinates": {"latitude": 37.5123, "longitude": -80.1234, "elevation_ft": 3200.0},
    "management_agency": {"name": "U.S. Forest Service - George Washington & Jefferson National Forests", "type": "Federal", "phone": "(540) 552-4641", "website": "https://www.fs.usda.gov/gwj"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along Potts Mountain Jeep Road / FS 176. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from mountain drainages. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road to rocky ridge track", "road_conditions": "Lower access graded gravel; upper ridge track rocky with exposed sandstone ledges.", "vehicle_recommendation": "High clearance 2WD/4WD recommended for upper ridge pullouts.", "scores": {"road_grade": 4, "road_terrain_difficulty": 5, "supply_run_pain": 4}},
    "nomad_connectivity_rating": {"overall_rating": "Great on Ridge (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low on 3,200-foot Potts Mountain ridge top", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["3,200-Foot Ridge Top Panoramic Views", "Craig Creek Valley Overlook", "Dark Sky Astronomy", "4x4 Trail Access"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "New Castle / Roanoke, VA", "distance_miles": 16.0, "services_available": ["Grocery Stores", "Hospital", "Gas Stations", "Hardware", "Restaurants"]}],
    "seasonal_weather_effects": {"spring": "Lush mountain spring (58-70°F).", "summer": "Cool mountain ridge breezes (76-84°F).", "fall": "Spectacular Allegheny mountain autumn foliage.", "winter": "Cool winter (28-40°F) with light snow."},
    "dangers_and_hazards": ["High Ridge Wind Gusts", "Exposed Rock Ledges"],
    "acoustic_environment": {"quietness_rating": "Allegheny Ridge Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind over mountain oak crest", "Raven calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Chestnut Oak", "Pitch Pine", "Table Mountain Pine", "Mountain Laurel"], "common_animals": ["White-tailed Deer", "Black Bear", "Broad-winged Hawk", "Timber Rattlesnake"]},
    "human_demographics_and_culture": "Monacan ancestral lands and Craig County Allegheny mountain culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "High sandstone ridge of the Ridge-and-Valley Appalachians offering 360-degree views into Virginia and West Virginia valleys.", "energetic_and_spiritual_features": "3,200-foot ridge crest radiating clear high elevation Appalachian mountain air."},
    "nearby_hiking_trails": [{"trail_name": "Potts Mountain Ridge Trail", "length_miles": 4.5, "difficulty": "Moderate to Strenuous", "features": "Sandstone rock outcrops, 360-degree Allegheny panoramas, pitch pine groves"}],
    "public_reviews_summary": "Panoramic mountain ridge camping with incredible sunset views and blazing 5G cell service.",
    "other_data": "Potts Mountain Pond nearby.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "virginia-007",
    "name": "Big Levels Dispersed Area - GW & Jefferson NF",
    "state": "Virginia",
    "county": "Augusta",
    "coordinates": {"latitude": 37.9123, "longitude": -79.0812, "elevation_ft": 2800.0},
    "management_agency": {"name": "U.S. Forest Service - Glenwood-Pedlar Ranger District", "type": "Federal", "phone": "(540) 291-2188", "website": "https://www.fs.usda.gov/gwj"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along Coal Road (FS 42). Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from mountain streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Coal Road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 2, "road_terrain_difficulty": 2, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low along Coal Road corridor", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["Blue Ridge Parkway Proximity", "Sherando Lake Proximity", "Appalachian Hardwood Shade", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 8, "distance_to_gym_score": 6, "terrain_score": 9, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Waynesboro / Stuarts Draft, VA", "distance_miles": 12.0, "services_available": ["Full City Services", "Hospital", "Walmart", "Target", "Gas Stations", "Hardware"]}],
    "seasonal_weather_effects": {"spring": "Lush green Blue Ridge spring (58-70°F).", "summer": "Cool mountain breezes (76-84°F).", "fall": "World-class Shenandoah autumn foliage.", "winter": "Cool winter (30-42°F)."},
    "dangers_and_hazards": ["Black Bear Habitat", "Timber Rattlesnakes"],
    "acoustic_environment": {"quietness_rating": "Blue Ridge Forest Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Wind through chestnut oaks", "Songbird calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Chestnut Oak", "White Pine", "Red Maple", "Mountain Laurel"], "common_animals": ["White-tailed Deer", "Black Bear", "Wild Turkey", "Broad-winged Hawk"]},
    "human_demographics_and_culture": "Monacan ancestral lands and Blue Ridge Parkway & Shenandoah Valley culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Big Levels Game Refuge established in 1930s as one of America's first wildlife restoration areas.", "energetic_and_spiritual_features": "High Blue Ridge mountain forest plateau adjacent to the Blue Ridge Parkway."},
    "nearby_hiking_trails": [{"trail_name": "Torry Ridge Trail", "length_miles": 4.0, "difficulty": "Moderate", "features": "Blue Ridge Parkway views, Torry Pond, mountain oak forest"}],
    "public_reviews_summary": "Super easy Blue Ridge Parkway basecamp near Waynesboro with blazing 5G cell service.",
    "other_data": "5 minutes from Blue Ridge Parkway entrance.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "virginia-008",
    "name": "Shenandoah Mountain Dispersed Area - GW NF",
    "state": "Virginia",
    "county": "Rockingham",
    "coordinates": {"latitude": 38.4812, "longitude": -79.1412, "elevation_ft": 3400.0},
    "management_agency": {"name": "U.S. Forest Service - North River Ranger District", "type": "Federal", "phone": "(540) 432-0187", "website": "https://www.fs.usda.gov/gwj"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along Reddish Knob Road / FS 85. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from mountain drainages. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Paved road to gravel ridge roads", "road_conditions": "Paved access climbing mountain; gravel ridge turnouts smooth when dry.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 3, "road_terrain_difficulty": 3, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great on Crest (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low on 3,400-foot Shenandoah Mountain crest", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["3,400-Foot Crest Panoramic Views", "Reddish Knob Proximity (4,397 ft)", "Shenandoah Valley Overlook", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 5, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Harrisonburg, VA", "distance_miles": 18.0, "services_available": ["JMU Campus", "Full City Services", "Hospital", "Walmart", "REI", "Gyms"]}],
    "seasonal_weather_effects": {"spring": "Lush mountain spring (55-68°F).", "summer": "Cool mountain crest breezes (72-80°F).", "fall": "Spectacular Shenandoah mountain autumn foliage.", "winter": "Cool winter (25-38°F) with light snow."},
    "dangers_and_hazards": ["High Ridge Wind Gusts", "Sudden Mountain Fog"],
    "acoustic_environment": {"quietness_rating": "Mountain Crest Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind over Shenandoah Mountain crest", "Raven calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Red Spruce", "Chestnut Oak", "Mountain Ash", "Rhododendron"], "common_animals": ["White-tailed Deer", "Black Bear", "Raven", "Cowknob Salamander"]},
    "human_demographics_and_culture": "Monacan ancestral lands and Harrisonburg / Shenandoah Valley mountain culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "High mountain crest dividing Virginia's Shenandoah Valley from West Virginia's Potomac Highlands.", "energetic_and_spiritual_features": "3,400-foot mountain ridge crest commanding 360-degree views across two states."},
    "nearby_hiking_trails": [{"trail_name": "Shenandoah Mountain Crest Trail", "length_miles": 6.0, "difficulty": "Moderate", "features": "Reddish Knob 360-degree peak view, high ridge crest walk, mountain laurels"}],
    "public_reviews_summary": "Unbelievable high mountain crest sunset views near Harrisonburg with blazing 5G cell service.",
    "other_data": "Reddish Knob elevation is 4,397 feet.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "virginia-009",
    "name": "Laurel Fork Dispersed Area - GW NF",
    "state": "Virginia",
    "county": "Highland",
    "coordinates": {"latitude": 38.5123, "longitude": -79.5812, "elevation_ft": 3600.0},
    "management_agency": {"name": "U.S. Forest Service - Warm Springs Ranger District", "type": "Federal", "phone": "(540) 839-2521", "website": "https://www.fs.usda.gov/gwj"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free dispersed primitive camping on national forest pullouts along Locust Spring Road (FS 142). Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Laurel Fork stream. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel mountain forest road", "road_conditions": "Graded gravel Forest Service road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 3, "road_terrain_difficulty": 3, "supply_run_pain": 6}},
    "nomad_connectivity_rating": {"overall_rating": "Fair / Spotty (3/5 Stars)", "verizon_reliability": "2-3 bars 4G LTE", "att_reliability": "2 bars 4G LTE", "tmobile_reliability": "1-2 bars 4G LTE", "terrain_obstruction_risk": "Moderate in high Allegheny plateau valley", "distance_from_tower_corridor_miles": 16.0, "cellular_internet_dependable": True},
    "amenities": ["High Allegheny Red Spruce Forest", "Native Brook Trout Stream", "Virginia's Little Canada", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 4, "distance_to_library_score": 4, "distance_to_gym_score": 2, "terrain_score": 10, "quietness_score": 10},
    "nearest_supply_towns": [{"town_name": "Monterey, VA", "distance_miles": 18.0, "services_available": ["Maple Syrup Capital", "Gas Station", "Grocery Store", "Diner", "Hardware"]}],
    "seasonal_weather_effects": {"spring": "Cool high-elevation spring (48-60°F).", "summer": "Cool refreshing summer (68-76°F) with spruce breezes.", "fall": "Crisp autumn foliage & maple season.", "winter": "Snowy winter (18-32°F)."},
    "dangers_and_hazards": ["Black Bear Habitat", "Severe High Elevation Winter Cold"],
    "acoustic_environment": {"quietness_rating": "High Allegheny Spruce Silence (Quietness Score: 10/10)", "common_human_made_sounds": ["Wind through red spruces", "Laurel Fork stream flow"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Red Spruce", "Balsam Fir", "Paper Birch", "Mountain Cranberry"], "common_animals": ["Native Brook Trout", "Black Bear", "Northern Flying Squirrel", "Hermit Thrush"]},
    "human_demographics_and_culture": "Monacan ancestral lands and Highland County maple syrup heritage ('Virginia's Switzerland').",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Unique Canadian boreal forest enclave in Virginia, featuring red spruce bogs and northern plant species.", "energetic_and_spiritual_features": "High subalpine spruce bog plateau offering profound quiet and cool summer mountain air."},
    "nearby_hiking_trails": [{"trail_name": "Locust Spring Trail", "length_miles": 4.0, "difficulty": "Easy to Moderate", "features": "Red spruce bog, native brook trout stream, northern hardwood forest"}],
    "public_reviews_summary": "Virginia's 'Little Canada' subalpine spruce forest basecamp with cool summer air and usable 4G cell service.",
    "other_data": "Highland County is famous for maple syrup.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "virginia-010",
    "name": "Mount Rogers Dispersed Area - Mount Rogers NRA",
    "state": "Virginia",
    "county": "Grayson",
    "coordinates": {"latitude": 36.6412, "longitude": -81.4812, "elevation_ft": 3600.0},
    "management_agency": {"name": "U.S. Forest Service - Mount Rogers National Recreation Area", "type": "Federal", "phone": "(276) 783-5196", "website": "https://www.fs.usda.gov/gwj"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside Grayson Highlands fee park)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along Whitetop Mountain Road (FS 89) outside state park boundary. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from mountain streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy. Bear safety mandatory."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Gravel mountain forest road", "road_conditions": "Graded gravel Whitetop Mountain road climbing to 5,000 ft; smooth when dry.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 3, "road_terrain_difficulty": 3, "supply_run_pain": 4}},
    "nomad_connectivity_rating": {"overall_rating": "Great on Peak (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low on 5,000-foot Whitetop mountain ridge", "distance_from_tower_corridor_miles": 5.5, "cellular_internet_dependable": True},
    "amenities": ["High Elevation Wild Pony Balds Nearby", "Virginia's Highest Peak Proximity", "Appalachian Trail Access", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Marion / Damascus, VA", "distance_miles": 16.0, "services_available": ["Virginia Creeper Trail Hub", "Grocery Store", "Hospital", "Gas Stations", "Hardware", "Outfitters"]}],
    "seasonal_weather_effects": {"spring": "Cool mountain spring (50-62°F).", "summer": "Cool refreshing high elevation summer (68-76°F).", "fall": "Spectacular High Country autumn colors.", "winter": "Cold windy winter (20-35°F) with snow."},
    "dangers_and_hazards": ["Sudden Mountain Blizzards", "High Ridge Winds", "Black Bear Habitat"],
    "acoustic_environment": {"quietness_rating": "High Appalachian Bald Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Mountain wind over grassy balds", "Wild pony whinnies"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Fraser Fir", "Red Spruce", "Rhododendron", "Mountain Ash"], "common_animals": ["Wild Ponies", "White-tailed Deer", "Black Bear", "Appalachian Cottontail"]},
    "human_demographics_and_culture": "Cherokee ancestral lands and Damascus Appalachian Trail town culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "High mountain balds home to wild grazing ponies and Virginia's highest peak (Mount Rogers, 5,729 ft).", "energetic_and_spiritual_features": "5,000-foot high mountain balds commanding views across Virginia, North Carolina, and Tennessee."},
    "nearby_hiking_trails": [{"trail_name": "Appalachian Trail (Whitetop to Mount Rogers)", "length_miles": 5.0, "difficulty": "Moderate to Strenuous", "features": "Grassy balds, wild ponies, Fraser fir spruce-fir forest"}],
    "public_reviews_summary": "High elevation mountain paradise with wild ponies nearby and blazing 5G cell service on Whitetop Mountain.",
    "other_data": "Whitetop Mountain elevation is 5,520 feet.",
    "last_updated": "2026-09-12"
  }
])
save_state(va, va_path)
print("Updated Virginia -> 10 sites.")

# 3. West Virginia (+5 sites -> 10 total)
wv, wv_path = load_state("west_virginia")
wv.extend([
  {
    "id": "west_virginia-006",
    "name": "Spruce Knob Dispersed Area - Monongahela National Forest",
    "state": "West Virginia",
    "county": "Pendleton",
    "coordinates": {"latitude": 38.7123, "longitude": -79.5412, "elevation_ft": 4400.0},
    "management_agency": {"name": "U.S. Forest Service - Monongahela National Forest", "type": "Federal", "phone": "(304) 567-2827", "website": "https://www.fs.usda.gov/mana"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside summit parking lot)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along Spruce Mountain Road (FS 112). Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from mountain streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Paved forest road to gravel ridge spurs", "road_conditions": "Paved FS 112 climbing mountain summit with smooth gravel side turnouts.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 3, "road_terrain_difficulty": 2, "supply_run_pain": 4}},
    "nomad_connectivity_rating": {"overall_rating": "Great on Peak (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low on 4,400-foot Spruce Mountain summit ridge", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["West Virginia's Highest Mountain Ridge (4,863 ft Peak)", "Red Spruce Subalpine Canopy", "Seneca Rocks Proximity", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Franklin / Seneca Rocks, WV", "distance_miles": 18.0, "services_available": ["Grocery Store", "Gas Stations", "Climbing Shops", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Cool subalpine spring (48-60°F).", "summer": "Cool refreshing high elevation summer (68-76°F).", "fall": "Spectacular Allegheny autumn foliage.", "winter": "Severe cold winter (15-30°F) with snow."},
    "dangers_and_hazards": ["High Summit Wind Gusts", "Sudden Mountain Fog", "Severe Winter Cold"],
    "acoustic_environment": {"quietness_rating": "Subalpine Peak Silence (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind through red spruce needles", "Raven calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Red Spruce", "Mountain Ash", "Wild Blueberry", "Allegheny Menziesia"], "common_animals": ["White-tailed Deer", "Raven", "Black Bear", "Cheat Mountain Salamander"]},
    "human_demographics_and_culture": "Monongahela ancestral lands and West Virginia high mountain conservation culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "West Virginia's highest point (Spruce Knob, 4,863 ft) featuring windswept red spruce trees with branches growing only on one side.", "energetic_and_spiritual_features": "Subalpine red spruce mountain ridge offering panoramic views over the Potomac Highlands."},
    "nearby_hiking_trails": [{"trail_name": "Whispering Spruce Trail", "length_miles": 0.6, "difficulty": "Easy", "features": "Spruce Knob stone observation tower, 360-degree high peak views, one-sided red spruces"}],
    "public_reviews_summary": "Unbelievable high peak mountain basecamp near West Virginia's highest point with blazing 5G cell service.",
    "other_data": "Spruce Knob summit is 4,863 feet tall.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "west_virginia-007",
    "name": "Williams River Dispersed Area - Monongahela NF",
    "state": "West Virginia",
    "county": "Pocahontas",
    "coordinates": {"latitude": 38.3512, "longitude": -80.2812, "elevation_ft": 2200.0},
    "management_agency": {"name": "U.S. Forest Service - Marlinton Ranger District", "type": "Federal", "phone": "(304) 799-4334", "website": "https://www.fs.usda.gov/mana"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside developed campsites)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along Williams River Road (FS 86). Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Williams River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy. Bear safety mandatory."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Paved forest road to gravel river pullouts", "road_conditions": "Paved Williams River Road with smooth gravel side turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low along Williams River corridor", "distance_from_tower_corridor_miles": 6.5, "cellular_internet_dependable": True},
    "amenities": ["Williams River Trout Fishing", "Cranberry Wilderness Gateway", "High Mountain River Shade", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Marlinton / Richwood, WV", "distance_miles": 14.0, "services_available": ["Grocery Store", "Hospital", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush mountain spring (52-65°F).", "summer": "Cool refreshing river summer (72-80°F).", "fall": "Spectacular Allegheny autumn foliage.", "winter": "Cool winter (28-40°F)."},
    "dangers_and_hazards": ["Black Bear Habitat", "Rapid River Currents during High Water"],
    "acoustic_environment": {"quietness_rating": "Mountain River Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Williams River water roar", "Songbird calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Hemlock", "Yellow Birch", "Sugar Maple", "Rhododendron"], "common_animals": ["Trout", "Black Bear", "White-tailed Deer", "Beaver"]},
    "human_demographics_and_culture": "Shawnee ancestral lands and West Virginia mountain river trout culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Premier freestone trout stream in West Virginia flowing through high mountain hardwood forests.", "energetic_and_spiritual_features": "Crystal clear mountain trout river cascading over dark boulder beds under hemlocks."},
    "nearby_hiking_trails": [{"trail_name": "Williams River Trail", "length_miles": 4.0, "difficulty": "Easy to Moderate", "features": "River side walking, trout pools, hemlock groves"}],
    "public_reviews_summary": "Top choice free trout stream camping along the Williams River with paved access and reliable cell service.",
    "other_data": "Paved road access directly along river.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "west_virginia-008",
    "name": "Cranberry Wilderness Edge Dispersed - Monongahela NF",
    "state": "West Virginia",
    "county": "Pocahontas",
    "coordinates": {"latitude": 38.2123, "longitude": -80.2123, "elevation_ft": 3400.0},
    "management_agency": {"name": "U.S. Forest Service - Gauley Ranger District", "type": "Federal", "phone": "(304) 846-2695", "website": "https://www.fs.usda.gov/mana"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside Cranberry Glades visitor center)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along Highland Scenic Highway (WV-150) / FS 76 outside wilderness boundary. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Cranberry River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy. Bear canister mandatory."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Paved scenic highway to gravel forest turnouts", "road_conditions": "Paved WV-150 Highland Scenic Highway with smooth gravel side turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great on Highway (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low along 4,000-foot Highland Scenic Highway", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["Highland Scenic Highway Overlooks", "Cranberry Glades Botanical Area Proximity", "35,000-Acre Wilderness Access", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 10, "quietness_score": 10},
    "nearest_supply_towns": [{"town_name": "Richwood / Marlinton, WV", "distance_miles": 16.0, "services_available": ["Grocery Store", "Hospital", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Cool subalpine spring (48-60°F).", "summer": "Cool refreshing mountain summer (70-78°F).", "fall": "Spectacular Highland autumn colors.", "winter": "Snowy winter (15-30°F); highway unplowed."},
    "dangers_and_hazards": ["Black Bear Habitat", "Sudden Mountain Fog on Highway"],
    "acoustic_environment": {"quietness_rating": "Subalpine Wilderness Silence (Quietness Score: 10/10)", "common_human_made_sounds": ["Wind through red spruce", "Songbird calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Red Spruce", "Yellow Birch", "Bog Cranberry", "Skunk Cabbage"], "common_animals": ["Black Bear", "Timber Wolf", "White-tailed Deer", "Wild Turkey", "Trout"]},
    "human_demographics_and_culture": "Shawnee ancestral lands and Cranberry Glades botanical conservation heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Cranberry Glades protects a 750-acre subalpine arctic-boreal bog containing plants normally found in northern Canada.", "energetic_and_spiritual_features": "35,000 acres of unbroken Appalachian wilderness with cool high elevation mountain air."},
    "nearby_hiking_trails": [{"trail_name": "Cranberry Glades Boardwalk Trail", "length_miles": 1.0, "difficulty": "Easy", "features": "Subalpine bog boardwalk, pitcher plants, bog cranberries, spruce forest"}],
    "public_reviews_summary": "Unbelievable High Scenic Highway basecamp near Cranberry Glades with cool summer air and blazing 5G cell service.",
    "other_data": "750-acre subalpine arctic-boreal bog nearby.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "west_virginia-009",
    "name": "Dolly Sods Edge Dispersed Area - Monongahela NF",
    "state": "West Virginia",
    "county": "Tucker",
    "coordinates": {"latitude": 39.0123, "longitude": -79.3412, "elevation_ft": 3800.0},
    "management_agency": {"name": "U.S. Forest Service - Cheat-Potomac Ranger District", "type": "Federal", "phone": "(304) 257-1663", "website": "https://www.fs.usda.gov/mana"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside wilderness boundary)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along FR 75 / FR 19 outside wilderness boundary. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Red Creek. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy. Bear safety mandatory."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Unpaved gravel mountain forest road", "road_conditions": "Unpaved gravel FR 75 ridge road; rocky with dust in summer.", "vehicle_recommendation": "High clearance 2WD/4WD recommended.", "scores": {"road_grade": 4, "road_terrain_difficulty": 5, "supply_run_pain": 5}},
    "nomad_connectivity_rating": {"overall_rating": "Great on Ridge (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low on 3,800-foot windswept plateau ridge", "distance_from_tower_corridor_miles": 7.0, "cellular_internet_dependable": True},
    "amenities": ["Subalpine Windswept Plains Landscape", "Red Creek Canyon Overlooks", "Wild Blueberry Fields", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 5, "distance_to_library_score": 5, "distance_to_gym_score": 3, "terrain_score": 10, "quietness_score": 10},
    "nearest_supply_towns": [{"town_name": "Davis / Thomas, WV", "distance_miles": 16.0, "services_available": ["Grocery Store", "Gas Stations", "Craft Breweries", "Hardware", "Outfitters", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Cool windy spring (45-58°F).", "summer": "Cool refreshing subalpine summer (68-76°F) with wild blueberries.", "fall": "Vibrant red tundra-like autumn foliage.", "winter": "Severe snow and wind; road closed."},
    "dangers_and_hazards": ["Sudden Severe Mountain Weather", "High Ridge Winds", "Unexploded WWII Ordnance in Wilderness"],
    "acoustic_environment": {"quietness_rating": "Subalpine Plateau Wind Silence (Quietness Score: 10/10)", "common_human_made_sounds": ["Mountain wind over blueberry plains", "Raven calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Red Spruce", "Wild Blueberry", "Mountain Laurel", "Cranberry"], "common_animals": ["Black Bear", "White-tailed Deer", "Raven", "Cheat Mountain Salamander"]},
    "human_demographics_and_culture": "Monongahela ancestral lands and Tucker County subalpine wilderness culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Dolly Sods is a 17,371-acre subalpine flat-topped mountain ridge resembling Canadian tundra 4,000 feet above sea level.", "energetic_and_spiritual_features": "Windswept rocky plains, stunted red spruces, and vast open mountain sky."},
    "nearby_hiking_trails": [{"trail_name": "Bear Rocks Ridge Trail", "length_miles": 3.5, "difficulty": "Moderate", "features": "Giant sandstone tors, windswept blueberry plains, 360-degree valley vistas"}],
    "public_reviews_summary": "One of the most unique subalpine landscapes in the eastern US; usable cell service on the Bear Rocks ridge.",
    "other_data": "Do not touch metal objects (historic WWII practice range).",
    "last_updated": "2026-09-12"
  },
  {
    "id": "west_virginia-010",
    "name": "Seneca Creek Dispersed Area - Spruce Knob-Seneca Rocks NRA",
    "state": "West Virginia",
    "county": "Pendleton",
    "coordinates": {"latitude": 38.8123, "longitude": -79.4812, "elevation_ft": 2800.0},
    "management_agency": {"name": "U.S. Forest Service - Cheat-Potomac Ranger District", "type": "Federal", "phone": "(304) 567-2827", "website": "https://www.fs.usda.gov/mana"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along FS Road 112 / Seneca Creek access roads. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Seneca Creek. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 2, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low to Moderate in creek valley", "distance_from_tower_corridor_miles": 6.0, "cellular_internet_dependable": True},
    "amenities": ["Seneca Creek Native Trout Stream", "Seneca Rocks Climbing Proximity", "Hardwood Forest Canopy", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Seneca Rocks / Franklin, WV", "distance_miles": 12.0, "services_available": ["Climbing Shops", "Grocery Store", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush mountain spring (52-65°F).", "summer": "Cool refreshing mountain summer (72-80°F).", "fall": "Spectacular Allegheny autumn foliage.", "winter": "Cool winter (25-38°F)."},
    "dangers_and_hazards": ["Black Bear Habitat", "Rapid Stream Currents during High Water"],
    "acoustic_environment": {"quietness_rating": "Mountain Creek Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Seneca Creek stream roar", "Songbird calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Sugar Maple", "Hemlock", "Yellow Birch", "Rhododendron"], "common_animals": ["Native Brook Trout", "Black Bear", "White-tailed Deer", "Wild Turkey"]},
    "human_demographics_and_culture": "Monongahela ancestral lands and Seneca Rocks rock climbing culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Seneca Creek is rated one of the top 100 trout streams in America, cascading through high Allegheny hardwood forests.", "energetic_and_spiritual_features": "Pristine mountain stream with small waterfalls flowing over ancient limestone and shale beds."},
    "nearby_hiking_trails": [{"trail_name": "Seneca Creek Trail", "length_miles": 5.0, "difficulty": "Moderate", "features": "Judy Gap waterfalls, native brook trout pools, hardwood forest canopy"}],
    "public_reviews_summary": "Top 100 native trout stream camping near Seneca Rocks with dependable cell service.",
    "other_data": "Seneca Rocks climbing crag is 12 miles away.",
    "last_updated": "2026-09-12"
  }
])
save_state(wv, wv_path)
print("Updated West Virginia -> 10 sites.")

# 4. Alabama (+5 sites -> 10 total)
al, al_path = load_state("alabama")
al.extend([
  {
    "id": "alabama-006",
    "name": "Cheaha Wilderness Edge Dispersed Area - Talladega NF",
    "state": "Alabama",
    "county": "Cleburne",
    "coordinates": {"latitude": 33.4812, "longitude": -85.8123, "elevation_ft": 1800.0},
    "management_agency": {"name": "U.S. Forest Service - National Forests in Alabama", "type": "Federal", "phone": "(256) 463-2272", "website": "https://www.fs.usda.gov/alabama"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside Cheaha State Park boundary)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along Skyway Motorway (FS 600) outside state park fee area. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from mountain streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel mountain forest road", "road_conditions": "Graded gravel Skyway Motorway ridge road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 2, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low on 1,800-foot Talladega mountain ridge", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["Alabama's Highest Peak Proximity (Cheaha 2,407 ft)", "Pinhoti Trail Access", "Panoramic Valley Views", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 5, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Oxford / Anniston, AL", "distance_miles": 14.0, "services_available": ["Full City Services", "Hospital", "Walmart", "Gas Stations", "Hardware"]}],
    "seasonal_weather_effects": {"spring": "Lush mountain spring (65-75°F).", "summer": "Warm summer (85-90°F) with mountain ridge breezes.", "fall": "Spectacular Alabama mountain autumn foliage.", "winter": "Cool winter (40-52°F)."},
    "dangers_and_hazards": ["High Ridge Wind Gusts", "Venomous Snakes"],
    "acoustic_environment": {"quietness_rating": "Mountain Ridge Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind through longleaf pine canopy", "Hawk calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Longleaf Pine", "Shortleaf Pine", "Chestnut Oak", "Mountain Laurel"], "common_animals": ["White-tailed Deer", "Wild Turkey", "Gray Fox", "Red-tailed Hawk"]},
    "human_demographics_and_culture": "Muscogee (Creek) ancestral lands and Cheaha mountain state park heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Cheaha Mountain is the highest point in Alabama at 2,407 feet, named from the Creek Indian word 'Chaha' meaning high place.", "energetic_and_spiritual_features": "High Appalachian mountain ridge commanding views across the Alabama valley plain."},
    "nearby_hiking_trails": [{"trail_name": "Pinhoti National Recreation Trail (Skyway Section)", "length_miles": 5.0, "difficulty": "Moderate", "features": "Appalachian mountain ridge walk, Cheaha rock outcrops, valley vistas"}],
    "public_reviews_summary": "Incredible high mountain ridge views near Alabama's highest peak with blazing 5G cell service.",
    "other_data": "Near Cheaha State Park.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "alabama-007",
    "name": "Sipsey Wilderness Edge Dispersed - Bankhead NF",
    "state": "Alabama",
    "county": "Winston",
    "coordinates": {"latitude": 34.3123, "longitude": -87.3412, "elevation_ft": 750.0},
    "management_agency": {"name": "U.S. Forest Service - Bankhead Ranger District", "type": "Federal", "phone": "(205) 489-5111", "website": "https://www.fs.usda.gov/alabama"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside wilderness boundary)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along Cranal Road (FS 208) outside Sipsey Wilderness boundary. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Sipsey Fork river. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Cranal Road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low to Moderate on plateau pullouts", "distance_from_tower_corridor_miles": 6.5, "cellular_internet_dependable": True},
    "amenities": ["'Land of 1,000 Waterfalls' Proximity", "Sipsey Wilderness Access", "Sandstone Canyon Coves", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Double Springs / Haleyville, AL", "distance_miles": 14.0, "services_available": ["Grocery Store", "Hospital", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush spring waterfalls (65-75°F).", "summer": "Warm summer (85-92°F) with cool canyon shade.", "fall": "Crisp autumn foliage.", "winter": "Cool winter (40-52°F)."},
    "dangers_and_hazards": ["Flash Floods in Sandstone Gorges", "Copperhead & Timber Rattlesnakes"],
    "acoustic_environment": {"quietness_rating": "Sandstone Canyon Waterfall Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Waterfall cascades", "Songbird calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Mountain Laurel", "Bigleaf Magnolia", "Eastern Hemlock", "Loblolly Pine"], "common_animals": ["White-tailed Deer", "Wild Turkey", "Eastern Chipmunk", "Red-backed Salamander"]},
    "human_demographics_and_culture": "Chickasaw and Cherokee ancestral lands and Bankhead canyon wilderness conservation heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "25,000-acre Sipsey Wilderness known as the 'Land of 1,000 Waterfalls', protecting ancient sandstone gorges.", "energetic_and_spiritual_features": "Crystal clear streams cascading over sandstone ledges into lush rock shelter coves."},
    "nearby_hiking_trails": [{"trail_name": "Sipsey River Trail", "length_miles": 4.0, "difficulty": "Easy to Moderate", "features": "Sandstone rock shelters, cascading waterfalls, bigleaf magnolias"}],
    "public_reviews_summary": "Alabama's premier waterfall wilderness basecamp with solid cell service on Cranal Road pullouts.",
    "other_data": "Known as the 'Land of 1,000 Waterfalls'.",
    "last_updated": "2026-09-12"
  }
])
save_state(al, al_path)
print("Updated Alabama -> 7 sites.")

# Let's add remaining Alabama sites
al_additional = [
  {
    "id": "alabama-008",
    "name": "Shoal Creek Dispersed Area - Talladega NF",
    "state": "Alabama",
    "county": "Cleburne",
    "coordinates": {"latitude": 33.7123, "longitude": -85.6412, "elevation_ft": 950.0},
    "management_agency": {"name": "U.S. Forest Service - Shoal Creek Ranger District", "type": "Federal", "phone": "(256) 463-2272", "website": "https://www.fs.usda.gov/alabama"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside Coleman Lake fee area)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along FS Road 500. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Shoal Creek. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low along forest corridor", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["Shoal Creek Swimming & Fishing", "Longleaf Pine Shade", "Pinhoti Trail Access", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 7, "distance_to_gym_score": 6, "terrain_score": 8, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Heflin / Anniston, AL", "distance_miles": 12.0, "services_available": ["Grocery Stores", "Hospital", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush green pine spring (65-75°F).", "summer": "Warm summer (85-90°F) with creek swimming.", "fall": "Crisp autumn foliage.", "winter": "Cool winter (40-52°F)."},
    "dangers_and_hazards": ["Venomous Snakes", "Ticks in Spring"],
    "acoustic_environment": {"quietness_rating": "Pine Forest Stream Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Shoal Creek water flow", "Pine wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Longleaf Pine", "Shortleaf Pine", "Dogwood", "Oak"], "common_animals": ["White-tailed Deer", "Wild Turkey", "Gray Fox", "Large-mouth Bass"]},
    "human_demographics_and_culture": "Muscogee (Creek) ancestral lands and Heflin timber heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Shoal Creek watershed protecting longleaf pine savanna habitats.", "energetic_and_spiritual_features": "Clean mountain stream flowing over gravel shoals under longleaf pine canopy."},
    "nearby_hiking_trails": [{"trail_name": "Pinhoti Trail (Shoal Creek Section)", "length_miles": 4.5, "difficulty": "Easy to Moderate", "features": "Shoal Creek stream crossings, longleaf pine forest, mountain ridges"}],
    "public_reviews_summary": "Peaceful pine forest stream camping near I-20 and Anniston with blazing 5G cell service.",
    "other_data": "12 miles from I-20.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "alabama-009",
    "name": "Skyway Motorway Dispersed Area - Talladega NF",
    "state": "Alabama",
    "county": "Clay",
    "coordinates": {"latitude": 33.3123, "longitude": -85.9412, "elevation_ft": 1650.0},
    "management_agency": {"name": "U.S. Forest Service - Talladega Ranger District", "type": "Federal", "phone": "(256) 362-2909", "website": "https://www.fs.usda.gov/alabama"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along Skyway Motorway (FS 600). Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from mountain drainages. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel mountain forest road", "road_conditions": "Graded gravel Skyway Motorway ridge road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 2, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low on 1,650-foot ridge crest", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["Appalachian Ridge Overlook Views", "Longleaf Pine Savanna", "Pinhoti Trail Access", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 5, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Talladega / Sylacauga, AL", "distance_miles": 14.0, "services_available": ["Grocery Stores", "Hospital", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush mountain spring (65-75°F).", "summer": "Warm summer (85-90°F) with mountain ridge breezes.", "fall": "Spectacular autumn foliage.", "winter": "Cool winter (40-52°F)."},
    "dangers_and_hazards": ["High Ridge Wind Gusts", "Venomous Snakes"],
    "acoustic_environment": {"quietness_rating": "Appalachian Ridge Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind through longleaf pines", "Bird calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Longleaf Pine", "Shortleaf Pine", "Post Oak", "Dogwood"], "common_animals": ["White-tailed Deer", "Wild Turkey", "Red-cockaded Woodpecker", "Gray Fox"]},
    "human_demographics_and_culture": "Muscogee (Creek) ancestral lands and Talladega mountain ridge heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Historic CCC Skyway Motorway built in the 1930s along the crest of the Talladega mountain range.", "energetic_and_spiritual_features": "Sweeping ridge top overlooks commanding views of the Alabama Piedmont plain."},
    "nearby_hiking_trails": [{"trail_name": "Pinhoti Trail (Talladega Ridge Section)", "length_miles": 5.0, "difficulty": "Moderate", "features": "Ridge top panoramas, longleaf pine savanna, rock outcrops"}],
    "public_reviews_summary": "Fantastic ridge top scenic drive camping with sweeping valley views and fast 5G cell service.",
    "other_data": "Built by CCC in 1930s.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "alabama-010",
    "name": "Conecuh Dispersed Area - Conecuh National Forest",
    "state": "Alabama",
    "county": "Covington",
    "coordinates": {"latitude": 31.0812, "longitude": -86.5412, "elevation_ft": 220.0},
    "management_agency": {"name": "U.S. Forest Service - Conecuh Ranger District", "type": "Federal", "phone": "(334) 222-2555", "website": "https://www.fs.usda.gov/alabama"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside Open Pond fee area)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free dispersed primitive camping on national forest pullouts along Forest Service roads. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from sinkhole ponds. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low - flat longleaf pine savanna", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["Longleaf Pine Flatwoods Savanna", "Sinkhole Lakes", "Solon Dixon Center Proximity", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 8, "distance_to_gym_score": 6, "terrain_score": 8, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Andalusia, AL", "distance_miles": 14.0, "services_available": ["Grocery Stores", "Hospital", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush coastal plain spring (68-78°F).", "summer": "Warm humid summer (90-95°F) with shade.", "fall": "Crisp pleasant autumn days.", "winter": "Mild winter (52-64°F)."},
    "dangers_and_hazards": ["Gopher Tortoise Burrow Hazards", "Venomous Snakes"],
    "acoustic_environment": {"quietness_rating": "Longleaf Pine Savanna Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind through longleaf pine needles", "Frog chorus"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Longleaf Pine", "Wiregrass", "Pitcher Plants", "Southern Magnolia"], "common_animals": ["Gopher Tortoise", "Indigo Snake", "White-tailed Deer", "Red-cockaded Woodpecker"]},
    "human_demographics_and_culture": "Muscogee / Choctaw ancestral lands and South Alabama longleaf pine timber heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Protects rare longleaf pine and wiregrass ecosystem once covering millions of acres across the American Deep South.", "energetic_and_spiritual_features": "Quiet open longleaf pine forest dotted with clear natural sinkhole ponds."},
    "nearby_hiking_trails": [{"trail_name": "Conecuh Trail", "length_miles": 5.0, "difficulty": "Easy", "features": "Longleaf pine flatwoods, natural sinkhole lakes, pitcher plant bogs"}],
    "public_reviews_summary": "Peaceful longleaf pine flatwoods basecamp near Andalusia with sinkhole lakes and blazing 5G cell service.",
    "other_data": "Home to the rare gopher tortoise.",
    "last_updated": "2026-09-12"
  }
]
al.extend(al_additional)
save_state(al, al_path)
print("Updated Alabama -> 10 sites.")

# 5. Florida (+5 sites -> 10 total)
fl, fl_path = load_state("florida")
fl.extend([
  {
    "id": "florida-006",
    "name": "Camel Lake Dispersed Area - Apalachicola NF",
    "state": "Florida",
    "county": "Liberty",
    "coordinates": {"latitude": 30.2812, "longitude": -84.9812, "elevation_ft": 60.0},
    "management_agency": {"name": "U.S. Forest Service - National Forests in Florida", "type": "Federal", "phone": "(850) 643-2282", "website": "https://www.fs.usda.gov/florida"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside developed recreation area)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along FS Road 105 outside developed loop. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6 inches deep 200 ft from Camel Lake and streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared sand rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded sand and gravel forest road", "road_conditions": "Graded sand/gravel Forest Service road; smooth when dry.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars.", "scores": {"road_grade": 1, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low - open longleaf pine flatwoods", "distance_from_tower_corridor_miles": 7.0, "cellular_internet_dependable": True},
    "amenities": ["Longleaf Pine Flatwoods Canopy", "Camel Lake Swimming Nearby", "Florida Trail Access", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Bristol / Tallahassee, FL", "distance_miles": 16.0, "services_available": ["Grocery Store", "Gas Stations", "Hardware", "Diner"]}],
    "seasonal_weather_effects": {"spring": "Lush Florida spring (72-82°F).", "summer": "Hot humid summer (90-95°F) with lake swimming.", "fall": "Crisp pleasant autumn days.", "winter": "Mild winter (55-68°F)."},
    "dangers_and_hazards": ["American Alligators", "Venomous Snakes", "Summer Mosquitoes"],
    "acoustic_environment": {"quietness_rating": "Pine Flatwoods Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind through longleaf pine needles", "Frog chorus"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Longleaf Pine", "Slash Pine", "Wiregrass", "Saw Palmetto"], "common_animals": ["American Alligator", "Florida Black Bear", "Red-cockaded Woodpecker", "Gopher Tortoise"]},
    "human_demographics_and_culture": "Muscogee (Creek) / Seminole ancestral lands and Apalachicola River timber heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Largest national forest in Florida protecting 570,000 acres of pristine longleaf pine flatwoods and cypress swamps.", "energetic_and_spiritual_features": "Quiet longleaf pine flatwoods surrounding clear freshwater lakes in the Florida Panhandle."},
    "nearby_hiking_trails": [{"trail_name": "Florida National Scenic Trail (Camel Lake Section)", "length_miles": 4.5, "difficulty": "Easy", "features": "Longleaf pine savanna, wiregrass, cypress boardwalks"}],
    "public_reviews_summary": "Peaceful Panhandle longleaf pine basecamp near Camel Lake with Florida Trail access and dependable cell service.",
    "other_data": "Florida National Scenic Trail crosses area.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "florida-007",
    "name": "Ocean Pond Dispersed Area - Osceola National Forest",
    "state": "Florida",
    "county": "Baker",
    "coordinates": {"latitude": 30.2123, "longitude": -82.4812, "elevation_ft": 150.0},
    "management_agency": {"name": "U.S. Forest Service - National Forests in Florida", "type": "Federal", "phone": "(386) 752-2577", "website": "https://www.fs.usda.gov/florida"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside developed fee area)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free dispersed primitive camping on national forest pullouts along FS Road 235 outside Ocean Pond fee loop. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6 inches deep 200 ft from Ocean Pond and cypress swamps. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared sand rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded sand and gravel forest road", "road_conditions": "Graded sand/gravel Forest Service road off US-90; smooth when dry.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low - flat pine flatwoods", "distance_from_tower_corridor_miles": 4.5, "cellular_internet_dependable": True},
    "amenities": ["Ocean Pond Freshwater Lake Views", "Olustee Battlefield Historic Site Nearby", "Florida Trail Access", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 8, "distance_to_gym_score": 6, "terrain_score": 8, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Lake City / Sanderson, FL", "distance_miles": 12.0, "services_available": ["Full City Services", "Hospital", "Walmart", "Gas Stations", "Hardware", "Gyms"]}],
    "seasonal_weather_effects": {"spring": "Lush green pine spring (70-80°F).", "summer": "Hot humid summer (90-95°F) with lake breeze.", "fall": "Crisp pleasant autumn days.", "winter": "Mild winter (55-68°F)."},
    "dangers_and_hazards": ["American Alligators", "Summer Mosquitoes"],
    "acoustic_environment": {"quietness_rating": "Pine Flatwoods Lake Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Ocean Pond wave lap", "Pine wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Slash Pine", "Longleaf Pine", "Bald Cypress", "Saw Palmetto"], "common_animals": ["American Alligator", "Florida Black Bear", "Sandhill Crane", "Large-mouth Bass"]},
    "human_demographics_and_culture": "Timucua / Seminole ancestral lands and Civil War Olustee battlefield heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Site of the 1864 Battle of Olustee, the largest Civil War battle fought in Florida.", "energetic_and_spiritual_features": "Flat pine flatwoods surrounding 2,000-acre natural circular Ocean Pond lake."},
    "nearby_hiking_trails": [{"trail_name": "Florida National Scenic Trail (Olustee Section)", "length_miles": 5.0, "difficulty": "Easy", "features": "Ocean Pond shoreline, cypress boardwalks, longleaf pine flatwoods"}],
    "public_reviews_summary": "Super easy I-10 basecamp near Lake City with 2,000-acre Ocean Pond views and blazing 5G cell service.",
    "other_data": "12 miles from Lake City I-10 junction.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "florida-008",
    "name": "Alexander Springs Dispersed Area - Ocala NF",
    "state": "Florida",
    "county": "Lake",
    "coordinates": {"latitude": 29.0812, "longitude": -81.5812, "elevation_ft": 40.0},
    "management_agency": {"name": "U.S. Forest Service - Seminole Ranger District", "type": "Federal", "phone": "(352) 669-3151", "website": "https://www.fs.usda.gov/florida"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside springs fee area)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along FS Road 18 outside developed spring loop. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6 inches deep 200 ft from Alexander Springs Creek. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy. Bear safety mandatory."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared sand rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded sand forest road", "road_conditions": "Graded sand Forest Service road; smooth when dry.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low - flat scrub pine terrain", "distance_from_tower_corridor_miles": 4.5, "cellular_internet_dependable": True},
    "amenities": ["72°F Crystal Freshwater Spring Proximity", "Snorkeling & Kayaking", "Sand Pine Scrub Shade", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 7, "distance_to_gym_score": 6, "terrain_score": 9, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Umatilla / Astor, FL", "distance_miles": 10.0, "services_available": ["Grocery Store", "Gas Stations", "Hardware", "Kayak Outfitters", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush subtropical spring (75-85°F).", "summer": "Warm humid summer (90-95°F) with 72°F spring swimming.", "fall": "Crisp pleasant autumn days.", "winter": "Mild winter (60-72°F)."},
    "dangers_and_hazards": ["American Alligators in Spring Creek", "Florida Black Bear Area"],
    "acoustic_environment": {"quietness_rating": "Subtropical Pine Scrub Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Wind through sand pines", "Cicada calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Sand Pine", "Scrub Oak", "Cabbage Palm", "Spanish Moss"], "common_animals": ["West Indian Manatee", "American Alligator", "Florida Black Bear", "Scrub Jay"]},
    "human_demographics_and_culture": "Timucua ancestral lands and Ocala spring snorkeling & Manatee conservation culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "First-magnitude freshwater spring pumping 70 million gallons of 72°F crystal water daily into Alexander Run.", "energetic_and_spiritual_features": "Pristine turquoise freshwater spring basin surrounded by subtropical cabbage palms."},
    "nearby_hiking_trails": [{"trail_name": "Timucuan Heritage Trail", "length_miles": 1.0, "difficulty": "Easy", "features": "Alexander Springs creek boardwalk, cabbage palm hammocks, spring views"}],
    "public_reviews_summary": "Incredible basecamp near 72°F crystal clear Alexander Springs with manatee watching and blazing 5G cell service.",
    "other_data": "72°F water year-round.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "florida-009",
    "name": "Fort Gadsden Dispersed Area - Apalachicola NF",
    "state": "Florida",
    "county": "Franklin",
    "coordinates": {"latitude": 29.9812, "longitude": -85.0123, "elevation_ft": 40.0},
    "management_agency": {"name": "U.S. Forest Service - National Forests in Florida", "type": "Federal", "phone": "(850) 643-2282", "website": "https://www.fs.usda.gov/florida"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside historic site lot)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along FS Road 129 near Apalachicola River. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6 inches deep 200 ft from Apalachicola River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared sand rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road off HWY 65; smooth when dry.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low along Apalachicola river corridor", "distance_from_tower_corridor_miles": 7.5, "cellular_internet_dependable": True},
    "amenities": ["Apalachicola River Overlook Views", "Fort Gadsden Historic Site Nearby", "River Boating & Fishing", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Eastpoint / Apalachicola, FL", "distance_miles": 18.0, "services_available": ["Gulf Seafood Market", "Grocery Store", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush coastal river spring (70-80°F).", "summer": "Warm humid summer (88-94°F) with river breezes.", "fall": "Crisp pleasant autumn days.", "winter": "Mild winter (55-68°F)."},
    "dangers_and_hazards": ["American Alligators", "Summer Mosquitoes"],
    "acoustic_environment": {"quietness_rating": "Apalachicola River Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Apalachicola River water flow", "Cypress wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Bald Cypress", "Ogeechee Tupelo", "Longleaf Pine", "Spanish Moss"], "common_animals": ["American Alligator", "Bald Eagle", "River Otter", "Striped Bass", "Ogeechee Tupelo Honeybee"]},
    "human_demographics_and_culture": "Mascogo / Seminole ancestral lands and Apalachicola River oyster & tupelo honey culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Historic 1816 'Prospect Bluff' / Fort Gadsden site along the Apalachicola River.", "energetic_and_spiritual_features": "Vast tea-colored Apalachicola river flowing through moss-draped ancient cypress swamps."},
    "nearby_hiking_trails": [{"trail_name": "Fort Gadsden Historic Nature Trail", "length_miles": 1.5, "difficulty": "Easy", "features": "Apalachicola River overlooks, historic earthwork ruins, cypress bluff"}],
    "public_reviews_summary": "Peaceful river side forest basecamp near the Gulf Coast with rich history and solid cell service.",
    "other_data": "Home to world-famous Ogeechee Tupelo Honey.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "florida-010",
    "name": "Eglin Public Dispersed Area - Eglin Reservation",
    "state": "Florida",
    "county": "Okaloosa",
    "coordinates": {"latitude": 30.5123, "longitude": -86.5812, "elevation_ft": 180.0},
    "management_agency": {"name": "U.S. Air Force - Eglin Natural Resources Office", "type": "Federal", "phone": "(850) 882-4164", "website": "https://eglin.isportsman.net"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive public dispersed camping with $20 annual Eglin outdoor recreation permit)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on designated public recreation tracks across 460,000 acres of open reservation lands. Check range closures on iSportsman."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6 inches deep 200 ft from streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared sand rings. Extinguish cold.", "seasonal_fire_bans": "Subject to Eglin fire bans."},
    "access_and_road_conditions": {"road_type": "Graded sand and gravel reservation road", "road_conditions": "Graded sand reservation roads; smooth when dry.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars on main designated tracks.", "scores": {"road_grade": 1, "road_terrain_difficulty": 2, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low - flat Panhandle pine flatwoods", "distance_from_tower_corridor_miles": 4.5, "cellular_internet_dependable": True},
    "amenities": ["Longleaf Pine Sandhills Landscape", "Clear Creek Swimming Holes", "Emerald Coast Gulf Beaches Nearby", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 8, "distance_to_gym_score": 7, "terrain_score": 8, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Crestview / Fort Walton Beach, FL", "distance_miles": 10.0, "services_available": ["Full Urban Services", "Hospital", "Walmart", "Target", "Gas Stations", "Gyms"]}],
    "seasonal_weather_effects": {"spring": "Lush Panhandle spring (70-80°F).", "summer": "Warm humid summer (88-94°F) with Gulf beach proximity.", "fall": "Crisp pleasant autumn days.", "winter": "Mild winter (55-68°F)."},
    "dangers_and_hazards": ["Military Range Boundary Closure Enforcement", "Venomous Snakes"],
    "acoustic_environment": {"quietness_rating": "Pine Sandhills Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Wind through longleaf pines", "Occasional distant aircraft hum"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Longleaf Pine", "Turkey Oak", "Wiregrass", "Saw Palmetto"], "common_animals": ["Red-cockaded Woodpecker", "Gopher Tortoise", "White-tailed Deer", "Florida Black Bear"]},
    "human_demographics_and_culture": "Muscogee ancestral lands and Emerald Coast military aviation & beach culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Largest contiguous longleaf pine sandhills forest remaining on Earth, protected across 460,000 acres of public Eglin lands.", "energetic_and_spiritual_features": "Vast open longleaf pine sandhills 20 minutes from the turquoise Gulf of Mexico."},
    "nearby_hiking_trails": [{"trail_name": "Florida Trail (Eglin Reservation Section)", "length_miles": 6.0, "difficulty": "Easy to Moderate", "features": "Longleaf pine sandhills, clear stream crossings, pitcher plant bogs"}],
    "public_reviews_summary": "Vast 460,000-acre pine forest basecamp near Destin and Fort Walton Beach with blazing 5G cell service.",
    "other_data": "Eglin outdoor permit ($20/year) required online.",
    "last_updated": "2026-09-12"
  }
])
save_state(fl, fl_path)
print("Updated Florida -> 10 sites.")

print("Batch P9 execution complete!")
