import json
import os

STATES_DIR = "/home/volmarr/.gemini/antigravity/scratch/Camping_Nomad_Life/states"

def load_state(name):
    path = os.path.join(STATES_DIR, f"{name}.json")
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f), path

def save_state(data, path):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")

# 1. North Dakota (+5 sites -> 10 total)
nd, nd_path = load_state("north_dakota")
nd.extend([
  {
    "id": "north_dakota-006",
    "name": "Magpie Road Dispersed Area - Little Missouri National Grassland",
    "state": "North Dakota",
    "county": "McKenzie",
    "coordinates": {"latitude": 47.4123, "longitude": -103.5412, "elevation_ft": 2400.0},
    "management_agency": {"name": "U.S. Forest Service - Little Missouri National Grassland", "type": "Federal", "phone": "(701) 227-7800", "website": "https://www.fs.usda.gov/d Dakota"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive dispersed grassland camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed camping allowed on open public grassland pullouts along Magpie Road (FS 710). Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from dry wash channels. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Bring firewood; no wood gathering in badlands.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans in dry summer."},
    "access_and_road_conditions": {"road_type": "Graded gravel grassland road", "road_conditions": "Graded gravel access road; scoria surface provides decent traction, but clay ruts when wet.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars when dry.", "scores": {"road_grade": 3, "road_terrain_difficulty": 3, "supply_run_pain": 5}},
    "nomad_connectivity_rating": {"overall_rating": "Great on Ridge (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "3 bars 4G LTE", "tmobile_reliability": "2-3 bars 4G LTE", "terrain_obstruction_risk": "Low to Moderate on badland ridge top", "distance_from_tower_corridor_miles": 12.0, "cellular_internet_dependable": True},
    "amenities": ["Little Missouri Badlands Panorama Views", "Maah Daah Hey Trail Access Nearby", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 5, "distance_to_library_score": 5, "distance_to_gym_score": 3, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Belfield, ND", "distance_miles": 22.0, "services_available": ["Gas Station", "Small Grocery", "Diner", "Hardware"]}, {"town_name": "Dickinson, ND", "distance_miles": 42.0, "services_available": ["Full Urban Services", "Hospital", "Walmart", "Gyms"]}],
    "seasonal_weather_effects": {"spring": "Lush green badlands spring (55-68°F).", "summer": "Warm summer (82-90°F) with cool evening breeze.", "fall": "Golden autumn badland colors.", "winter": "Cold windy winter (15-32°F)."},
    "dangers_and_hazards": ["Clay Mud when Wet", "High Prairie Winds", "Severe Summer Thunderstorms"],
    "acoustic_environment": {"quietness_rating": "Badland Prairie Silence (Quietness Score: 9/10)", "common_human_made_sounds": ["Prairie wind through badland coulees", "Coyote calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Rocky Mountain Juniper", "Western Wheatgrass", "Prickly Pear", "Chokecherry"], "common_animals": ["Mule Deer", "Pronghorn Antelope", "Bison", "Sharp-tailed Grouse", "Golden Eagle"]},
    "human_demographics_and_culture": "Mandan, Hidatsa, and Arikara ancestral lands and Theodore Roosevelt badland conservation heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Traditional hunting and vision quest grounds of the Mandan and Hidatsa nations.", "energetic_and_spiritual_features": "Dramatic scoria red rock capped badland formations stretching across the Little Missouri river basin."},
    "nearby_hiking_trails": [{"trail_name": "Maah Daah Hey Trail (Magpie Section)", "length_miles": 5.0, "difficulty": "Moderate", "features": "Badland ridges, scoria rock outcrops, prairie coulees"}],
    "public_reviews_summary": "Incredible badland views and Maah Daah Hey trail access with rock-solid cell service on ridge pullouts.",
    "other_data": "Carry fresh drinking water.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "north_dakota-007",
    "name": "Burning Coal Vein Dispersed Area - Little Missouri Grassland",
    "state": "North Dakota",
    "county": "Slope",
    "coordinates": {"latitude": 46.6123, "longitude": -103.4512, "elevation_ft": 2500.0},
    "management_agency": {"name": "U.S. Forest Service - Medora Ranger District", "type": "Federal", "phone": "(701) 227-7800", "website": "https://www.fs.usda.gov/d Dakota"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside campground loop)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free primitive dispersed camping on surrounding public grassland pullouts along FS Road 757. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from drainages. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded scoria gravel road; smooth when dry.", "vehicle_recommendation": "Accessible by standard low-clearance 2WD passenger cars.", "scores": {"road_grade": 2, "road_terrain_difficulty": 3, "supply_run_pain": 5}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "3 bars 4G LTE", "tmobile_reliability": "2-3 bars 4G LTE", "terrain_obstruction_risk": "Low - open prairie badlands", "distance_from_tower_corridor_miles": 14.0, "cellular_internet_dependable": True},
    "amenities": ["Columnar Cedar Grove", "Subterranean Coal Vein Fire Geology", "Maah Daah Hey Southern Trailhead", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 5, "distance_to_library_score": 5, "distance_to_gym_score": 3, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Amidon, ND", "distance_miles": 15.0, "services_available": ["Gas Station", "Post Office", "Small Store"]}, {"town_name": "Dickinson, ND", "distance_miles": 52.0, "services_available": ["Full Urban Services", "Hospital", "Walmart", "Hardware"]}],
    "seasonal_weather_effects": {"spring": "Lush spring badlands (55-68°F).", "summer": "Warm summer (82-90°F) with cool evening breeze.", "fall": "Crisp dry autumn days.", "winter": "Cold windy winter (15-30°F)."},
    "dangers_and_hazards": ["Clay Mud when Wet", "Subterranean Coal Fumes near Vein Vent", "High Prairie Winds"],
    "acoustic_environment": {"quietness_rating": "Columnar Cedar Silence (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind through columnar junipers", "Coyote calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Columnar Rocky Mountain Juniper", "Creeping Juniper", "Big Sagebrush"], "common_animals": ["Mule Deer", "Pronghorn Antelope", "Sharp-tailed Grouse", "Porcupine"]},
    "human_demographics_and_culture": "Lakota tradition and Slope County pioneer badland ranching culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Unique natural phenomenon where an underground lignite coal vein burned for decades, baking surrounding clay into red scoria rock.", "energetic_and_spiritual_features": "Ancient columnar juniper grove growing in red scoria baked soil."},
    "nearby_hiking_trails": [{"trail_name": "Columnar Juniper Nature Trail", "length_miles": 2.0, "difficulty": "Easy", "features": "Columnar juniper trees, red scoria rock outcrops, badland vistas"}],
    "public_reviews_summary": "Unique geological landmark with columnar junipers, southern Maah Daah Hey access, and good cell service.",
    "other_data": "Southern terminus of the 144-mile Maah Daah Hey Trail.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "north_dakota-008",
    "name": "Sheyenne Grassland Dispersed Area - Sheyenne National Grassland",
    "state": "North Dakota",
    "county": "Ransom",
    "coordinates": {"latitude": 46.4812, "longitude": -97.2812, "elevation_ft": 1050.0},
    "management_agency": {"name": "U.S. Forest Service - Sheyenne National Grassland", "type": "Federal", "phone": "(701) 683-4342", "website": "https://www.fs.usda.gov/d Dakota"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed camping allowed on open grassland pullouts along Forest Service roads. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from wetlands and Sheyenne River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded sandy gravel forest road", "road_conditions": "Graded gravel and sandy dirt forest roads.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars on main gravel roads.", "scores": {"road_grade": 1, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low - open tallgrass prairie oak savanna", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["Tallgrass Prairie & Oak Savanna", "North Country Trail Access", "Wildflower Blooms", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 5, "terrain_score": 8, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Lisbon, ND", "distance_miles": 14.0, "services_available": ["Groceries", "Gas Stations", "Hardware Store", "Diner"]}, {"town_name": "Fargo, ND", "distance_miles": 45.0, "services_available": ["Full Urban Services", "Airport", "Walmart", "Hospital"]}],
    "seasonal_weather_effects": {"spring": "Lush green prairie spring (58-70°F).", "summer": "Warm prairie summer (78-88°F) with lush wildflowers.", "fall": "Golden oak savanna autumn days.", "winter": "Cold winter (12-28°F) with snow."},
    "dangers_and_hazards": ["Ticks in Spring Tallgrass", "High Summer Mosquitoes near Swales"],
    "acoustic_environment": {"quietness_rating": "Tallgrass Prairie Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind rustling oak leaves", "Bobolink songs"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Bur Oak", "Big Bluestem", "Western Prairie Fringed Orchid", "Switchgrass"], "common_animals": ["Greater Prairie-Chicken", "White-tailed Deer", "Red Fox", "Wild Turkey"]},
    "human_demographics_and_culture": "Sisseton Wahpeton Oyate ancestral lands and Red River Valley agricultural heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "One of the last remaining native tallgrass prairie sandhills ecosystems in North America.", "energetic_and_spiritual_features": "Oak savanna savanna groves surrounded by towering native tallgrass prairie."},
    "nearby_hiking_trails": [{"trail_name": "North Country National Scenic Trail (Sheyenne Section)", "length_miles": 6.0, "difficulty": "Easy", "features": "Tallgrass prairie, bur oak savanna, sand dunes, rare wildflowers"}],
    "public_reviews_summary": "Beautiful bur oak savanna and tallgrass prairie hiking with fast 5G cell service close to Fargo.",
    "other_data": "Home to the endangered Western Prairie Fringed Orchid.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "north_dakota-009",
    "name": "Pembina Gorge Dispersed Primitive Area - State Rec Area",
    "state": "North Dakota",
    "county": "Cavalier",
    "coordinates": {"latitude": 48.9123, "longitude": -97.8412, "elevation_ft": 1150.0},
    "management_agency": {"name": "North Dakota Parks and Recreation Department", "type": "State", "phone": "(701) 549-2444", "website": "https://www.parkrec.nd.gov"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive state dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Primitive dispersed camping allowed on designated public state land pullouts outside developed day-use areas. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Pembina River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to state fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel access road", "road_conditions": "Graded gravel access roads off ND-32; smooth when dry.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars.", "scores": {"road_grade": 2, "road_terrain_difficulty": 3, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "3 bars 4G LTE", "tmobile_reliability": "2-3 bars 4G LTE", "terrain_obstruction_risk": "Low to Moderate on gorge rim pullouts", "distance_from_tower_corridor_miles": 7.5, "cellular_internet_dependable": True},
    "amenities": ["Pembina River Gorge Overlook Views", "Lush Deciduous Forest Canopy", "Kayaking & Canoeing", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Walhalla, ND", "distance_miles": 8.0, "services_available": ["Grocery Store", "Gas Station", "Hardware", "Diner"]}, {"town_name": "Cavalier, ND", "distance_miles": 22.0, "services_available": ["Groceries", "Hospital", "Gas Stations", "Pharmacy"]}],
    "seasonal_weather_effects": {"spring": "Lush green forest spring (55-68°F).", "summer": "Warm pleasant summer (78-85°F) with rich forest shade.", "fall": "Spectacular red and yellow autumn canopy.", "winter": "Cold snow sports winter (10-25°F)."},
    "dangers_and_hazards": ["Steep River Bank Drops", "Ticks in Spring Brush"],
    "acoustic_environment": {"quietness_rating": "Deciduous Gorge Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Pembina River flow", "Songbird calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Bur Oak", "Paper Birch", "Quaking Aspen", "Beaked Hazelnut"], "common_animals": ["Elk", "Moose", "Ruffed Grouse", "Beaver", "River Otter"]},
    "human_demographics_and_culture": "Pembina Chippewa / Métis ancestral lands and Red River fur trade post heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Historic 1790s Alexander Henry fur trading post and Métis bison hunting trail heritage.", "energetic_and_spiritual_features": "Deepest unglaciated river gorge valley in North Dakota with lush hardwood forest canopy."},
    "nearby_hiking_trails": [{"trail_name": "Pembina Gorge Rim Trail", "length_miles": 4.2, "difficulty": "Moderate", "features": "River gorge panoramas, bur oak canopy, autumn foliage"}],
    "public_reviews_summary": "Largest continuous native forest in North Dakota with stunning river gorge views and strong cell service.",
    "other_data": "Great canoeing river in late spring.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "north_dakota-010",
    "name": "Lake Oahe Dispersed Area - Lake Oahe WMA",
    "state": "North Dakota",
    "county": "Emmons",
    "coordinates": {"latitude": 46.2812, "longitude": -100.5812, "elevation_ft": 1620.0},
    "management_agency": {"name": "North Dakota Game and Fish Department / USACE", "type": "State", "phone": "(701) 328-6300", "website": "https://gf.nd.gov"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive state WMA dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed camping allowed on open public WMA pullouts along Lake Oahe shoreline. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from high water line. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to state fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel WMA access road", "road_conditions": "Graded gravel access roads off ND-1804; smooth when dry.", "vehicle_recommendation": "Accessible by standard low-clearance 2WD passenger cars.", "scores": {"road_grade": 1, "road_terrain_difficulty": 2, "supply_run_pain": 4}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "4 bars 4G LTE", "att_reliability": "3-4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low along open reservoir shoreline", "distance_from_tower_corridor_miles": 6.5, "cellular_internet_dependable": True},
    "amenities": ["Missouri River Reservoir Views", "Walleye & Bass Fishing", "Boat Ramp Access Nearby", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 8, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Linton, ND", "distance_miles": 16.0, "services_available": ["Grocery Store", "Gas Station", "Hardware", "Diner"]}, {"town_name": "Bismarck, ND", "distance_miles": 42.0, "services_available": ["Full Urban Services", "Airport", "Walmart", "Hospital"]}],
    "seasonal_weather_effects": {"spring": "Breezy spring (55-68°F).", "summer": "Warm sunny summer (80-88°F) with water breezes.", "fall": "Crisp dry autumn fishing days.", "winter": "Cold freezing winter (15-30°F) with ice fishing."},
    "dangers_and_hazards": ["High Reservoir Winds", "High Summer Sun Exposure"],
    "acoustic_environment": {"quietness_rating": "Reservoir Water Silence (Quietness Score: 9/10)", "common_human_made_sounds": ["Gentle reservoir water lap", "Pelican calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Cottonwood", "Willow", "Western Wheatgrass"], "common_animals": ["Walleye", "White Pelican", "Bald Eagle", "Mule Deer", "Pheasant"]},
    "human_demographics_and_culture": "Standing Rock Sioux ancestral lands and Missouri River water heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Lewis & Clark 1804 expedition camp along the Missouri River route.", "energetic_and_spiritual_features": "Vast blue reservoir water contrasting against rolling prairie bluffs."},
    "nearby_hiking_trails": [{"trail_name": "Lake Oahe Shoreline Trail", "length_miles": 3.0, "difficulty": "Easy", "features": "Reservoir shore walking, pelican watching, prairie bluff views"}],
    "public_reviews_summary": "Uncrowded lake side camping with world-class walleye fishing and rock-solid cell service.",
    "other_data": "ND 1804 scenic byway access route.",
    "last_updated": "2026-09-12"
  }
])
save_state(nd, nd_path)
print("Updated North Dakota -> 10 sites.")

# 2. Texas (+5 sites -> 10 total)
tx, tx_path = load_state("texas")
tx.extend([
  {
    "id": "texas-006",
    "name": "Davy Crockett Dispersed Area - Davy Crockett National Forest",
    "state": "Texas",
    "county": "Houston",
    "coordinates": {"latitude": 31.3123, "longitude": -95.1234, "elevation_ft": 320.0},
    "management_agency": {"name": "U.S. Forest Service - National Forests in Texas", "type": "Federal", "phone": "(936) 544-2046", "website": "https://www.fs.usda.gov/texas"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside designated fee areas)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed camping allowed on general national forest lands along Forest Service roads outside deer hunting season. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to county burn bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; dirt turnouts smooth when dry.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low to Moderate under pine forest canopy", "distance_from_tower_corridor_miles": 6.5, "cellular_internet_dependable": True},
    "amenities": ["Loblolly Pine Canopy", "4C National Recreation Trail Access", "Piney Woods Solitude", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 6, "distance_to_gym_score": 5, "terrain_score": 8, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Crockett, TX", "distance_miles": 16.0, "services_available": ["Groceries", "Hospital", "Gas Stations", "Hardware"]}, {"town_name": "Lufkin, TX", "distance_miles": 34.0, "services_available": ["Full City Services", "Walmart", "Target", "Gyms"]}],
    "seasonal_weather_effects": {"spring": "Lush green pine spring (68-78°F).", "summer": "Hot humid summer (90-96°F) with shade.", "fall": "Crisp pleasant autumn days.", "winter": "Mild winter (52-64°F)."},
    "dangers_and_hazards": ["Feral Hogs", "Copperhead & Cottonmouth Snakes", "Ticks in Spring"],
    "acoustic_environment": {"quietness_rating": "Piney Woods Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind through tall loblolly pines", "Frog chorus"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Loblolly Pine", "Shortleaf Pine", "Post Oak", "American Holly"], "common_animals": ["White-tailed Deer", "Feral Hog", "Red-cockaded Woodpecker", "Gray Fox"]},
    "human_demographics_and_culture": "Caddo indigenous heritage and East Texas Piney Woods timber history.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Caddo traditional mound builder ancestral territory.", "energetic_and_spiritual_features": "Tall whispering loblolly pines filtering warm East Texas sunlight."},
    "nearby_hiking_trails": [{"trail_name": "4C National Recreation Trail (Davy Crockett Section)", "length_miles": 5.0, "difficulty": "Easy to Moderate", "features": "Loblolly pine forest, hardwood bottoms, historic tramway trails"}],
    "public_reviews_summary": "Peaceful East Texas pine forest camping with reliable cell service and great trail access.",
    "other_data": "Check hunting season dates before camping.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "texas-007",
    "name": "Sabine Dispersed Area - Sabine National Forest",
    "state": "Texas",
    "county": "Sabine",
    "coordinates": {"latitude": 31.4812, "longitude": -93.8412, "elevation_ft": 280.0},
    "management_agency": {"name": "U.S. Forest Service - National Forests in Texas", "type": "Federal", "phone": "(409) 625-1940", "website": "https://www.fs.usda.gov/texas"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along Toledo Bend Reservoir corridor outside fee areas. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Toledo Bend high water line. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to county burn bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel forest roads; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars.", "scores": {"road_grade": 1, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low along reservoir shoreline", "distance_from_tower_corridor_miles": 7.0, "cellular_internet_dependable": True},
    "amenities": ["Toledo Bend Reservoir Shoreline Views", "Bass Fishing Proximity", "Pine Forest Shade", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Hemphill, TX", "distance_miles": 14.0, "services_available": ["Grocery Store", "Gas Station", "Hardware", "Diner"]}, {"town_name": "Nacogdoches, TX", "distance_miles": 48.0, "services_available": ["Full Urban Services", "Hospital", "Walmart", "University"]}],
    "seasonal_weather_effects": {"spring": "Lush green forest spring (68-78°F).", "summer": "Warm humid summer (90-95°F) with lake breezes.", "fall": "Crisp autumn fishing weather.", "winter": "Mild winter (50-62°F)."},
    "dangers_and_hazards": ["Alligators in Lake Arms", "Venomous Snakes", "Humidity"],
    "acoustic_environment": {"quietness_rating": "Reservoir Pine Forest Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Gentle reservoir water lap", "Pine wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Loblolly Pine", "Shortleaf Pine", "Southern Red Oak", "Dogwood"], "common_animals": ["American Alligator", "White-tailed Deer", "Bald Eagle", "Large-mouth Bass"]},
    "human_demographics_and_culture": "Hasinai Caddo heritage and Toledo Bend bass fishing tournament culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Historic El Camino Real de los Tejas Spanish trade corridor passed near here.", "energetic_and_spiritual_features": "Massive freshwater reservoir shoreline framed by East Texas pine forests."},
    "nearby_hiking_trails": [{"trail_name": "Between the Lakes Trail", "length_miles": 4.0, "difficulty": "Easy to Moderate", "features": "Toledo Bend lake views, pine canopy, dogwood blooms"}],
    "public_reviews_summary": "Super peaceful lake side pine forest camping with world-class bass fishing and reliable cell service.",
    "other_data": "Watch for alligators near swampy coves.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "texas-008",
    "name": "Angelina Dispersed Area - Angelina National Forest",
    "state": "Texas",
    "county": "Jasper",
    "coordinates": {"latitude": 31.1412, "longitude": -94.2812, "elevation_ft": 250.0},
    "management_agency": {"name": "U.S. Forest Service - National Forests in Texas", "type": "Federal", "phone": "(936) 897-1068", "website": "https://www.fs.usda.gov/texas"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along Sam Rayburn Reservoir corridor. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Sam Rayburn high water line. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to county burn bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel forest roads; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars.", "scores": {"road_grade": 1, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low along Sam Rayburn reservoir rim", "distance_from_tower_corridor_miles": 6.8, "cellular_internet_dependable": True},
    "amenities": ["Sam Rayburn Reservoir Shoreline", "Piney Woods Forest Shade", "Bass Fishing", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 6, "distance_to_gym_score": 5, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Jasper, TX", "distance_miles": 16.0, "services_available": ["Groceries", "Hospital", "Gas Stations", "Hardware"]}, {"town_name": "Lufkin, TX", "distance_miles": 38.0, "services_available": ["Full Urban Services", "Walmart", "Target", "Gyms"]}],
    "seasonal_weather_effects": {"spring": "Lush spring forest (68-78°F).", "summer": "Warm humid summer (90-95°F) with lake breeze.", "fall": "Crisp autumn fishing days.", "winter": "Mild winter (52-64°F)."},
    "dangers_and_hazards": ["Alligators in Shallow Coves", "Venomous Snakes"],
    "acoustic_environment": {"quietness_rating": "Reservoir Shoreline Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Lake wave lap", "Pine wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Loblolly Pine", "Longleaf Pine", "Sweetgum", "Magnolia"], "common_animals": ["American Alligator", "White-tailed Deer", "Red-cockaded Woodpecker", "Bass"]},
    "human_demographics_and_culture": "Atakapa-Ishak ancestral lands and Sam Rayburn fishing culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Named after 17th-century Hasinai Caddo woman who assisted early Spanish explorers.", "energetic_and_spiritual_features": "Pristine pine savanna framing the massive Sam Rayburn lake surface."},
    "nearby_hiking_trails": [{"trail_name": "Boykin Springs Trail", "length_miles": 3.2, "difficulty": "Easy to Moderate", "features": "Spring-fed creek, longleaf pine savanna, rock outcrops"}],
    "public_reviews_summary": "Gorgeous pine-covered reservoir camping with great bass fishing and strong cell service.",
    "other_data": "Boykin Springs day-use area nearby.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "texas-009",
    "name": "Rita Blanca Dispersed Area - Rita Blanca National Grassland",
    "state": "Texas",
    "county": "Dallam",
    "coordinates": {"latitude": 36.3123, "longitude": -102.6412, "elevation_ft": 4200.0},
    "management_agency": {"name": "U.S. Forest Service - Cibola NF & National Grasslands", "type": "Federal", "phone": "(806) 362-4254", "website": "https://www.fs.usda.gov/cibola"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive dispersed grassland camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free primitive dispersed camping on open public grassland pullouts along USFS roads. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from dry playa basins. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Bring firewood; no wood gathering on prairie.", "safety_requirements": "Campfires strictly in metal fire pans. Extinguish cold.", "seasonal_fire_bans": "Strict USFS stage fire bans in dry spring/summer."},
    "access_and_road_conditions": {"road_type": "Graded dirt and gravel grassland road", "road_conditions": "Graded gravel/dirt access road; ruts when wet.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars when dry.", "scores": {"road_grade": 2, "road_terrain_difficulty": 3, "supply_run_pain": 5}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "4 bars 4G LTE", "att_reliability": "3-4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low - open High Plains prairie", "distance_from_tower_corridor_miles": 8.5, "cellular_internet_dependable": True},
    "amenities": ["High Plains Horizon Views", "Pronghorn Watching", "Stargazing", "Peaceful Solitude"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 8, "quietness_score": 10},
    "nearest_supply_towns": [{"town_name": "Dalhart, TX", "distance_miles": 18.0, "services_available": ["Grocery Store", "Hospital", "Gas Stations", "Hardware Store"]}],
    "seasonal_weather_effects": {"spring": "High winds spring (60-72°F).", "summer": "Warm High Plains summer (88-95°F) with cool nights.", "fall": "Crisp pleasant autumn days.", "winter": "Cold windy winter (25-42°F)."},
    "dangers_and_hazards": ["High Plains Prairie Winds", "Severe Thunderstorms", "Dust Storms"],
    "acoustic_environment": {"quietness_rating": "High Plains Prairie Silence (Quietness Score: 10/10)", "common_human_made_sounds": ["Prairie wind", "Horned lark songs"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Buffalograss", "Blue Grama", "Yucca", "Prickly Pear"], "common_animals": ["Pronghorn Antelope", "Prairie Dog", "Coyote", "Ferruginous Hawk"]},
    "human_demographics_and_culture": "Comanche traditional lands and Texas Panhandle Dust Bowl conservation history.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Comanche and Kiowa traditional High Plains bison hunting grounds.", "energetic_and_spiritual_features": "360-degree flat horizon in the Texas Panhandle High Plains."},
    "nearby_hiking_trails": [{"trail_name": "Rita Blanca Prairie Loop", "length_miles": 4.0, "difficulty": "Easy", "features": "Shortgrass prairie, pronghorn viewing, flat High Plains horizon"}],
    "public_reviews_summary": "Solitary High Plains prairie basecamp near Dalhart with steady 4G cell service.",
    "other_data": "High winds common year-round.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "texas-010",
    "name": "Four C Dispersed Area - Sam Houston National Forest",
    "state": "Texas",
    "county": "San Jacinto",
    "coordinates": {"latitude": 30.5812, "longitude": -95.1412, "elevation_ft": 210.0},
    "management_agency": {"name": "U.S. Forest Service - National Forests in Texas", "type": "Federal", "phone": "(936) 344-6205", "website": "https://www.fs.usda.gov/texas"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside deer hunting season)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free primitive dispersed camping on national forest pullouts along Lone Star Hiking Trail corridor. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to county burn bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; dirt turnouts smooth when dry.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low under pine forest canopy", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["Lone Star Hiking Trail Access", "Pine Forest Shade", "Close Proximity to Houston Metro", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 8, "distance_to_gym_score": 7, "terrain_score": 8, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "New Waverly, TX", "distance_miles": 10.0, "services_available": ["Gas Station", "Grocery Store", "Diner"]}, {"town_name": "Conroe / Houston, TX", "distance_miles": 22.0, "services_available": ["Major Metropolitan Services", "Hospitals", "REI"]}],
    "seasonal_weather_effects": {"spring": "Lush green pine spring (68-78°F).", "summer": "Warm humid summer (90-95°F) with shade.", "fall": "Crisp autumn hiking days.", "winter": "Mild winter (52-64°F)."},
    "dangers_and_hazards": ["Feral Hogs", "Venomous Snakes", "Ticks in Spring"],
    "acoustic_environment": {"quietness_rating": "Pine Forest Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Wind through loblolly pine canopy", "Occasional forest road pass"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Loblolly Pine", "Shortleaf Pine", "Sweetgum", "Southern Magnolia"], "common_animals": ["White-tailed Deer", "Feral Hog", "Red-cockaded Woodpecker", "Armadillo"]},
    "human_demographics_and_culture": "Akokisa indigenous ancestral lands and Houston outdoor escape culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Lone Star National Recreation Trail spans 128 miles through the heart of the Sam Houston Forest.", "energetic_and_spiritual_features": "Quiet loblolly pine canopy under an hour from Houston metro."},
    "nearby_hiking_trails": [{"trail_name": "Lone Star Hiking Trail (Section 4)", "length_miles": 5.5, "difficulty": "Easy to Moderate", "features": "Loblolly pine forest, creek bridges, magnolia bottomlands"}],
    "public_reviews_summary": "Top choice for nomads near Houston needing fast 5G cell service and peaceful pine forest camping.",
    "other_data": "Check hunting season regulations.",
    "last_updated": "2026-09-12"
  }
])
save_state(tx, tx_path)
print("Updated Texas -> 10 sites.")

# 3. Arkansas (+5 sites -> 10 total)
ar, ar_path = load_state("arkansas")
ar.extend([
  {
    "id": "arkansas-006",
    "name": "Richland Creek Dispersed Area - Ozark National Forest",
    "state": "Arkansas",
    "county": "Searcy",
    "coordinates": {"latitude": 35.8123, "longitude": -92.9412, "elevation_ft": 1400.0},
    "management_agency": {"name": "U.S. Forest Service - Ozark-St. Francis National Forests", "type": "Federal", "phone": "(870) 446-5122", "website": "https://www.fs.usda.gov/osfnf"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside developed loop)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed camping allowed along Forest Service roads outside developed wilderness area. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Richland Creek. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Gravel dirt mountain road", "road_conditions": "Winding gravel forest road with steep grades and washboard.", "vehicle_recommendation": "High clearance 2WD/4WD recommended.", "scores": {"road_grade": 5, "road_terrain_difficulty": 6, "supply_run_pain": 6}},
    "nomad_connectivity_rating": {"overall_rating": "Fair / Spotty (2.5/5 Stars)", "verizon_reliability": "2 bars 4G LTE (Ridge tops)", "att_reliability": "1-2 bars 4G LTE", "tmobile_reliability": "1 bar 4G LTE", "terrain_obstruction_risk": "High inside deep Ozark creek hollows", "distance_from_tower_corridor_miles": 18.0, "cellular_internet_dependable": False},
    "amenities": ["Richland Creek Waterfalls", "Ozark Mountain Hollow Views", "Wilderness Gateway", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 4, "distance_to_library_score": 4, "distance_to_gym_score": 2, "terrain_score": 10, "quietness_score": 10},
    "nearest_supply_towns": [{"town_name": "Jasper, AR", "distance_miles": 22.0, "services_available": ["Gas Station", "Grocery Store", "Hardware", "Diner"]}, {"town_name": "Harrison, AR", "distance_miles": 42.0, "services_available": ["Full City Services", "Hospital", "Walmart", "Gear Shops"]}],
    "seasonal_weather_effects": {"spring": "Lush spring waterfalls (60-72°F).", "summer": "Warm humid summer (85-92°F) with creek swimming.", "fall": "Spectacular Ozark autumn foliage.", "winter": "Cool winter (38-50°F)."},
    "dangers_and_hazards": ["Flash Floods in Narrow Hollows", "Venomous Snakes", "Steep Slippery Rock Slopes"],
    "acoustic_environment": {"quietness_rating": "Ozark Hollow Waterfall Quiet (Quietness Score: 10/10)", "common_human_made_sounds": ["Waterfalls and creek roar", "Songbird chorus"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Shortleaf Pine", "White Oak", "Sugar Maple", "Beech"], "common_animals": ["Black Bear", "White-tailed Deer", "Elk", "Wild Turkey", "Smallmouth Bass"]},
    "human_demographics_and_culture": "Osage ancestral lands and Ozark mountain pioneer heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Osage tradition reveres the pristine Ozark bluffs and spring-fed mountain creeks.", "energetic_and_spiritual_features": "Crystal clear Ozark mountain streams carving deep sandstone bluff hollows."},
    "nearby_hiking_trails": [{"trail_name": "Richland Falls & Twin Falls Trail", "length_miles": 5.5, "difficulty": "Strenuous", "features": "Cascading waterfalls, sandstone bluffs, turquoise creek pools"}],
    "public_reviews_summary": "World-class Ozark waterfall country; cell service is spotty in hollows so Starlink is recommended.",
    "other_data": "Best waterfall flows occur in spring.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "arkansas-007",
    "name": "Eagle Rock Dispersed Area - Ouachita National Forest",
    "state": "Arkansas",
    "county": "Montgomery",
    "coordinates": {"latitude": 34.3512, "longitude": -93.8123, "elevation_ft": 950.0},
    "management_agency": {"name": "U.S. Forest Service - Ouachita National Forest", "type": "Federal", "phone": "(479) 394-2382", "website": "https://www.fs.usda.gov/ouachita"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside developed recreation area)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed along Forest Service pullouts outside Albert Pike day-use area. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Little Missouri River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 2, "road_terrain_difficulty": 3, "supply_run_pain": 4}},
    "nomad_connectivity_rating": {"overall_rating": "Great on Ridge (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "3 bars 4G LTE", "tmobile_reliability": "2-3 bars 4G LTE", "terrain_obstruction_risk": "Low to Moderate on ridge pullouts", "distance_from_tower_corridor_miles": 8.0, "cellular_internet_dependable": True},
    "amenities": ["Little Missouri River Swimming", "Eagle Rock Loop Trail Access", "Shortleaf Pine Shade", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Glenwood, AR", "distance_miles": 18.0, "services_available": ["Grocery Store", "Gas Stations", "Hardware", "Diner"]}, {"town_name": "Hot Springs, AR", "distance_miles": 45.0, "services_available": ["Full City Services", "Hospital", "Walmart", "Thermal Baths"]}],
    "seasonal_weather_effects": {"spring": "Lush spring green (62-74°F).", "summer": "Warm summer (85-92°F) with river swimming.", "fall": "Crisp autumn foliage.", "winter": "Cool winter (40-52°F)."},
    "dangers_and_hazards": ["Flash Floods in Little Missouri River", "Copperhead Snakes"],
    "acoustic_environment": {"quietness_rating": "Ouachita Pine River Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["River water flow", "Pine needle wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Shortleaf Pine", "Loblolly Pine", "White Oak", "Dogwood"], "common_animals": ["White-tailed Deer", "Black Bear", "Wild Turkey", "Smallmouth Bass"]},
    "human_demographics_and_culture": "Caddo indigenous heritage and Ouachita mountain lumber history.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Caddo traditional territory; Ouachita mountains feature East-West mountain ridge alignments.", "energetic_and_spiritual_features": "Crystal clear Little Missouri river flowing through quartz-bearing Ouachita pine ridges."},
    "nearby_hiking_trails": [{"trail_name": "Eagle Rock Loop Trail (Winding Stairs Section)", "length_miles": 4.5, "difficulty": "Moderate", "features": "Winding stairs rapids, quartz rock outcrops, pine ridge vistas"}],
    "public_reviews_summary": "Incredible swimming holes along the Little Missouri River with reliable cell service on ridge pullouts.",
    "other_data": "Winding Stairs is a famous local scenic swimming spot.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "arkansas-008",
    "name": "Sylamore Dispersed Area - Sylamore Ranger District",
    "state": "Arkansas",
    "county": "Stone",
    "coordinates": {"latitude": 35.9812, "longitude": -92.1412, "elevation_ft": 850.0},
    "management_agency": {"name": "U.S. Forest Service - Ozark National Forest", "type": "Federal", "phone": "(870) 269-3228", "website": "https://www.fs.usda.gov/osfnf"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside Blanchard fee zone)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free dispersed primitive camping on national forest pullouts along Green Mountain road (FR 1102). Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Sylamore Creek. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; smooth dirt pullouts.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 2, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low to Moderate on ridge tops", "distance_from_tower_corridor_miles": 7.0, "cellular_internet_dependable": True},
    "amenities": ["Sylamore Creek Swimming", "Blanchard Springs Caverns Proximity", "Mountain Biking Trails", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 5, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Mountain View, AR", "distance_miles": 12.0, "services_available": ["Folk Music Capital", "Grocery Stores", "Hospital", "Gas", "Hardware"]}],
    "seasonal_weather_effects": {"spring": "Lush green Ozark spring (62-74°F).", "summer": "Warm summer (85-92°F) with cool cave air & swimming.", "fall": "Spectacular autumn foliage.", "winter": "Cool winter (38-50°F)."},
    "dangers_and_hazards": ["Flash Floods in Creek Hollows", "Ticks in Spring"],
    "acoustic_environment": {"quietness_rating": "Ozark Pine & Hardwood Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Creek flow", "Fiddle music echoes from Mountain View"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Shortleaf Pine", "White Oak", "Dogwood", "Redbud"], "common_animals": ["White-tailed Deer", "Gray Fox", "Black Bear", "Ozark Hellbender"]},
    "human_demographics_and_culture": "Osage ancestral lands and Mountain View traditional Ozark folk music culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Blanchard Springs subterranean cavern system carved through ancient limestone over millions of years.", "energetic_and_spiritual_features": "Crystal clear spring waters pouring from deep limestone caverns into Sylamore Creek."},
    "nearby_hiking_trails": [{"trail_name": "Syllamo Mountain Bike & Hike Trail", "length_miles": 7.5, "difficulty": "Moderate", "features": "Sandstone bluffs, pine forest singletrack, creek vistas"}],
    "public_reviews_summary": "Top choice near Mountain View for free pine forest camping, mountain biking, and Blanchard Caverns visits with strong cell service.",
    "other_data": "Visit Blanchard Springs Caverns nearby.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "arkansas-009",
    "name": "White Rock Mountain Dispersed Area - Ozark NF",
    "state": "Arkansas",
    "county": "Franklin",
    "coordinates": {"latitude": 35.6812, "longitude": -93.9412, "elevation_ft": 2250.0},
    "management_agency": {"name": "U.S. Forest Service - Boston Mountain District", "type": "Federal", "phone": "(479) 667-2191", "website": "https://www.fs.usda.gov/osfnf"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside peak rim fee area)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free dispersed primitive camping on national forest pullouts along FR 1003 approaching White Rock Mountain. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from mountain drainages. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel mountain forest road", "road_conditions": "Graded gravel Forest Service road climbing mountain ridge; smooth when dry.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 4, "road_terrain_difficulty": 3, "supply_run_pain": 4}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low on 2,250-foot mountain rim", "distance_from_tower_corridor_miles": 6.0, "cellular_internet_dependable": True},
    "amenities": ["2,250-Foot Ozark Mountain Panoramic Views", "Sunset Bluff Overlooks", "Ozark Highlands Trail Access", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Ozark, AR", "distance_miles": 20.0, "services_available": ["Grocery Store", "Hospital", "Gas Stations", "Hardware"]}, {"town_name": "Fayetteville, AR", "distance_miles": 42.0, "services_available": ["Full Urban Services", "University of Arkansas", "REI", "Walmart"]}],
    "seasonal_weather_effects": {"spring": "Lush mountain spring (60-72°F).", "summer": "Cool mountain breezes (78-85°F vs 95°F in valley).", "fall": "World-class Ozark autumn foliage.", "winter": "Cool winter (35-48°F) with light snow."},
    "dangers_and_hazards": ["Sheer Bluff Rim Drop-offs", "High Wind Gusts"],
    "acoustic_environment": {"quietness_rating": "Mountain Crest Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Mountain wind over bluffs", "Hawk screeches"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Shortleaf Pine", "White Oak", "Hickory", "Wild Azalea"], "common_animals": ["White-tailed Deer", "Black Bear", "Broad-winged Hawk", "Scarlet Tanager"]},
    "human_demographics_and_culture": "Osage ancestral lands and 1930s Civilian Conservation Corps (CCC) mountain build heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "CCC workers constructed stone bluffs and pavilions atop White Rock Mountain in 1935.", "energetic_and_spiritual_features": "Highest mountain peak in the region commanding 360-degree views across the Boston Mountains."},
    "nearby_hiking_trails": [{"trail_name": "White Rock Rim Trail", "length_miles": 2.0, "difficulty": "Easy to Moderate", "features": "Sandstone bluffs, 360-degree Ozark panoramas, CCC stone structures"}],
    "public_reviews_summary": "Unmatched 360-degree Ozark mountain sunset views with blazing 5G cell service on the mountain rim.",
    "other_data": "Ozark Highlands Trail connection point.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "arkansas-010",
    "name": "Caney Creek Wilderness Dispersed Area - Ouachita NF",
    "state": "Arkansas",
    "county": "Polk",
    "coordinates": {"latitude": 34.4123, "longitude": -94.2812, "elevation_ft": 1100.0},
    "management_agency": {"name": "U.S. Forest Service - Mena Ranger District", "type": "Federal", "phone": "(479) 394-2382", "website": "https://www.fs.usda.gov/ouachita"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along FR 38 outside wilderness boundary. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Caney Creek. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 2, "road_terrain_difficulty": 3, "supply_run_pain": 4}},
    "nomad_connectivity_rating": {"overall_rating": "Great on Ridge (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "3 bars 4G LTE", "tmobile_reliability": "2-3 bars 4G LTE", "terrain_obstruction_risk": "Low to Moderate on elevated forest pullouts", "distance_from_tower_corridor_miles": 8.5, "cellular_internet_dependable": True},
    "amenities": ["Caney Creek Wilderness Access", "Pine & Hardwood Shade", "Creek Swimming", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Mena, AR", "distance_miles": 18.0, "services_available": ["Grocery Stores", "Hospital", "Gas Stations", "Hardware", "Restaurants"]}],
    "seasonal_weather_effects": {"spring": "Lush spring green (60-72°F).", "summer": "Warm summer (84-90°F) with creek swimming.", "fall": "Crisp autumn foliage.", "winter": "Cool winter (38-50°F)."},
    "dangers_and_hazards": ["Flash Floods in Caney Creek", "Copperhead Snakes"],
    "acoustic_environment": {"quietness_rating": "Wilderness Edge Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Caney creek water flow", "Pine wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Shortleaf Pine", "White Oak", "American Beech", "Sweetgum"], "common_animals": ["White-tailed Deer", "Black Bear", "Wild Turkey", "Smallmouth Bass"]},
    "human_demographics_and_culture": "Caddo indigenous heritage and Polk County timber history.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Caney Creek Wilderness protects 14,460 acres of untouched Ouachita mountain forest.", "energetic_and_spiritual_features": "Pristine wilderness edge stream flowing over polished Ouachita quartz stones."},
    "nearby_hiking_trails": [{"trail_name": "Caney Creek Wilderness Trail", "length_miles": 9.5, "difficulty": "Moderate to Strenuous", "features": "Old-growth hardwoods, crystal clear creek crossings, mountain ridges"}],
    "public_reviews_summary": "Peaceful wilderness edge camping near Mena with reliable cell service and crystal clear stream swimming.",
    "other_data": "18 miles from Mena.",
    "last_updated": "2026-09-12"
  }
])
save_state(ar, ar_path)
print("Updated Arkansas -> 10 sites.")

# 4. Missouri (+5 sites -> 10 total)
mo, mo_path = load_state("missouri")
mo.extend([
  {
    "id": "missouri-006",
    "name": "Eleven Point Dispersed Area - Mark Twain National Forest",
    "state": "Missouri",
    "county": "Oregon",
    "coordinates": {"latitude": 36.7812, "longitude": -91.2812, "elevation_ft": 550.0},
    "management_agency": {"name": "U.S. Forest Service - Mark Twain National Forest (Eleven Point District)", "type": "Federal", "phone": "(417) 256-7151", "website": "https://www.fs.usda.gov/mtnf"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside float camp fee sites)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest lands along Eleven Point National Wild and Scenic River corridor. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Eleven Point River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 2, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great on Ridge (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low to Moderate on ridge pullouts", "distance_from_tower_corridor_miles": 7.0, "cellular_internet_dependable": True},
    "amenities": ["Eleven Point National Wild & Scenic River", "Spring-fed River Canoeing", "Dolomite Bluffs", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Alton, MO", "distance_miles": 12.0, "services_available": ["Gas Station", "Grocery Store", "Diner", "Hardware"]}, {"town_name": "West Plains, MO", "distance_miles": 32.0, "services_available": ["Full City Services", "Hospital", "Walmart", "Gyms"]}],
    "seasonal_weather_effects": {"spring": "Lush Ozark spring (62-74°F).", "summer": "Warm summer (84-90°F) with cool spring-fed river swimming.", "fall": "Spectacular Ozark autumn foliage.", "winter": "Cool winter (35-48°F)."},
    "dangers_and_hazards": ["River Cold Currents near Springs", "Copperhead Snakes"],
    "acoustic_environment": {"quietness_rating": "Spring-Fed River Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Eleven Point River flow", "Pine wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Shortleaf Pine", "White Oak", "Sycamore", "Dogwood"], "common_animals": ["River Otter", "White-tailed Deer", "Bald Eagle", "Smallmouth Bass", "Hellbender Salamander"]},
    "human_demographics_and_culture": "Osage ancestral lands and Ozark float trip canoe culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Greer Spring pours 220 million gallons of crystal clear 55°F water daily into the Eleven Point River.", "energetic_and_spiritual_features": "Spring-fed turquoise river flowing beneath towering dolomite bluffs."},
    "nearby_hiking_trails": [{"trail_name": "Greer Spring Trail", "length_miles": 2.0, "difficulty": "Easy to Moderate", "features": "Massive freshwater spring outburst, dolomite gorge, river confluence"}],
    "public_reviews_summary": "Pristine Wild and Scenic river float country with easy access and good cell service on ridge pullouts.",
    "other_data": "Visit Greer Spring, 2nd largest spring in the Ozarks.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "missouri-007",
    "name": "Bell Mountain Dispersed Area - Mark Twain NF",
    "state": "Missouri",
    "county": "Iron",
    "coordinates": {"latitude": 37.6123, "longitude": -90.8812, "elevation_ft": 1700.0},
    "management_agency": {"name": "U.S. Forest Service - Potosi Ranger District", "type": "Federal", "phone": "(573) 438-5427", "website": "https://www.fs.usda.gov/mtnf"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside wilderness boundary)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free dispersed primitive camping on forest pullouts along Highway A / FR 2228 approaching Bell Mountain Wilderness trailhead. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Paved highway to gravel forest road", "road_conditions": "Paved Highway A to well-graded gravel forest road.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 2, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low on high St. Francois mountain ridge", "distance_from_tower_corridor_miles": 5.5, "cellular_internet_dependable": True},
    "amenities": ["St. Francois Mountain Rhyolite Glades", "Bell Mountain Wilderness Trailhead", "Panoramic Ozark Views", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 5, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Ironton / Farmington, MO", "distance_miles": 16.0, "services_available": ["Grocery Stores", "Hospital", "Gas Stations", "Hardware", "Restaurants"]}],
    "seasonal_weather_effects": {"spring": "Lush mountain spring (60-72°F).", "summer": "Warm summer (82-88°F) with cool ridge breezes.", "fall": "Stunning Ozark mountain autumn foliage.", "winter": "Cool winter (32-45°F)."},
    "dangers_and_hazards": ["Exposed Rhyolite Glade Drop-offs", "Ticks in Spring"],
    "acoustic_environment": {"quietness_rating": "St. Francois Mountain Silence (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind over granite glades", "Songbird calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Shortleaf Pine", "Post Oak", "Farkleberry", "Rhyolite Glade Moss"], "common_animals": ["White-tailed Deer", "Collared Lizard", "Black Bear", "Wild Turkey"]},
    "human_demographics_and_culture": "Osage ancestral lands and St. Francois mountain iron mining history.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "St. Francois Mountains are among the oldest exposed rock formations in North America, over 1.4 billion years old.", "energetic_and_spiritual_features": "Red rhyolite rock glades commanding panoramic vistas over Shutdown Creek valley."},
    "nearby_hiking_trails": [{"trail_name": "Bell Mountain Wilderness Loop Trail", "length_miles": 8.0, "difficulty": "Moderate to Strenuous", "features": "Rhyolite glades, 360-degree St. Francois mountain views, pine groves"}],
    "public_reviews_summary": "Ancient 1.4 billion year old rhyolite mountain scenery with blazing 5G cell service on ridge pullouts.",
    "other_data": "Taum Sauk Mountain State Park nearby.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "missouri-008",
    "name": "Glade Top Trail Dispersed Area - Mark Twain NF",
    "state": "Missouri",
    "county": "Douglas",
    "coordinates": {"latitude": 36.7123, "longitude": -92.7412, "elevation_ft": 1450.0},
    "management_agency": {"name": "U.S. Forest Service - Ava Ranger District", "type": "Federal", "phone": "(417) 683-4428", "website": "https://www.fs.usda.gov/mtnf"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed camping allowed in designated gravel pullouts along Glade Top National Forest Scenic Byway. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from dry glade washes. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel scenic byway", "road_conditions": "23-mile well-graded gravel scenic byway along ridge tops.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low on 23-mile ridge top scenic byway", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["23-Mile National Scenic Byway Overlooks", "Limestone Glade Flora", "Panoramic Ozark Horizons", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 5, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Ava, MO", "distance_miles": 14.0, "services_available": ["Grocery Stores", "Gas Stations", "Hardware", "Diner"]}, {"town_name": "Springfield, MO", "distance_miles": 48.0, "services_available": ["Full Urban Services", "Airport", "Bass Pro Shops", "Hospital"]}],
    "seasonal_weather_effects": {"spring": "Lush wild Smoke Tree spring (60-72°F).", "summer": "Warm summer (82-88°F) with cool ridge breezes.", "fall": "Famous Ozark fall foliage panorama.", "winter": "Cool winter (35-48°F)."},
    "dangers_and_hazards": ["High Ridge Wind Gusts", "Rattlesnakes in Glades"],
    "acoustic_environment": {"quietness_rating": "Scenic Byway Ridge Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind over limestone glades", "Songbird calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["American Smoke Tree", "Eastern Red Cedar", "Post Oak", "Purple Coneflower"], "common_animals": ["Roadrunner", "White-tailed Deer", "Collared Lizard", "Wild Turkey"]},
    "human_demographics_and_culture": "Osage ancestral territory and Missouri Ozark glade conservation heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Missouri's only designated National Forest Scenic Byway, traversing narrow limestone glade ridge crests.", "energetic_and_spiritual_features": "Sweeping 40-mile vistas across the rolling Ozark hills from open limestone glades."},
    "nearby_hiking_trails": [{"trail_name": "Caney Mountain Glade Trail", "length_miles": 3.0, "difficulty": "Easy to Moderate", "features": "Limestone glade wildflowers, smoke trees, panoramic Ozark vistas"}],
    "public_reviews_summary": "Missouri's premier ridge top scenic drive with incredible 40-mile views and lightning fast 5G cell service.",
    "other_data": "Smoke Tree bloom in May is a major highlight.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "missouri-009",
    "name": "Black River Dispersed Area - Mark Twain NF",
    "state": "Missouri",
    "county": "Reynolds",
    "coordinates": {"latitude": 37.3512, "longitude": -90.8123, "elevation_ft": 600.0},
    "management_agency": {"name": "U.S. Forest Service - Salem Ranger District", "type": "Federal", "phone": "(573) 729-6656", "website": "https://www.fs.usda.gov/mtnf"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside developed fee loops)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free dispersed primitive camping on national forest pullouts along Black River access roads. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Black River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; smooth gravel pullouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low along Black River gravel bars", "distance_from_tower_corridor_miles": 6.5, "cellular_internet_dependable": True},
    "amenities": ["Crystal Clear Black River Gravel Bars", "Canoeing & Kayaking", "Johnson's Shut-Ins Proximity", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Lesterville / Ellington, MO", "distance_miles": 10.0, "services_available": ["Gas Station", "Grocery Store", "Canoe Outfitters", "Diner"]}],
    "seasonal_weather_effects": {"spring": "Lush Ozark spring (62-74°F).", "summer": "Warm summer (84-90°F) with clear gravel bar river swimming.", "fall": "Crisp autumn foliage.", "winter": "Cool winter (32-45°F)."},
    "dangers_and_hazards": ["Flash Floods on Gravel Bars", "Copperhead Snakes"],
    "acoustic_environment": {"quietness_rating": "Gravel Bar River Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Black River gravel bar flow", "Canoe paddle dips"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Sycamore", "River Birch", "Shortleaf Pine", "Sweetgum"], "common_animals": ["Smallmouth Bass", "White-tailed Deer", "River Otter", "Great Blue Heron"]},
    "human_demographics_and_culture": "Osage ancestral territory and Black River gravel bar canoe culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Johnson's Shut-Ins state park nearby features 1.4 billion year old volcanic rock chutes carved by the Black River.", "energetic_and_spiritual_features": "Crystal clear spring-fed Ozark river flowing over smooth chert gravel bars."},
    "nearby_hiking_trails": [{"trail_name": "Scour Trail (Johnson's Shut-Ins)", "length_miles": 2.5, "difficulty": "Moderate", "features": "Proterozoic volcanic rock shut-ins, Black River gravel bars, canyon shut-ins"}],
    "public_reviews_summary": "Incredible crystal clear river gravel bar camping near Johnson's Shut-Ins with solid cell service.",
    "other_data": "Never camp on low gravel bars when heavy rain is forecast.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "missouri-010",
    "name": "Ridge Runner Dispersed Area - Mark Twain NF",
    "state": "Missouri",
    "county": "Howell",
    "coordinates": {"latitude": 36.8812, "longitude": -91.9412, "elevation_ft": 1100.0},
    "management_agency": {"name": "U.S. Forest Service - Willow Springs District", "type": "Federal", "phone": "(417) 469-3155", "website": "https://www.fs.usda.gov/mtnf"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside trailhead fee lot)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed along Forest Road 2010 pullouts near Ridge Runner trailhead. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Noblett Lake / streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low on elevated forest ridge", "distance_from_tower_corridor_miles": 5.5, "cellular_internet_dependable": True},
    "amenities": ["Ridge Runner National Rec Trailhead", "Noblett Lake Access Nearby", "Pine & Oak Shade", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 7, "distance_to_gym_score": 6, "terrain_score": 8, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Willow Springs, MO", "distance_miles": 12.0, "services_available": ["Grocery Store", "Gas Station", "Hardware", "Diner"]}, {"town_name": "West Plains, MO", "distance_miles": 22.0, "services_available": ["Full City Services", "Hospital", "Walmart", "Gyms"]}],
    "seasonal_weather_effects": {"spring": "Lush pine spring (60-72°F).", "summer": "Warm summer (82-88°F) with lake swimming.", "fall": "Crisp autumn trail hiking days.", "winter": "Cool winter (35-48°F)."},
    "dangers_and_hazards": ["Ticks in Spring Brush", "Copperhead Snakes"],
    "acoustic_environment": {"quietness_rating": "Ozark Pine Ridge Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind through shortleaf pine canopy", "Songbird calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Shortleaf Pine", "White Oak", "Post Oak", "Dogwood"], "common_animals": ["White-tailed Deer", "Wild Turkey", "Gray Fox", "Large-mouth Bass"]},
    "human_demographics_and_culture": "Osage ancestral lands and 1930s CCC lake & trail build heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Civilian Conservation Corps (CCC) constructed historic stone dam at Noblett Lake in 1936.", "energetic_and_spiritual_features": "Quiet shortleaf pine ridge trailing into historic Ozark hollows."},
    "nearby_hiking_trails": [{"trail_name": "Ridge Runner National Recreation Trail", "length_miles": 8.0, "difficulty": "Moderate", "features": "Pine ridges, Noblett Lake loop, CCC stone springhouse ruins"}],
    "public_reviews_summary": "Excellent free basecamp near West Plains with 22-mile Ridge Runner trail access and blazing 5G cell service.",
    "other_data": "12 miles from Willow Springs.",
    "last_updated": "2026-09-12"
  }
])
save_state(mo, mo_path)
print("Updated Missouri -> 10 sites.")

# 5. Michigan (+5 sites -> 10 total)
mi, mi_path = load_state("michigan")
mi.extend([
  {
    "id": "michigan-006",
    "name": "Nordhouse Dunes Dispersed Primitive Area - Huron-Manistee NF",
    "state": "Michigan",
    "county": "Mason",
    "coordinates": {"latitude": 44.0812, "longitude": -86.4512, "elevation_ft": 620.0},
    "management_agency": {"name": "U.S. Forest Service - Huron-Manistee National Forests", "type": "Federal", "phone": "(231) 723-5511", "website": "https://www.fs.usda.gov/hmnf"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside parking lot)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest lands 400 ft back from Lake Michigan shoreline and outside wilderness boundary. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Lake Michigan and dune wetlands. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock/sand fire rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Paved road to gravel forest road", "road_conditions": "Paved Nurnberg Road leads to gravel trailhead access; smooth when dry.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars to trailhead parking.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low on open Lake Michigan sand dunes", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["Lake Michigan Sand Dunes Shoreline", "Freshwater Beach Swimming", "Wilderness Trails", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 7, "distance_to_gym_score": 6, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Ludington, MI", "distance_miles": 14.0, "services_available": ["Full Groceries", "Hospital", "Gas Stations", "Hardware", "Gyms"]}],
    "seasonal_weather_effects": {"spring": "Breezy dune spring (55-68°F).", "summer": "Warm sunny summer (75-84°F) with Lake Michigan beach swimming.", "fall": "Crisp clear autumn days.", "winter": "Snow-covered dunes; freezing cold wind."},
    "dangers_and_hazards": ["Rip Currents in Lake Michigan", "Poison Ivy in Dunes", "High Lake Winds"],
    "acoustic_environment": {"quietness_rating": "Freshwater Dune Wave Silence (Quietness Score: 9/10)", "common_human_made_sounds": ["Lake Michigan wave lap", "Dune wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Jack Pine", "White Pine", "Marram Grass", "Pitcher's Thistle"], "common_animals": ["Piping Plover", "White-tailed Deer", "Bald Eagle", "Porcupine"]},
    "human_demographics_and_culture": "Anishinaabe (Ottawa/Ojibwe) ancestral lands and Lake Michigan dune conservation heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Only designated wilderness area in Michigan's Lower Peninsula protecting 3,450 acres of coastal sand dunes.", "energetic_and_spiritual_features": "Towering natural freshwater sand dunes overlooking endless blue Lake Michigan horizons."},
    "nearby_hiking_trails": [{"trail_name": "Nordhouse Dunes Wilderness Trail", "length_miles": 4.5, "difficulty": "Easy to Moderate", "features": "Sand dune ridges, Lake Michigan beach, pine forest swales"}],
    "public_reviews_summary": "Michigan's ultimate free Lake Michigan beach dune camping spot with blazing 5G cell service.",
    "other_data": "Camp 400 ft back from high water mark mandatory.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "michigan-007",
    "name": "Pine River Dispersed Area - Huron-Manistee NF",
    "state": "Michigan",
    "county": "Wexford",
    "coordinates": {"latitude": 44.2123, "longitude": -85.8123, "elevation_ft": 820.0},
    "management_agency": {"name": "U.S. Forest Service - Cadillac-Manistee Ranger District", "type": "Federal", "phone": "(231) 723-5511", "website": "https://www.fs.usda.gov/hmnf"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside designated watercraft landings)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along Pine National Scenic River corridor outside developed landings. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Pine River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low to Moderate on river bluff pullouts", "distance_from_tower_corridor_miles": 6.0, "cellular_internet_dependable": True},
    "amenities": ["Pine National Scenic River Canoeing", "High Sandy Bluff Views", "Trout Fishing", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 6, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Cadillac, MI", "distance_miles": 16.0, "services_available": ["Full Groceries", "Hospital", "Gas Stations", "Hardware", "Gyms"]}],
    "seasonal_weather_effects": {"spring": "Lush green pine spring (55-68°F).", "summer": "Warm pleasant summer (75-84°F) with fast-water river paddling.", "fall": "Spectacular northern hardwoods autumn foliage.", "winter": "Snowy winter (20-32°F)."},
    "dangers_and_hazards": ["Fast River Currents on Pine River", "Ticks in Spring"],
    "acoustic_environment": {"quietness_rating": "Pine River Bluff Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Pine River water rush", "Wind through white pines"]},
    "flora_and_fauna": {"common_plants_and_trees": ["White Pine", "Red Pine", "Sugar Maple", "Paper Birch"], "common_animals": ["Brown Trout", "Bald Eagle", "White-tailed Deer", "River Otter", "Black Bear"]},
    "human_demographics_and_culture": "Anishinaabe ancestral territory and Michigan lumber & river paddling culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Fastest flowing river in Michigan's Lower Peninsula, famous for high sandy banks and sharp oxbow bends.", "energetic_and_spiritual_features": "Deep clear sand-bottom river cutting through towering white pine bluffs."},
    "nearby_hiking_trails": [{"trail_name": "Silver Creek Pathway Trail", "length_miles": 4.0, "difficulty": "Easy to Moderate", "features": "Pine River bluffs, footbridges, white pine forest"}],
    "public_reviews_summary": "Michigan's premier canoe river forest camping with high sandy bluffs and strong cell service.",
    "other_data": "Watercraft permit required for paddling Pine River in peak summer.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "michigan-008",
    "name": "Sturgeon River Dispersed Area - Hiawatha National Forest",
    "state": "Michigan",
    "county": "Delta",
    "coordinates": {"latitude": 46.0812, "longitude": -86.7412, "elevation_ft": 750.0},
    "management_agency": {"name": "U.S. Forest Service - Hiawatha National Forest (Rapid River District)", "type": "Federal", "phone": "(906) 474-6442", "website": "https://www.fs.usda.gov/hiawatha"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free primitive dispersed camping on national forest pullouts along Sturgeon River corridor. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Sturgeon River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "3-4 bars 4G LTE", "tmobile_reliability": "2-3 bars 4G LTE", "terrain_obstruction_risk": "Low under Upper Peninsula pine forest", "distance_from_tower_corridor_miles": 7.5, "cellular_internet_dependable": True},
    "amenities": ["Sturgeon River Canoeing & Kayaking", "UP Boreal Pine Forest", "Northern Lights Stargazing", "Wildberry Picking"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Rapid River / Escanaba, MI", "distance_miles": 18.0, "services_available": ["Groceries", "Hospital", "Gas Stations", "Hardware", "Gyms"]}],
    "seasonal_weather_effects": {"spring": "Lush green UP spring (50-62°F).", "summer": "Pleasant UP summer (72-82°F) with cool forest shade.", "fall": "Spectacular Upper Peninsula fall colors.", "winter": "Deep snowy winter (15-28°F)."},
    "dangers_and_hazards": ["Black Bear Habitat", "Spring Mosquitoes & Blackflies"],
    "acoustic_environment": {"quietness_rating": "UP Boreal River Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Sturgeon River flow", "Loon calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["White Pine", "Balsam Fir", "Paper Birch", "Blueberry"], "common_animals": ["Black Bear", "White-tailed Deer", "Bald Eagle", "River Otter", "Brook Trout"]},
    "human_demographics_and_culture": "Ojibwe (Anishinaabe) ancestral territory and Upper Peninsula Yooper timber culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Sturgeon River National Wild and Scenic River corridor protecting pristine UP boreal forest.", "energetic_and_spiritual_features": "Pristine tea-colored boreal river flowing over polished stones."},
    "nearby_hiking_trails": [{"trail_name": "Sturgeon River Gorge Trail", "length_miles": 3.5, "difficulty": "Moderate", "features": "River gorge cliffs, hardwood-pine forest, wild rapids"}],
    "public_reviews_summary": "Classic Upper Peninsula river forest camping with great canoeing and dependable cell service.",
    "other_data": "Great blueberry picking in late July.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "michigan-009",
    "name": "Au Sable River Dispersed Area - Huron National Forest",
    "state": "Michigan",
    "county": "Oscoda",
    "coordinates": {"latitude": 44.6412, "longitude": -84.1234, "elevation_ft": 950.0},
    "management_agency": {"name": "U.S. Forest Service - Mio Ranger District", "type": "Federal", "phone": "(989) 826-3252", "website": "https://www.fs.usda.gov/hmnf"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside developed fee loops)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along Au Sable National Scenic River corridor outside fee campgrounds. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Au Sable River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low along elevated river bluff pullouts", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["Au Sable National Scenic River", "World-Class Blue-Ribbon Trout Fishing", "Canoeing & Kayaking", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 7, "distance_to_gym_score": 6, "terrain_score": 9, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Mio, MI", "distance_miles": 8.0, "services_available": ["Grocery Store", "Gas Stations", "Canoe Outfitters", "Hardware", "Diner"]}],
    "seasonal_weather_effects": {"spring": "Lush green pine spring (55-68°F).", "summer": "Warm pleasant summer (75-84°F) with world-class fly hatch.", "fall": "Spectacular northern autumn colors.", "winter": "Snowy winter (20-32°F)."},
    "dangers_and_hazards": ["River Wading Cold Hazards", "Ticks in Spring"],
    "acoustic_environment": {"quietness_rating": "Au Sable River Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Au Sable river flow", "Fly fisherman casting"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Jack Pine", "Red Pine", "White Pine", "Paper Birch"], "common_animals": ["Brown Trout", "Kirtland's Warbler", "Bald Eagle", "White-tailed Deer"]},
    "human_demographics_and_culture": "Ojibwe ancestral lands and legendary Au Sable River fly fishing culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Birthplace of Trout Unlimited in 1959 on the banks of the Au Sable River.", "energetic_and_spiritual_features": "World-famous sand-bottom trout river flowing through jack pine forests."},
    "nearby_hiking_trails": [{"trail_name": "Au Sable River Foot Trail", "length_miles": 3.0, "difficulty": "Easy", "features": "River bluff views, white pine canopy, fly fishing access"}],
    "public_reviews_summary": "World-class trout fly fishing river camping with easy access and blazing 5G cell service.",
    "other_data": "Home to the rare Kirtland's Warbler.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "michigan-010",
    "name": "Kingston Plains Dispersed Area - Lake Superior State Forest",
    "state": "Michigan",
    "county": "Alger",
    "coordinates": {"latitude": 46.5812, "longitude": -86.2812, "elevation_ft": 920.0},
    "management_agency": {"name": "Michigan Department of Natural Resources (DNR)", "type": "State", "phone": "(906) 293-5131", "website": "https://www.michigan.gov/dnr"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive state forest dispersed camping with free DNR permit)", "stay_limit": "15 days maximum stay limit", "guidelines": "Free dispersed primitive camping allowed on state forest lands in Kingston Plains pullouts. Post free DNR camping tag on camp. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from lakes/streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to DNR fire bans."},
    "access_and_road_conditions": {"road_type": "Graded sandy gravel forest road", "road_conditions": "Graded sandy gravel forest roads off H-58; smooth when dry.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars on main gravel tracks.", "scores": {"road_grade": 2, "road_terrain_difficulty": 3, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "3-4 bars 4G LTE", "tmobile_reliability": "2-3 bars 4G LTE", "terrain_obstruction_risk": "Low - wide open historic pine stump plains", "distance_from_tower_corridor_miles": 7.0, "cellular_internet_dependable": True},
    "amenities": ["Historic White Pine Stump Plains", "Pictured Rocks National Lakeshore Proximity", "Wild Blueberry Fields", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 9, "quietness_score": 10},
    "nearest_supply_towns": [{"town_name": "Grand Marais, MI", "distance_miles": 12.0, "services_available": ["Grocery Store", "Gas Station", "Tavern", "Hardware"]}, {"town_name": "Munising, MI", "distance_miles": 32.0, "services_available": ["Groceries", "Hospital", "Pictured Rocks Tours", "Hardware"]}],
    "seasonal_weather_effects": {"spring": "Cool UP spring (48-60°F).", "summer": "Pleasant UP summer (70-80°F) with blueberry picking.", "fall": "Spectacular Lake Superior autumn colors.", "winter": "Heavy lake-effect snow (15-28°F)."},
    "dangers_and_hazards": ["Black Bear Habitat", "Lake-Effect Snow in Late Fall"],
    "acoustic_environment": {"quietness_rating": "Open Stump Plains Silence (Quietness Score: 10/10)", "common_human_made_sounds": ["Wind over open pine plains", "Raven calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Bracken Fern", "Wild Blueberry", "Jack Pine", "Historic White Pine Stumps"], "common_animals": ["Black Bear", "Sandhill Crane", "White-tailed Deer", "Coyote"]},
    "human_demographics_and_culture": "Ojibwe ancestral territory and 1890s UP white pine lumber baron boom & bust history.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Haunting landscape of massive charred white pine stumps remaining from the 1890s logging era fires.", "energetic_and_spiritual_features": "Wide open historic pine plains offering vast sky horizons 15 minutes from Pictured Rocks."},
    "nearby_hiking_trails": [{"trail_name": "Kingston Plains Blueberry Trail", "length_miles": 3.0, "difficulty": "Easy", "features": "Historic giant pine stumps, blueberry picking, open plains vistas"}],
    "public_reviews_summary": "Eerie and beautiful historic white pine stump plains basecamp just minutes from Pictured Rocks with reliable cell service.",
    "other_data": "Free DNR camping tag required.",
    "last_updated": "2026-09-12"
  }
])
save_state(mi, mi_path)
print("Updated Michigan -> 10 sites.")

print("Batch P6 execution complete!")
