import json
import os

STATES_DIR = "/home/volmarr/.gemini/antigravity/scratch/Camping_Nomad_Life/states"

def load_state(name):
    path = os.path.join(STATES_DIR, f"{name}.json")
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f), path

def save_state(data, path):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")

# 1. Alaska (+5 sites -> 10 total)
ak, ak_path = load_state("alaska")
ak.extend([
  {
    "id": "alaska-006",
    "name": "Finger Mountain Dispersed Area - Dalton Highway BLM",
    "state": "Alaska",
    "county": "Yukon-Koyukuk Census Area",
    "coordinates": {"latitude": 66.3512, "longitude": -150.8123, "elevation_ft": 2200.0},
    "management_agency": {"name": "Bureau of Land Management (BLM) - Central Yukon Field Office", "type": "Federal", "phone": "(907) 474-2200", "website": "https://www.blm.gov/alaska"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive BLM dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed camping allowed along Dalton Highway pullouts. Pack out all human waste and garbage. Strict bear safety rules."},
    "waste_disposal_rules": {"poop_disposal": "Pack out human waste via wag-bag or bury 6 inches deep in tundra topsoil 200 ft from drainages.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy. Bear canister mandatory."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Bring firewood; no wood gathering in Arctic tundra.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to tundra fire bans in dry June."},
    "access_and_road_conditions": {"road_type": "Unpaved gravel and dirt Dalton Highway", "road_conditions": "Dalton Highway gravel with heavy industrial truck traffic, mud, and pot holes.", "vehicle_recommendation": "High clearance 4x4 or sturdy truck required; carry 2 full-sized spare tires.", "scores": {"road_grade": 5, "road_terrain_difficulty": 8, "supply_run_pain": 10}},
    "nomad_connectivity_rating": {"overall_rating": "No Service (1/5 Stars)", "verizon_reliability": "0 bars", "att_reliability": "0 bars", "tmobile_reliability": "0 bars", "terrain_obstruction_risk": "Low - open arctic tundra, but complete lack of cell towers", "distance_from_tower_corridor_miles": 98.0, "cellular_internet_dependable": False},
    "amenities": ["Arctic Circle Crossing Nearby", "Alpine Tundra Solitude", "Midnight Sun (Summer)", "Aurora Borealis (Fall)"],
    "location_scores": {"distance_to_groceries_score": 1, "distance_to_library_score": 1, "distance_to_gym_score": 1, "terrain_score": 10, "quietness_score": 10},
    "nearest_supply_towns": [{"town_name": "Coldfoot, AK", "distance_miles": 42.0, "services_available": ["Gas Pump", "Basic Cafe", "Post Office"]}, {"town_name": "Fairbanks, AK", "distance_miles": 210.0, "services_available": ["Full Urban Services", "Hospital", "Airport", "Walmart"]}],
    "seasonal_weather_effects": {"spring": "Breakup season; extreme mud and ice.", "summer": "24-hour Midnight Sun (55-68°F) with intense mosquitoes.", "fall": "Golden tundra color (August-Sept) with Aurora Borealis.", "winter": "Severe Arctic cold (-30 to -50°F); dangerous."},
    "dangers_and_hazards": ["Grizzly and Black Bear Encounters", "Industrial Haul Truck Traffic", "Extreme Remote Isolation"],
    "acoustic_environment": {"quietness_rating": "Arctic Tundra Silence (Quietness Score: 10/10)", "common_human_made_sounds": ["Occasional distant haul truck engine brake", "Tundra wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Arctic Tundra Moss", "Dwarf Birch", "Cottongrass"], "common_animals": ["Grizzly Bear", "Caribou", "Dall Sheep", "Arctic Fox", "Raven"]},
    "human_demographics_and_culture": "Koyukon Athabascan indigenous territory and Trans-Alaska Pipeline haul road culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Koyukon Athabascan traditions hold deep reverence for the sacred tundra animal spirits.", "energetic_and_spiritual_features": "Vast open Arctic wilderness north of the Arctic Circle under the Midnight Sun."},
    "nearby_hiking_trails": [{"trail_name": "Finger Mountain Alpine Tundra Trail", "length_miles": 1.0, "difficulty": "Easy", "features": "Granite tors, alpine tundra vegetation, Arctic valley vistas"}],
    "public_reviews_summary": "Bucket-list Arctic tundra adventure north of the Arctic Circle; zero cell service requires Starlink or satellite communication.",
    "other_data": "Carry extra fuel, food, and two spare tires.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "alaska-007",
    "name": "Brushkana Creek Dispersed Area - Denali Highway BLM",
    "state": "Alaska",
    "county": "Matanuska-Susitna Borough",
    "coordinates": {"latitude": 63.2112, "longitude": -148.4512, "elevation_ft": 2900.0},
    "management_agency": {"name": "Bureau of Land Management (BLM) - Glennallen Field Office", "type": "Federal", "phone": "(907) 822-3217", "website": "https://www.blm.gov/alaska"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive BLM dispersed camping outside developed loop)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed camping allowed along Denali Highway pullouts. Pack out all trash. Strict bear food safety."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6 inches deep in tundra topsoil 200 ft from Brushkana Creek. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy. Bear canister mandatory."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down spruce wood.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to state fire bans."},
    "access_and_road_conditions": {"road_type": "Unpaved gravel Denali Highway", "road_conditions": "135-mile unpaved gravel road; ruts, loose rocks, and washboards.", "vehicle_recommendation": "Sturdy truck, SUV, or high clearance camper recommended; carry spare tire.", "scores": {"road_grade": 4, "road_terrain_difficulty": 6, "supply_run_pain": 8}},
    "nomad_connectivity_rating": {"overall_rating": "No Service (1/5 Stars)", "verizon_reliability": "0 bars", "att_reliability": "0 bars", "tmobile_reliability": "0 bars", "terrain_obstruction_risk": "Moderate in Alaska Range valley", "distance_from_tower_corridor_miles": 55.0, "cellular_internet_dependable": False},
    "amenities": ["Alaska Range Snowcap Views", "Grayling Fly Fishing", "Tundra Berry Picking", "Dark Sky Aurora Borealis"],
    "location_scores": {"distance_to_groceries_score": 2, "distance_to_library_score": 2, "distance_to_gym_score": 1, "terrain_score": 10, "quietness_score": 10},
    "nearest_supply_towns": [{"town_name": "Cantwell, AK", "distance_miles": 30.0, "services_available": ["Gas Station", "General Store", "Diner"]}, {"town_name": "Fairbanks, AK", "distance_miles": 150.0, "services_available": ["Full Urban Services", "Hospital", "Walmart", "Airport"]}],
    "seasonal_weather_effects": {"spring": "Snow melts late May.", "summer": "Mild tundra summer (60-72°F) with long daylight.", "fall": "Vibrant red tundra color (August-Sept) with Northern Lights.", "winter": "Road unplowed; closed to vehicles."},
    "dangers_and_hazards": ["Grizzly Bear Habitat", "Remote Tire Punctures", "Sudden Frosts in August"],
    "acoustic_environment": {"quietness_rating": "Subarctic Wilderness Silence (Quietness Score: 10/10)", "common_human_made_sounds": ["Brushkana Creek flow", "Wind through dwarf birch"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Black Spruce", "Dwarf Willow", "Blueberry", "Lingonberry"], "common_animals": ["Grizzly Bear", "Moose", "Caribou", "Arctic Grayling", "Ptarmigan"]},
    "human_demographics_and_culture": "Ahtna Athabascan ancestral lands and historic Denali pioneer highway heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Ahtna Athabascan tradition honors the sacred peaks of the Alaska Range.", "energetic_and_spiritual_features": "Panoramic wilderness framed by the snowcapped peaks of the Alaska Range."},
    "nearby_hiking_trails": [{"trail_name": "Brushkana Creek Tundra Ridge Walk", "length_miles": 3.0, "difficulty": "Easy to Moderate", "features": "Subarctic tundra, grayling fishing stream, Alaska Range vistas"}],
    "public_reviews_summary": "Unbelievable Alaska Range wilderness driving route; complete disconnection requiring Starlink for internet.",
    "other_data": "Excellent Arctic grayling fishing in Brushkana Creek.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "alaska-008",
    "name": "Hatcher Pass Dispersed Area - State Management Area",
    "state": "Alaska",
    "county": "Matanuska-Susitna Borough",
    "coordinates": {"latitude": 61.7845, "longitude": -149.2812, "elevation_ft": 3800.0},
    "management_agency": {"name": "Alaska Department of Natural Resources (DNR)", "type": "State", "phone": "(907) 745-3974", "website": "https://dnr.alaska.gov"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive state dispersed camping outside park fee lots)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed camping allowed on state public lands along Fishhook / Willow Creek Road outside developed Independence Mine state park lots. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6 inches deep 200 ft from alpine streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy. Bear safety mandatory."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Bring firewood; no wood gathering in alpine tundra.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to DNR fire bans."},
    "access_and_road_conditions": {"road_type": "Paved road transitioning to gravel mountain pass", "road_conditions": "Paved from Palmer/Wasilla, turns to steep narrow gravel pass road.", "vehicle_recommendation": "Accessible by low-clearance 2WD to lower valley; high clearance / 4WD for upper pass.", "scores": {"road_grade": 6, "road_terrain_difficulty": 5, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great on Lower Slopes (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "3 bars 4G LTE", "tmobile_reliability": "2-3 bars 4G LTE", "terrain_obstruction_risk": "Moderate in Talkeetna mountain cirque", "distance_from_tower_corridor_miles": 12.0, "cellular_internet_dependable": True},
    "amenities": ["Talkeetna Mountain Alpine Peaks", "Historic Gold Mine Ruins Nearby", "Alpine Lake Views", "Dark Sky Aurora"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 6, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Palmer, AK", "distance_miles": 16.0, "services_available": ["Full Groceries", "Hospital", "Gas Stations", "Hardware"]}, {"town_name": "Wasilla, AK", "distance_miles": 22.0, "services_available": ["Walmart", "Target", "All Urban Services"]}],
    "seasonal_weather_effects": {"spring": "Snow lingers into June.", "summer": "Pleasant alpine summer (60-70°F).", "fall": "Golden tundra colors (Aug-Sept) with Northern Lights.", "winter": "Snow sports paradise; road closed over pass."},
    "dangers_and_hazards": ["Avalanche Danger in Winter/Spring", "Bear Encounters", "Steep Mountain Drops"],
    "acoustic_environment": {"quietness_rating": "Alpine Cirque Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Alpine stream flow", "Occasional visitor car pass"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Alpine Tundra", "Fireweed", "Dwarf Birch", "Blueberry"], "common_animals": ["Hoary Marmot", "Pika", "Arctic Ground Squirrel", "Black Bear", "Dall Sheep"]},
    "human_demographics_and_culture": "Dena'ina Athabascan territory and 1930s Independence Mine hard-rock gold mining culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Dena'ina Athabascan tradition honors the Talkeetna peaks as sacred hunting lands.", "energetic_and_spiritual_features": "Dramatic glacial alpine bowls surrounded by sharp granite peaks."},
    "nearby_hiking_trails": [{"trail_name": "April Bowl Trail", "length_miles": 2.2, "difficulty": "Moderate", "features": "Alpine tarn lakes, granite spires, 360-degree mountain panorama"}],
    "public_reviews_summary": "World-class alpine scenery just 20 minutes from Palmer with solid cell service on lower mountain slopes.",
    "other_data": "Visit Independence Mine State Historical Park nearby.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "alaska-009",
    "name": "Skilak Lake Dispersed Area - Kenai National Wildlife Refuge",
    "state": "Alaska",
    "county": "Kenai Peninsula Borough",
    "coordinates": {"latitude": 60.4812, "longitude": -150.3412, "elevation_ft": 350.0},
    "management_agency": {"name": "U.S. Fish and Wildlife Service - Kenai NWR", "type": "Federal", "phone": "(907) 262-7021", "website": "https://www.fws.gov/refuge/kenai"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFWS dispersed camping outside fee loops)", "stay_limit": "14 days maximum stay limit", "guidelines": "Primitive dispersed camping allowed at designated pullouts along Skilak Loop Road outside fee campgrounds. Pack out all trash. Strict bear food regulations."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6 inches deep 200 ft from Skilak Lake / Kenai River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy. Approved bear container mandatory."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFWS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel loop road", "road_conditions": "Well-maintained gravel Skilak Loop Road off Sterling Highway.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 2, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Good (3.5/5 Stars)", "verizon_reliability": "3 bars 4G LTE", "att_reliability": "2-3 bars 4G LTE", "tmobile_reliability": "2 bars 4G LTE", "terrain_obstruction_risk": "Low to Moderate along lake shoreline", "distance_from_tower_corridor_miles": 8.5, "cellular_internet_dependable": True},
    "amenities": ["Glacial Turquoise Lake Views", "Kenai River Salmon Fishing Nearby", "Wildlife Viewing", "Dark Sky Stargazing"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 5, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Soldotna, AK", "distance_miles": 22.0, "services_available": ["Fred Meyer", "Hospital", "Gas Stations", "Gear Shops", "Gyms"]}, {"town_name": "Sterling, AK", "distance_miles": 12.0, "services_available": ["Gas Station", "Grocery Store", "Tackle Shops"]}],
    "seasonal_weather_effects": {"spring": "Lush coastal spring (50-62°F).", "summer": "Mild pleasant summer (62-72°F).", "fall": "Crisp autumn salmon run season.", "winter": "Snow and ice on lake; freezing cold."},
    "dangers_and_hazards": ["High Density Brown Bear (Grizzly) Habitat", "Cold Glacial Water Hazards"],
    "acoustic_environment": {"quietness_rating": "Kenai Glacial Lake Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Loon calls across water", "Gentle lake wave lap"]},
    "flora_and_fauna": {"common_plants_and_trees": ["White Spruce", "Paper Birch", "Kenai Willow", "Fireweed"], "common_animals": ["Brown Bear (Grizzly)", "Black Bear", "Kenai Moose", "Bald Eagle", "Sockeye Salmon"]},
    "human_demographics_and_culture": "Dena'ina Athabascan ancestral lands and Kenai Peninsula salmon fishing heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Dena'ina tradition reveres Skilak Lake as a sacred fishing lake of life.", "energetic_and_spiritual_features": "Glacial turquoise lake water reflecting the Kenai Mountains."},
    "nearby_hiking_trails": [{"trail_name": "Skilak Lookout Trail", "length_miles": 2.6, "difficulty": "Moderate", "features": "Panoramic views of Skilak Lake, Kenai River valley, birch forests"}],
    "public_reviews_summary": "Stunning glacial lake setting in the heart of Kenai wildlife refuge with usable cell service.",
    "other_data": "High brown bear concentration during salmon runs; carry bear spray.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "alaska-010",
    "name": "Chena River Primitive Area - Chena River State Rec Area",
    "state": "Alaska",
    "county": "Fairbanks North Star Borough",
    "coordinates": {"latitude": 64.9123, "longitude": -146.5412, "elevation_ft": 750.0},
    "management_agency": {"name": "Alaska State Parks - Northern Region", "type": "State", "phone": "(907) 451-2695", "website": "https://dnr.alaska.gov/parks"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive state dispersed camping along river pullouts)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed at unpaved pullouts along Chena Hot Springs Road outside developed fee campgrounds. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6 inches deep 200 ft from Chena River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy. Bear safety mandatory."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to state fire bans during dry June."},
    "access_and_road_conditions": {"road_type": "Paved highway to dirt river pullouts", "road_conditions": "Paved Chena Hot Springs Road with smooth gravel dirt pullouts.", "vehicle_recommendation": "Accessible by all low-clearance 2WD passenger cars and RVs.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "3-4 bars 4G LTE", "tmobile_reliability": "2-3 bars 4G LTE", "terrain_obstruction_risk": "Low along Chena River valley floor", "distance_from_tower_corridor_miles": 6.0, "cellular_internet_dependable": True},
    "amenities": ["Chena River Canoeing & Fishing", "Hot Springs Proximity", "Midnight Sun", "Aurora Borealis Viewing"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 6, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Fairbanks, AK", "distance_miles": 28.0, "services_available": ["Full Urban Services", "Hospital", "Walmart", "Airport", "Gyms"]}],
    "seasonal_weather_effects": {"spring": "Breakup season in May.", "summer": "Warm interior Alaska summer (72-85°F) with Midnight Sun.", "fall": "Golden autumn birches (Aug-Sept) with world-class Aurora Borealis.", "winter": "Extreme interior cold (-20 to -40°F) with Northern Lights."},
    "dangers_and_hazards": ["Black Bear and Grizzly Habitat", "Moose Encounters"],
    "acoustic_environment": {"quietness_rating": "Boreal Forest River Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Chena River water flow", "Occasional road car pass"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Paper Birch", "White Spruce", "Quaking Aspen", "Fireweed"], "common_animals": ["Moose", "Black Bear", "Grizzly Bear", "Beaver", "Arctic Grayling"]},
    "human_demographics_and_culture": "Tanana Athabascan ancestral territory and Fairbanks interior pioneer heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Tanana Athabascan tradition honors the Chena River as a vital interior salmon and trade arterial.", "energetic_and_spiritual_features": "Pristine boreal river forest under the glowing Northern Lights."},
    "nearby_hiking_trails": [{"trail_name": "Angel Rocks Trail", "length_miles": 3.5, "difficulty": "Moderate", "features": "Granite rock tors, Chena River valley panorama, boreal forest"}],
    "public_reviews_summary": "Easy paved access, close to Fairbanks and Chena Hot Springs, with reliable cell service and phenomenal Aurora Borealis viewing.",
    "other_data": "Short drive to Chena Hot Springs resort.",
    "last_updated": "2026-09-12"
  }
])
save_state(ak, ak_path)
print("Updated Alaska -> 10 sites.")

# 2. South Dakota (+5 sites -> 10 total)
sd, sd_path = load_state("south_dakota")
sd.extend([
  {
    "id": "south_dakota-006",
    "name": "French Creek Dispersed Area - Buffalo Gap National Grassland",
    "state": "South Dakota",
    "county": "Custer",
    "coordinates": {"latitude": 43.7123, "longitude": -103.3412, "elevation_ft": 3100.0},
    "management_agency": {"name": "U.S. Forest Service - Buffalo Gap National Grassland", "type": "Federal", "phone": "(605) 273-1600", "website": "https://www.fs.usda.gov/nebraska"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive dispersed grassland camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free dispersed camping on open public grassland pullouts along French Creek road. Pack out all waste."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from French Creek. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Bring firewood; no wood gathering on prairie.", "safety_requirements": "Campfires strictly in metal fire pans or rock rings. Extinguish cold.", "seasonal_fire_bans": "Strict USFS stage fire bans in dry summer."},
    "access_and_road_conditions": {"road_type": "Graded gravel grassland road", "road_conditions": "Graded gravel access road; slick gumbo mud when wet.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars when dry.", "scores": {"road_grade": 2, "road_terrain_difficulty": 3, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "4 bars 4G LTE", "att_reliability": "3-4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low - open mixed-grass prairie", "distance_from_tower_corridor_miles": 7.0, "cellular_internet_dependable": True},
    "amenities": ["Black Hills Mountain Panorama Views", "Mixed-Grass Prairie", "Bison Viewing Nearby", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 5, "terrain_score": 8, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Custer, SD", "distance_miles": 14.0, "services_available": ["Groceries", "Hospital", "Hardware", "Restaurants"]}, {"town_name": "Rapid City, SD", "distance_miles": 42.0, "services_available": ["Full Urban Services", "Airport", "Walmart", "REI"]}],
    "seasonal_weather_effects": {"spring": "Breezy prairie spring (58-70°F).", "summer": "Warm summer (82-90°F) with afternoon thunderstorms.", "fall": "Crisp dry autumn days.", "winter": "Cold winter (25-38°F) with prairie snow."},
    "dangers_and_hazards": ["Gumbo Mud when Wet", "Severe Thunderstorms & Hail", "Rattlesnakes"],
    "acoustic_environment": {"quietness_rating": "Prairie Grassland Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Prairie wind", "Meadowlark calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Western Wheatgrass", "Green Needlegrass", "Prickly Pear"], "common_animals": ["American Bison", "Pronghorn Antelope", "Prairie Dog", "Coyote", "Burrowing Owl"]},
    "human_demographics_and_culture": "Oglala Lakota sacred land heritage and Black Hills pioneer ranching culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Great Plains Lakota sacred traditional buffalo hunting territory.", "energetic_and_spiritual_features": "Vast rolling grassland framing the dark silhouette of the Black Hills."},
    "nearby_hiking_trails": [{"trail_name": "French Creek Prairie Trail", "length_miles": 3.5, "difficulty": "Easy", "features": "Mixed-grass prairie, bison viewing, creek flora"}],
    "public_reviews_summary": "Peaceful prairie basecamp right outside Custer State Park with fast 4G cell service.",
    "other_data": "Do not drive on gumbo roads during rainstorms.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "south_dakota-007",
    "name": "Victoria Lake Dispersed Area - Black Hills National Forest",
    "state": "South Dakota",
    "county": "Pennington",
    "coordinates": {"latitude": 44.0212, "longitude": -103.3812, "elevation_ft": 4400.0},
    "management_agency": {"name": "U.S. Forest Service - Black Hills National Forest", "type": "Federal", "phone": "(605) 343-1567", "website": "https://www.fs.usda.gov/blackhills"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on designated forest pullouts along Victoria Road (FR 159). Camp within 30 ft of road. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Victoria Creek. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Gravel forest road", "road_conditions": "Graded gravel forest road with occasional ruts and washboard.", "vehicle_recommendation": "Accessible by standard low-clearance FWD passenger cars and camper vans.", "scores": {"road_grade": 2, "road_terrain_difficulty": 3, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low to Moderate under ponderosa pine canopy", "distance_from_tower_corridor_miles": 5.5, "cellular_internet_dependable": True},
    "amenities": ["Ponderosa Pine Canopy", "Rapid Creek Access Nearby", "Close to Rapid City", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 8, "distance_to_gym_score": 7, "terrain_score": 9, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Rapid City, SD", "distance_miles": 12.0, "services_available": ["Full Urban Services", "Hospital", "Walmart", "REI", "Target"]}],
    "seasonal_weather_effects": {"spring": "Lush pine forest spring (58-70°F).", "summer": "Warm pleasant summer (80-88°F) with cool pine nights.", "fall": "Crisp autumn weather.", "winter": "Cool winter (28-40°F) with snow."},
    "dangers_and_hazards": ["Summer Fire Hazard", "Mountain Lions", "High Summer Tourist Traffic"],
    "acoustic_environment": {"quietness_rating": "Black Hills Pine Forest (Quietness Score: 8/10)", "common_human_made_sounds": ["Wind through ponderosa needles", "Occasional forest road pass"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Ponderosa Pine", "Quaking Aspen", "Bur Oak", "Wild Rose"], "common_animals": ["Mountain Lion", "Mule Deer", "Elk", "Wild Turkey", "Red Squirrel"]},
    "human_demographics_and_culture": "Lakota sacred Black Hills (Pahá Sápə) heritage and Rapid City outdoor culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Pahá Sápə (Black Hills) is the sacred heartland of the Lakota Sioux nation.", "energetic_and_spiritual_features": "Fragrant ponderosa pine forest radiating deep grounding mountain stillness."},
    "nearby_hiking_trails": [{"trail_name": "Victoria Lake Trail", "length_miles": 3.2, "difficulty": "Moderate", "features": "Ponderosa pine forests, creek drainages, historic 1880s flume ruins"}],
    "public_reviews_summary": "Top choice for nomads wanting beautiful ponderosa pine forest camping just 15 minutes from Rapid City.",
    "other_data": "Camp within 30 ft of established forest road pullouts.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "south_dakota-008",
    "name": "Fort Pierre Dispersed Area - Fort Pierre National Grassland",
    "state": "South Dakota",
    "county": "Lyman",
    "coordinates": {"latitude": 44.1412, "longitude": -100.2812, "elevation_ft": 1800.0},
    "management_agency": {"name": "U.S. Forest Service - Fort Pierre National Grassland", "type": "Federal", "phone": "(605) 224-5117", "website": "https://www.fs.usda.gov/nebraska"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive dispersed grassland camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free dispersed camping on public grassland pullouts along USFS dirt roads. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from stock ponds and dry drainages. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Bring firewood; no wood gathering on prairie.", "safety_requirements": "Campfires strictly in metal fire pans. Extinguish cold.", "seasonal_fire_bans": "Strict USFS stage fire bans in dry summer."},
    "access_and_road_conditions": {"road_type": "Graded gravel and dirt grassland road", "road_conditions": "Graded gravel access roads; sticky gumbo clay mud when wet.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars when dry.", "scores": {"road_grade": 2, "road_terrain_difficulty": 3, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "4 bars 4G LTE", "att_reliability": "3-4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low - open rolling prairie", "distance_from_tower_corridor_miles": 8.0, "cellular_internet_dependable": True},
    "amenities": ["Endless Mixed-Grass Prairie", "Missouri River Nearby", "Stargazing", "Bird Watching"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 5, "terrain_score": 8, "quietness_score": 10},
    "nearest_supply_towns": [{"town_name": "Pierre / Fort Pierre, SD", "distance_miles": 15.0, "services_available": ["State Capital Services", "Full Groceries", "Hospital", "Hardware", "Gas Stations"]}],
    "seasonal_weather_effects": {"spring": "Breezy spring (55-68°F).", "summer": "Warm to hot summer (85-95°F) with sun.", "fall": "Crisp autumn prairie days.", "winter": "Cold windy winter (20-35°F)."},
    "dangers_and_hazards": ["Prairie Gumbo Mud", "High Prairie Winds", "Severe Summer Thunderstorms"],
    "acoustic_environment": {"quietness_rating": "Rolling Prairie Silence (Quietness Score: 10/10)", "common_human_made_sounds": ["Grassland wind", "Greater Prairie-Chicken booming"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Green Needlegrass", "Western Wheatgrass", "Yellow Coneflower"], "common_animals": ["Greater Prairie-Chicken", "Sharptailed Grouse", "Pronghorn", "Prairie Dog", "Coyote"]},
    "human_demographics_and_culture": "Lakota tradition, fur trade post history, and South Dakota state capital heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Historic 1830s Fort Pierre fur trading post and Lewis & Clark Missouri River expedition heritage.", "energetic_and_spiritual_features": "Rolling mixed-grass prairie rolling to the horizon under vast open skies."},
    "nearby_hiking_trails": [{"trail_name": "Fort Pierre Prairie Grouse Loop", "length_miles": 4.0, "difficulty": "Easy", "features": "Mixed-grass prairie, prairie-chicken leks, panoramic prairie horizons"}],
    "public_reviews_summary": "Vast quiet prairie solitude just 15 minutes from the state capital in Pierre with strong cell service.",
    "other_data": "Great location for bird watchers.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "south_dakota-009",
    "name": "Grand River Dispersed Area - Grand River National Grassland",
    "state": "South Dakota",
    "county": "Perkins",
    "coordinates": {"latitude": 45.7123, "longitude": -102.3412, "elevation_ft": 2600.0},
    "management_agency": {"name": "U.S. Forest Service - Grand River National Grassland", "type": "Federal", "phone": "(701) 225-5151", "website": "https://www.fs.usda.gov/d Dakota"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive dispersed grassland camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed camping allowed on open public grassland pullouts along USFS roads. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Grand River / Shadehill. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Bring firewood; no wood gathering on prairie.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel grassland road", "road_conditions": "Graded gravel access road; slick clay gumbo when wet.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars when dry.", "scores": {"road_grade": 2, "road_terrain_difficulty": 3, "supply_run_pain": 6}},
    "nomad_connectivity_rating": {"overall_rating": "Fair (3/5 Stars)", "verizon_reliability": "2-3 bars 4G LTE", "att_reliability": "2 bars 4G LTE", "tmobile_reliability": "1-2 bars 4G LTE", "terrain_obstruction_risk": "Low - open prairie badlands", "distance_from_tower_corridor_miles": 16.0, "cellular_internet_dependable": True},
    "amenities": ["Grand River Badlands", "Shadehill Reservoir Proximity", "Hugh Glass Monument Nearby", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 4, "distance_to_library_score": 4, "distance_to_gym_score": 2, "terrain_score": 8, "quietness_score": 10},
    "nearest_supply_towns": [{"town_name": "Bison, SD", "distance_miles": 18.0, "services_available": ["Gas Station", "Small Grocery", "Diner"]}, {"town_name": "Lemmon, SD", "distance_miles": 24.0, "services_available": ["Groceries", "Gas Stations", "Hardware Store", "Clinic"]}],
    "seasonal_weather_effects": {"spring": "Breezy spring (52-65°F).", "summer": "Warm to hot summer (84-94°F).", "fall": "Crisp dry autumn days.", "winter": "Cold freezing winter (15-32°F)."},
    "dangers_and_hazards": ["Gumbo Mud when Wet", "Severe Thunderstorms & Hail", "Extreme Remote Distance"],
    "acoustic_environment": {"quietness_rating": "Northern Plains Solitude (Quietness Score: 10/10)", "common_human_made_sounds": ["Prairie wind", "Coyote howling"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Western Wheatgrass", "Buffalograss", "Prickly Pear"], "common_animals": ["Pronghorn Antelope", "Mule Deer", "Prairie Dog", "Golden Eagle"]},
    "human_demographics_and_culture": "Standing Rock Sioux ancestral lands and Hugh Glass mountain man legend heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Site where legendary mountain man Hugh Glass survived a grizzly bear attack in 1823.", "energetic_and_spiritual_features": "Stark northern plains prairie badlands along the Grand River."},
    "nearby_hiking_trails": [{"trail_name": "Hugh Glass Memorial Prairie Trail", "length_miles": 2.5, "difficulty": "Easy", "features": "Grand River vistas, Hugh Glass historic monument, prairie badlands"}],
    "public_reviews_summary": "Profound northern plains solitude steeped in mountain man history; usable 4G cell service.",
    "other_data": "Visit Hugh Glass monument on Shadehill reservoir shore.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "south_dakota-010",
    "name": "Cave Hills Dispersed Area - Custer National Forest",
    "state": "South Dakota",
    "county": "Harding",
    "coordinates": {"latitude": 45.8123, "longitude": -103.5412, "elevation_ft": 3400.0},
    "management_agency": {"name": "U.S. Forest Service - Custer Gallatin NF (Sioux District)", "type": "Federal", "phone": "(605) 797-4432", "website": "https://www.fs.usda.gov/custergallatin"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free dispersed primitive camping on Custer NF sandbutte pullouts. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from dry washes. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Gravel forest spur road", "road_conditions": "Graded gravel forest road; slick mud when wet.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars when dry.", "scores": {"road_grade": 3, "road_terrain_difficulty": 4, "supply_run_pain": 7}},
    "nomad_connectivity_rating": {"overall_rating": "Fair (3/5 Stars)", "verizon_reliability": "2-3 bars 4G LTE", "att_reliability": "2 bars 4G LTE", "tmobile_reliability": "1-2 bars 4G LTE", "terrain_obstruction_risk": "Moderate near sandstone bluff walls", "distance_from_tower_corridor_miles": 18.0, "cellular_internet_dependable": True},
    "amenities": ["Sandstone Butte Cliffs", "Ponderosa Pine Islands", "Petroglyph Caves Nearby", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 3, "distance_to_library_score": 3, "distance_to_gym_score": 1, "terrain_score": 9, "quietness_score": 10},
    "nearest_supply_towns": [{"town_name": "Buffalo, SD", "distance_miles": 16.0, "services_available": ["Gas Station", "Small Grocery", "Diner", "Hardware Store"]}],
    "seasonal_weather_effects": {"spring": "Breezy spring (50-64°F).", "summer": "Warm summer (82-90°F) with cool night breeze.", "fall": "Crisp dry autumn days.", "winter": "Cold freezing winter (15-30°F)."},
    "dangers_and_hazards": ["Gumbo Mud when Wet", "Rattlesnakes", "Remote Location"],
    "acoustic_environment": {"quietness_rating": "Sandstone Butte Silence (Quietness Score: 10/10)", "common_human_made_sounds": ["Wind through cliff pines", "Coyote calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Ponderosa Pine", "Green Needlegrass", "Yucca", "Skunkbush Sumac"], "common_animals": ["Mule Deer", "Pronghorn", "Porcupine", "Golden Eagle", "Merlin"]},
    "human_demographics_and_culture": "Lakota and Cheyenne sacred cave art culture and northwestern SD ranching heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Lakota and Cheyenne tradition views Ludlow Cave and sandstone arches as sacred medicine sites.", "energetic_and_spiritual_features": "Island sandstone pine bluffs rising dramatically out of the open prairie."},
    "nearby_hiking_trails": [{"trail_name": "Cave Hills Sandstone Bluff Trail", "length_miles": 3.0, "difficulty": "Moderate", "features": "Sandstone caves, petroglyph panels, ponderosa pine bluffs"}],
    "public_reviews_summary": "Hidden jewel of northwestern South Dakota; dramatic sandstone pine bluffs with usable cell service.",
    "other_data": "Do not deface historic rock art.",
    "last_updated": "2026-09-12"
  }
])
save_state(sd, sd_path)
print("Updated South Dakota -> 10 sites.")

# Save all updated states cleanly
print("Batch P5 execution complete!")
