import json
import os

STATES_DIR = "/home/volmarr/.gemini/antigravity/scratch/Camping_Nomad_Life/states"

def load_state(name):
    path = os.path.join(STATES_DIR, f"{name}.json")
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f), path

def save_state(data, path):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")

# 1. Oklahoma (+5 sites -> 10 total)
ok, ok_path = load_state("oklahoma")
ok.extend([
  {
    "id": "oklahoma-006",
    "name": "Kiamichi River Dispersed Area - Ouachita NF",
    "state": "Oklahoma",
    "county": "Le Flore",
    "coordinates": {"latitude": 34.7123, "longitude": -94.7412, "elevation_ft": 1150.0},
    "management_agency": {"name": "U.S. Forest Service - Ouachita National Forest (Choctaw District)", "type": "Federal", "phone": "(918) 653-2991", "website": "https://www.fs.usda.gov/ouachita"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free dispersed primitive camping on national forest pullouts along Kiamichi Spine Road / FS 6000. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Kiamichi River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel mountain forest road", "road_conditions": "Graded gravel Forest Service road along mountain ridge; smooth when dry.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 2, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low to Moderate on Kiamichi mountain ridge", "distance_from_tower_corridor_miles": 6.5, "cellular_internet_dependable": True},
    "amenities": ["Kiamichi Mountain Ridge Views", "Ouachita Pine Forest Canopy", "Kiamichi River Access", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Talihina, OK", "distance_miles": 12.0, "services_available": ["Grocery Store", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush mountain spring (62-74°F).", "summer": "Warm summer (85-92°F) with pine shade.", "fall": "Crisp Talimena Drive autumn foliage.", "winter": "Cool winter (38-50°F)."},
    "dangers_and_hazards": ["Black Bear Area", "Copperhead & Timber Rattlesnakes"],
    "acoustic_environment": {"quietness_rating": "Ouachita Mountain Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind through shortleaf pine needles", "Creek flow"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Shortleaf Pine", "Post Oak", "Sweetgum", "Dogwood"], "common_animals": ["White-tailed Deer", "Black Bear", "Wild Turkey", "Smallmouth Bass"]},
    "human_demographics_and_culture": "Choctaw Nation ancestral lands and Talimena Scenic Drive mountain heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Capital of the Choctaw Nation in Indian Territory after the 1830s Trail of Tears relocation.", "energetic_and_spiritual_features": "Dramatic East-West Ouachita mountain ridge lines overlooking pine forest valleys."},
    "nearby_hiking_trails": [{"trail_name": "Ouachita National Recreation Trail (Kiamichi Section)", "length_miles": 5.0, "difficulty": "Moderate", "features": "Pine ridge walk, Kiamichi valley overlooks, mountain stream crossings"}],
    "public_reviews_summary": "Beautiful shortleaf pine mountain basecamp near Talihina with dependable cell service.",
    "other_data": "Talimena Scenic Drive starts nearby.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "oklahoma-007",
    "name": "Point of Rocks Dispersed Area - Cimarron National Grassland",
    "state": "Kansas",
    "county": "Morton",
    "coordinates": {"latitude": 37.1412, "longitude": -101.8412, "elevation_ft": 3450.0},
    "management_agency": {"name": "U.S. Forest Service - Cimarron National Grassland", "type": "Federal", "phone": "(620) 697-4621", "website": "https://www.fs.usda.gov/psicc"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on open public grassland pullouts along Santa Fe Trail route. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Cimarron River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Bring firewood; no wood gathering on shortgrass prairie.", "safety_requirements": "Campfires strictly in metal fire pans. Extinguish cold.", "seasonal_fire_bans": "Strict USFS stage fire bans in dry spring/summer."},
    "access_and_road_conditions": {"road_type": "Graded gravel grassland road", "road_conditions": "Graded gravel access road; smooth when dry.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 2, "supply_run_pain": 4}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "4 bars 4G LTE", "att_reliability": "3-4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low - open Cimarron River valley", "distance_from_tower_corridor_miles": 7.0, "cellular_internet_dependable": True},
    "amenities": ["Santa Fe National Historic Trail Ruts", "Point of Rocks Sandstone Bluff Views", "Cimarron River Valley", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 8, "quietness_score": 10},
    "nearest_supply_towns": [{"town_name": "Elkhart, KS", "distance_miles": 12.0, "services_available": ["Grocery Store", "Gas Stations", "Hardware", "Diner"]}],
    "seasonal_weather_effects": {"spring": "High winds spring (60-72°F).", "summer": "Warm High Plains summer (88-96°F) with cool nights.", "fall": "Crisp dry autumn days.", "winter": "Cold windy winter (25-40°F)."},
    "dangers_and_hazards": ["High Plains Prairie Winds", "Severe Thunderstorms", "Dust Storms"],
    "acoustic_environment": {"quietness_rating": "High Plains Prairie Silence (Quietness Score: 10/10)", "common_human_made_sounds": ["Prairie wind", "Lark sparrow songs"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Buffalograss", "Blue Grama", "Yucca", "Cottonwood"], "common_animals": ["Pronghorn Antelope", "Lesser Prairie-Chicken", "Prairie Dog", "Coyote"]},
    "human_demographics_and_culture": "Comanche and Kiowa ancestral lands and Santa Fe Trail pioneer wagon route heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Point of Rocks was a major landmark for 19th-century Santa Fe Trail wagon trains seeking water along the dry Cimarron Route.", "energetic_and_spiritual_features": "Sandstone bluffs rising 100 feet above the Cimarron River prairie valley."},
    "nearby_hiking_trails": [{"trail_name": "Santa Fe Trail Companion Trail", "length_miles": 3.0, "difficulty": "Easy", "features": "Historic 1800s wagon ruts, Point of Rocks bluff overlooks, shortgrass prairie"}],
    "public_reviews_summary": "Peaceful historic Santa Fe Trail prairie basecamp near Elkhart with strong 4G cell service.",
    "other_data": "Authentic 1800s wagon ruts preserved.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "oklahoma-008",
    "name": "McGee Creek Primitive Area - McGee Creek State Park & WMA",
    "state": "Oklahoma",
    "county": "Atoka",
    "coordinates": {"latitude": 34.3512, "longitude": -95.8412, "elevation_ft": 650.0},
    "management_agency": {"name": "Oklahoma Department of Wildlife Conservation (ODWC)", "type": "State", "phone": "(580) 889-3754", "website": "https://www.wildlifedepartment.com"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive WMA dispersed camping with valid OK hunting/fishing or conservation land pass)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on designated public WMA pullouts outside state park fee area. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from McGee Creek Lake. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to state fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel WMA access road", "road_conditions": "Graded gravel access road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low to Moderate around lake coves", "distance_from_tower_corridor_miles": 7.0, "cellular_internet_dependable": True},
    "amenities": ["McGee Creek Reservoir Shoreline", "Trophy Bass Fishing", "McGee Creek Bugaboo Canyon Trail Access", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Atoka, OK", "distance_miles": 14.0, "services_available": ["Grocery Store", "Hospital", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush green lake spring (62-74°F).", "summer": "Warm summer (85-92°F) with lake swimming.", "fall": "Crisp autumn fishing days.", "winter": "Cool winter (38-50°F)."},
    "dangers_and_hazards": ["Copperhead & Cottonmouth Snakes", "Lake Water Hazards"],
    "acoustic_environment": {"quietness_rating": "Lake Cove Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["McGee Creek lake wave lap", "Pine wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Shortleaf Pine", "Post Oak", "Hickory", "Dogwood"], "common_animals": ["Large-mouth Bass", "White-tailed Deer", "Wild Turkey", "Bald Eagle"]},
    "human_demographics_and_culture": "Choctaw Nation ancestral lands and Oklahoma trophy bass fishing culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "8,900-acre natural bugaboo canyon wilderness zone surrounding McGee Creek reservoir.", "energetic_and_spiritual_features": "Quiet oak and pine forest hills descending into clear lake coves."},
    "nearby_hiking_trails": [{"trail_name": "McGee Creek Bugaboo Canyon Trail", "length_miles": 4.0, "difficulty": "Easy to Moderate", "features": "Lake shoreline, rocky canyon overlooks, pine-hardwood canopy"}],
    "public_reviews_summary": "Quiet trophy bass lake camping near Atoka with great hiking trails and dependable cell service.",
    "other_data": "Conservation land pass or hunting/fishing license required.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "oklahoma-009",
    "name": "Honobia Creek Dispersed Area - Honobia Creek WMA",
    "state": "Oklahoma",
    "county": "Pushmataha",
    "coordinates": {"latitude": 34.5812, "longitude": -95.1412, "elevation_ft": 950.0},
    "management_agency": {"name": "Oklahoma Department of Wildlife Conservation (ODWC)", "type": "State", "phone": "(405) 521-3851", "website": "https://www.wildlifedepartment.com"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive WMA dispersed camping with valid OK hunting/fishing or Honobia land pass)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free primitive dispersed camping on public WMA pullouts along forest roads. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Little River / streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to state fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel WMA roads; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 2, "road_terrain_difficulty": 2, "supply_run_pain": 4}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low to Moderate on mountain forest pullouts", "distance_from_tower_corridor_miles": 7.5, "cellular_internet_dependable": True},
    "amenities": ["Little River Fly Fishing", "Kiamichi Mountain Foothills", "Pine Forest Shade", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Antlers / Clayton, OK", "distance_miles": 16.0, "services_available": ["Grocery Store", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush mountain spring (62-74°F).", "summer": "Warm summer (85-92°F) with stream pools.", "fall": "Crisp autumn foliage.", "winter": "Cool winter (38-50°F)."},
    "dangers_and_hazards": ["Black Bear Habitat", "Copperhead Snakes"],
    "acoustic_environment": {"quietness_rating": "Kiamichi Foothills Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Little River stream flow", "Pine wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Shortleaf Pine", "Loblolly Pine", "White Oak", "Dogwood"], "common_animals": ["White-tailed Deer", "Black Bear", "Wild Turkey", "Smallmouth Bass"]},
    "human_demographics_and_culture": "Choctaw Nation ancestral lands and Kiamichi mountain timber & Sasquatch folklore culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Honobia is famous in regional folklore as the heart of southeastern Oklahoma's Bigfoot / Sasquatch legend country.", "energetic_and_spiritual_features": "Dense shortleaf pine forest hills rolling down to the Little River."},
    "nearby_hiking_trails": [{"trail_name": "Little River Trail", "length_miles": 3.5, "difficulty": "Easy to Moderate", "features": "Stream side walking, shortleaf pine forest, smallmouth bass pools"}],
    "public_reviews_summary": "Peaceful pine mountain stream basecamp near Antlers with solid cell service and Bigfoot folklore.",
    "other_data": "Honobia Bigfoot Festival held nearby annually.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "oklahoma-010",
    "name": "Wichita Mountains BLM Dispersed Area",
    "state": "Oklahoma",
    "county": "Comanche",
    "coordinates": {"latitude": 34.7812, "longitude": -98.6412, "elevation_ft": 1650.0},
    "management_agency": {"name": "Bureau of Land Management (BLM) / USFWS", "type": "Federal", "phone": "(580) 429-3222", "website": "https://www.blm.gov/oklahoma"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive BLM dispersed camping outside wildlife refuge boundary)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free primitive dispersed camping on public BLM lands surrounding the Wichita Mountains Wildlife Refuge. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from dry washes. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Bring firewood; no wood gathering in granite hills.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to BLM stage fire bans."},
    "access_and_road_conditions": {"road_type": "Paved highway to gravel dirt pullouts", "road_conditions": "Paved OK-49 with smooth gravel side pullouts.", "vehicle_recommendation": "Accessible by all low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low - open granite prairie plain", "distance_from_tower_corridor_miles": 4.5, "cellular_internet_dependable": True},
    "amenities": ["Ancient Granite Mountain Peak Views", "Bison & Longhorn Viewing Proximity", "Mount Scott Proximity", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 8, "distance_to_gym_score": 6, "terrain_score": 10, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Medicine Park / Lawton, OK", "distance_miles": 10.0, "services_available": ["Full City Services", "Hospital", "Walmart", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush prairie spring (62-74°F).", "summer": "Warm summer (88-95°F) with prairie breezes.", "fall": "Crisp clear autumn days.", "winter": "Cool winter (38-50°F)."},
    "dangers_and_hazards": ["Bison & Longhorn Distance Rules (Stay 50 yds away)", "Rattlesnakes"],
    "acoustic_environment": {"quietness_rating": "Granite Prairie Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Prairie wind over granite domes", "Elk bugles in fall"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Post Oak", "Blackjack Oak", "Little Bluestem", "Prickly Pear"], "common_animals": ["American Bison", "Texas Longhorn", "Rocky Mountain Elk", "Prairie Dog", "Collared Lizard"]},
    "human_demographics_and_culture": "Comanche and Kiowa ancestral lands and Medicine Park granite cobblestone resort culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "500-million-year-old pink granite mountain peaks rising out of the mixed-grass prairie, sacred to Comanche and Kiowa nations.", "energetic_and_spiritual_features": "Massive weathered pink granite boulders framing rolling bison prairies."},
    "nearby_hiking_trails": [{"trail_name": "Forty Foot Hole & Kite Trail", "length_miles": 3.0, "difficulty": "Moderate", "features": "Granite gorge, clear stream waterfalls, bison viewing, bouldering"}],
    "public_reviews_summary": "Spectacular pink granite mountain views near Medicine Park with wild bison herds and blazing 5G cell service.",
    "other_data": "10 minutes from Medicine Park cobblestone resort.",
    "last_updated": "2026-09-12"
  }
])
save_state(ok, ok_path)
print("Updated Oklahoma -> 10 sites.")

# 2. Kansas (+5 sites -> 10 total)
ks, ks_path = load_state("kansas")
ks.extend([
  {
    "id": "kansas-006",
    "name": "Fall River Dispersed Area - Fall River Wildlife Area",
    "state": "Kansas",
    "county": "Greenwood",
    "coordinates": {"latitude": 37.6123, "longitude": -96.0812, "elevation_ft": 920.0},
    "management_agency": {"name": "Kansas Department of Wildlife and Parks (KDWP)", "type": "State", "phone": "(620) 658-4445", "website": "https://ksoutdoors.com"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive state WMA dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on designated public Wildlife Management Area pullouts. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Fall River Lake. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to state fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel WMA access road", "road_conditions": "Graded gravel access roads off US-400; smooth when dry.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low - open Flint Hills reservoir shoreline", "distance_from_tower_corridor_miles": 5.5, "cellular_internet_dependable": True},
    "amenities": ["Fall River Reservoir Views", "Flint Hills Sandstone Bluffs", "Crappie & Catfish Fishing", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 5, "terrain_score": 8, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Eureka / Fredonia, KS", "distance_miles": 14.0, "services_available": ["Grocery Store", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush prairie spring (62-74°F).", "summer": "Warm summer (85-92°F) with lake swimming.", "fall": "Crisp autumn foliage.", "winter": "Cool winter (32-45°F)."},
    "dangers_and_hazards": ["High Prairie Winds", "Severe Summer Thunderstorms"],
    "acoustic_environment": {"quietness_rating": "Reservoir Prairie Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Fall River lake wave lap", "Meadowlark calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Post Oak", "Blackjack Oak", "Big Bluestem", "Switchgrass"], "common_animals": ["White-tailed Deer", "Wild Turkey", "Crappie", "Bald Eagle"]},
    "human_demographics_and_culture": "Osage ancestral lands and Kansas Flint Hills ranching heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Flint Hills tallgrass prairie transition zone featuring oak savannah and sandstone bluff lake coves.", "energetic_and_spiritual_features": "Quiet reservoir waters surrounded by rolling Flint Hills tallgrass prairie."},
    "nearby_hiking_trails": [{"trail_name": "Fall River Overlook Trail", "length_miles": 3.0, "difficulty": "Easy to Moderate", "features": "Sandstone bluffs, lake vistas, tallgrass prairie swales"}],
    "public_reviews_summary": "Peaceful lake side basecamp on the edge of the Flint Hills with fast 5G cell service.",
    "other_data": "Great crappie fishing.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "kansas-007",
    "name": "Tuttle Creek Dispersed Area - Tuttle Creek WMA",
    "state": "Kansas",
    "county": "Riley",
    "coordinates": {"latitude": 39.3512, "longitude": -96.6412, "elevation_ft": 1100.0},
    "management_agency": {"name": "Kansas Department of Wildlife and Parks (KDWP)", "type": "State", "phone": "(785) 539-7941", "website": "https://ksoutdoors.com"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive state WMA dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on designated public WMA pullouts along Tuttle Creek reservoir arms. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Tuttle Creek Lake. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to state fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel access road", "road_conditions": "Graded gravel access roads off US-77; smooth when dry.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low along open reservoir shoreline", "distance_from_tower_corridor_miles": 4.5, "cellular_internet_dependable": True},
    "amenities": ["Tuttle Creek Reservoir Shoreline", "Flint Hills Prairie Proximity", "Boating & Kayaking", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 8, "distance_to_gym_score": 7, "terrain_score": 8, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Manhattan, KS", "distance_miles": 12.0, "services_available": ["KSU Campus", "Full City Services", "Hospital", "Target", "Walmart", "Gyms"]}],
    "seasonal_weather_effects": {"spring": "Lush Flint Hills spring (60-72°F).", "summer": "Warm summer (85-92°F) with lake breezes.", "fall": "Crisp autumn foliage.", "winter": "Cold winter (25-38°F)."},
    "dangers_and_hazards": ["High Prairie Winds", "Severe Summer Thunderstorms"],
    "acoustic_environment": {"quietness_rating": "Reservoir Shoreline Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Tuttle Creek lake wave lap", "Meadowlark calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Cottonwood", "Bur Oak", "Big Bluestem", "Switchgrass"], "common_animals": ["White-tailed Deer", "Bald Eagle", "Catfish", "Wild Turkey"]},
    "human_demographics_and_culture": "Kaw (Kansa) ancestral lands and Kansas State University & Flint Hills ranching culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "12,000-acre reservoir situated in the heart of the Kansas Flint Hills tallgrass prairie region.", "energetic_and_spiritual_features": "Vast prairie reservoir water framing rolling Flint Hills horizons."},
    "nearby_hiking_trails": [{"trail_name": "Fancy Creek Mountain Bike & Hike Trail", "length_miles": 6.0, "difficulty": "Moderate", "features": "Flint Hills limestone bluffs, oak woodlands, lake vistas"}],
    "public_reviews_summary": "Top choice free basecamp just 15 minutes from Manhattan with blazing 5G cell service.",
    "other_data": "12 miles north of Kansas State University.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "kansas-008",
    "name": "Kaw Dispersed Area - Kaw Wildlife Area",
    "state": "Kansas",
    "county": "Cowley",
    "coordinates": {"latitude": 37.0812, "longitude": -96.9412, "elevation_ft": 1050.0},
    "management_agency": {"name": "Kansas Department of Wildlife and Parks (KDWP)", "type": "State", "phone": "(620) 442-4121", "website": "https://ksoutdoors.com"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive state WMA dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on designated public WMA pullouts along Arkansas River corridor. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Arkansas River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to state fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel access road", "road_conditions": "Graded gravel access roads off US-77; smooth when dry.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low along Arkansas River valley", "distance_from_tower_corridor_miles": 6.0, "cellular_internet_dependable": True},
    "amenities": ["Arkansas River Canoeing & Fishing", "Hardwood Bottomland Canopy", "Kaw Lake Proximity", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 5, "terrain_score": 8, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Arkansas City, KS", "distance_miles": 8.0, "services_available": ["Grocery Store", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush river valley spring (62-74°F).", "summer": "Warm summer (85-92°F) with river shade.", "fall": "Crisp autumn foliage.", "winter": "Cool winter (30-42°F)."},
    "dangers_and_hazards": ["High Spring River Water", "Ticks in Spring"],
    "acoustic_environment": {"quietness_rating": "River Bottomland Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Arkansas River water flow", "Cottonwood wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Cottonwood", "Sycamore", "Bur Oak", "Black Walnut"], "common_animals": ["White-tailed Deer", "Wild Turkey", "Channel Catfish", "Bald Eagle"]},
    "human_demographics_and_culture": "Kansa (Kaw) and Osage ancestral lands and Arkansas River valley pioneer heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Historic Arkansas River trade route used by Native American nations for thousands of years.", "energetic_and_spiritual_features": "Quiet cottonwood bottomland forest along the broad Arkansas River."},
    "nearby_hiking_trails": [{"trail_name": "Kaw River Bottoms Trail", "length_miles": 3.0, "difficulty": "Easy", "features": "Arkansas River sandbars, cottonwood canopy, eagle watching"}],
    "public_reviews_summary": "Peaceful river side camping near Arkansas City with good cell service and river fishing.",
    "other_data": "8 miles from Oklahoma border.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "kansas-009",
    "name": "Marais des Cygnes Dispersed Area - WMA",
    "state": "Kansas",
    "county": "Linn",
    "coordinates": {"latitude": 38.2812, "longitude": -94.6412, "elevation_ft": 820.0},
    "management_agency": {"name": "Kansas Department of Wildlife and Parks (KDWP)", "type": "State", "phone": "(913) 352-8941", "website": "https://ksoutdoors.com"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive state WMA dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free primitive dispersed camping on designated public WMA pullouts. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from river and marshes. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to state fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel access road", "road_conditions": "Graded gravel access roads off US-69; smooth when dry.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low along US-69 corridor", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["Hardwood Bottomland Forest", "Waterfowl Migration Sanctuary", "Historic Massacre Site Nearby", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 5, "terrain_score": 8, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Pleasanton / La Cygne, KS", "distance_miles": 10.0, "services_available": ["Grocery Store", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush spring green (60-72°F) with waterfowl.", "summer": "Warm summer (85-92°F) with forest shade.", "fall": "Spectacular autumn colors & bird migration.", "winter": "Cool winter (30-42°F)."},
    "dangers_and_hazards": ["Spring Floodplain Water", "Ticks in Spring"],
    "acoustic_environment": {"quietness_rating": "Marsh & Bottomland Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Duck and goose waterfowl calls", "River flow"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Bur Oak", "Shellbark Hickory", "Pecan", "River Birch"], "common_animals": ["Mallard", "Snow Goose", "White-tailed Deer", "Bald Eagle", "Beaver"]},
    "human_demographics_and_culture": "Osage ancestral lands and Bleeding Kansas 1858 historic massacre site heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "French name meaning 'Marsh of the Swans', protecting 7,500 acres of ancient hardwood bottomland wetlands.", "energetic_and_spiritual_features": "Quiet hardwood bottomland forest echoing with spring waterfowl migration calls."},
    "nearby_hiking_trails": [{"trail_name": "Marais des Cygnes Wildlife Trail", "length_miles": 3.5, "difficulty": "Easy", "features": "Hardwood bottomlands, marsh boardwalks, waterfowl viewing blinds"}],
    "public_reviews_summary": "World-class waterfowl watching and quiet hardwood forest camping under an hour from Kansas City with fast 5G cell service.",
    "other_data": "Historic Bleeding Kansas site nearby.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "kansas-010",
    "name": "Cedar Bluff Dispersed Area - Cedar Bluff WMA",
    "state": "Kansas",
    "county": "Trego",
    "coordinates": {"latitude": 38.7812, "longitude": -99.7812, "elevation_ft": 2150.0},
    "management_agency": {"name": "Kansas Department of Wildlife and Parks (KDWP)", "type": "State", "phone": "(785) 726-3212", "website": "https://ksoutdoors.com"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive state WMA dispersed camping outside state park fee area)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on designated public WMA pullouts along reservoir shoreline outside state park fee boundary. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Cedar Bluff Reservoir. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to state fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel access road", "road_conditions": "Graded gravel access roads off K-147; smooth when dry.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "4 bars 4G LTE", "att_reliability": "3-4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low along open reservoir shoreline", "distance_from_tower_corridor_miles": 6.5, "cellular_internet_dependable": True},
    "amenities": ["Limestone Bluff Reservoir Overlook Views", "Walleye & Bass Fishing", "Dark Sky Astronomy", "Boating Access"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "WaKeeney / Ellis, KS", "distance_miles": 16.0, "services_available": ["Grocery Store", "Gas Stations", "Hardware", "Diners", "I-70 Access"]}],
    "seasonal_weather_effects": {"spring": "Breezy High Plains spring (58-70°F).", "summer": "Warm summer (85-92°F) with water breezes.", "fall": "Crisp autumn fishing days.", "winter": "Cold windy winter (20-35°F)."},
    "dangers_and_hazards": ["High Plains Prairie Winds", "Severe Thunderstorms"],
    "acoustic_environment": {"quietness_rating": "Limestone Bluff Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Cedar Bluff reservoir wave lap", "Prairie wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Eastern Red Cedar", "Cottonwood", "Little Bluestem", "Yucca"], "common_animals": ["Mule Deer", "Pronghorn Antelope", "Walleye", "White Pelican", "Coyote"]},
    "human_demographics_and_culture": "Cheyenne and Arapaho ancestral lands and Smoky Hill Trail pioneer heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Towering 100-foot white limestone bluffs carving the Smoky Hill River reservoir basin.", "energetic_and_spiritual_features": "Striking white limestone bluffs standing over blue High Plains reservoir waters."},
    "nearby_hiking_trails": [{"trail_name": "Cedar Bluff Limestone Rim Trail", "length_miles": 3.0, "difficulty": "Easy to Moderate", "features": "Limestone bluff edge overlooks, reservoir vistas, cedar thickets"}],
    "public_reviews_summary": "Stunning white limestone bluff reservoir basecamp just 20 minutes from I-70 with strong cell service.",
    "other_data": "16 miles south of I-70.",
    "last_updated": "2026-09-12"
  }
])
save_state(ks, ks_path)
print("Updated Kansas -> 10 sites.")

# 3. Nebraska (+5 sites -> 10 total)
ne, ne_path = load_state("nebraska")
ne.extend([
  {
    "id": "nebraska-006",
    "name": "Toadstool Dispersed Area - Oglala National Grassland",
    "state": "Nebraska",
    "county": "Sioux",
    "coordinates": {"latitude": 42.8512, "longitude": -103.6412, "elevation_ft": 3600.0},
    "management_agency": {"name": "U.S. Forest Service - Pine Ridge Ranger District", "type": "Federal", "phone": "(308) 432-0300", "website": "https://www.fs.usda.gov/nebraska"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside park campground loop)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on open public grassland pullouts along FS Road 902. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from badland washes. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Bring firewood; no wood gathering on badlands.", "safety_requirements": "Campfires strictly in metal fire pans. Extinguish cold.", "seasonal_fire_bans": "Strict USFS stage fire bans in dry summer."},
    "access_and_road_conditions": {"road_type": "Graded gravel and dirt grassland road", "road_conditions": "Graded gravel access road; slick clay gumbo when wet.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars when dry.", "scores": {"road_grade": 3, "road_terrain_difficulty": 4, "supply_run_pain": 6}},
    "nomad_connectivity_rating": {"overall_rating": "Fair (3/5 Stars)", "verizon_reliability": "2-3 bars 4G LTE", "att_reliability": "2 bars 4G LTE", "tmobile_reliability": "1-2 bars 4G LTE", "terrain_obstruction_risk": "Moderate near badland hoodoo formations", "distance_from_tower_corridor_miles": 18.0, "cellular_internet_dependable": True},
    "amenities": ["Alien Badland Hoodoo Rock Formations", "Oglala Grassland Panoramas", "Fossil Beds Proximity", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 4, "distance_to_library_score": 4, "distance_to_gym_score": 2, "terrain_score": 10, "quietness_score": 10},
    "nearest_supply_towns": [{"town_name": "Crawford / Chadron, NE", "distance_miles": 18.0, "services_available": ["Grocery Store", "Hospital", "Gas Stations", "Hardware", "CSC Campus"]}],
    "seasonal_weather_effects": {"spring": "Breezy spring (52-65°F).", "summer": "Warm High Plains summer (85-94°F) with bright sun.", "fall": "Crisp dry autumn days.", "winter": "Cold windy winter (15-32°F)."},
    "dangers_and_hazards": ["Gumbo Clay Mud when Wet", "High Prairie Winds", "Severe Thunderstorms"],
    "acoustic_environment": {"quietness_rating": "Otherworldly Badland Silence (Quietness Score: 10/10)", "common_human_made_sounds": ["Wind through badland hoodoos", "Coyote calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Western Wheatgrass", "Buffalograss", "Yucca", "Prickly Pear"], "common_animals": ["Pronghorn Antelope", "Horned Lizard", "Golden Eagle", "Mule Deer"]},
    "human_demographics_and_culture": "Oglala Lakota sacred lands and High Plains paleontology & ranching culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Famous mushroom-shaped badland hoodoo rock formations containing 30-million-year-old Oligocene mammal fossils.", "energetic_and_spiritual_features": "Otherworldly badland hoodoo landscape set against open shortgrass prairie."},
    "nearby_hiking_trails": [{"trail_name": "Toadstool Geologic Park Loop Trail", "length_miles": 1.5, "difficulty": "Easy to Moderate", "features": "Mushroom badland hoodoos, fossil trackways, clay badland canyon"}],
    "public_reviews_summary": "Surreal badland hoodoo landscape like another planet with usable 4G cell service.",
    "other_data": "Do not collect fossils (protected federal land).",
    "last_updated": "2026-09-12"
  },
  {
    "id": "nebraska-007",
    "name": "McKelvie Dispersed Area - Samuel R. McKelvie NF",
    "state": "Nebraska",
    "county": "Cherry",
    "coordinates": {"latitude": 42.7123, "longitude": -101.0812, "elevation_ft": 3100.0},
    "management_agency": {"name": "U.S. Forest Service - Samuel R. McKelvie National Forest", "type": "Federal", "phone": "(402) 376-1901", "website": "https://www.fs.usda.gov/nebraska"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on public grassland pullouts along FS roads across 116,000 acres of Sandhills. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Niobrara River / blowout swales. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires strictly in metal fire pans. Extinguish cold.", "seasonal_fire_bans": "Strict USFS stage fire bans in dry prairie."},
    "access_and_road_conditions": {"road_type": "Graded sand and gravel forest road", "road_conditions": "Graded sand forest roads off NE-97; soft sand on side tracks.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars on main gravel tracks.", "scores": {"road_grade": 2, "road_terrain_difficulty": 3, "supply_run_pain": 5}},
    "nomad_connectivity_rating": {"overall_rating": "Fair to Good (3.5/5 Stars)", "verizon_reliability": "3 bars 4G LTE", "att_reliability": "3 bars 4G LTE", "tmobile_reliability": "2 bars 4G LTE", "terrain_obstruction_risk": "Low - rolling Sandhills prairie", "distance_from_tower_corridor_miles": 14.0, "cellular_internet_dependable": True},
    "amenities": ["Nebraska Sandhills Rolling Dunes", "Hand-Planted Ponderosa Groves", "Niobrara River Proximity", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 5, "distance_to_library_score": 5, "distance_to_gym_score": 3, "terrain_score": 9, "quietness_score": 10},
    "nearest_supply_towns": [{"town_name": "Valentine, NE", "distance_miles": 24.0, "services_available": ["Niobrara Outfitters", "Grocery Store", "Hospital", "Gas Stations", "Hardware"]}],
    "seasonal_weather_effects": {"spring": "Breezy Sandhills spring (52-65°F).", "summer": "Warm summer (84-92°F) with cool prairie nights.", "fall": "Crisp dry autumn days.", "winter": "Cold windy winter (15-30°F)."},
    "dangers_and_hazards": ["Getting Stuck in Loose Dune Sand", "High Prairie Fire Hazard"],
    "acoustic_environment": {"quietness_rating": "Sandhills Prairie Solitude (Quietness Score: 10/10)", "common_human_made_sounds": ["Sandhills wind", "Sharp-tailed grouse calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Little Bluestem", "Sand Bluestem", "Ponderosa Pine", "Jack Pine"], "common_animals": ["Mule Deer", "Sharp-tailed Grouse", "Pronghorn", "Coyote", "Blowout Penstemon"]},
    "human_demographics_and_culture": "Lakota ancestral lands and Cherry County Sandhills cattle ranching heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Largest hand-planted national forest in America, protecting 116,000 acres of grass-stabilized sand dunes.", "energetic_and_spiritual_features": "Vast rolling green grass dunes stretching to the horizon in total solitude."},
    "nearby_hiking_trails": [{"trail_name": "McKelvie Sandhills Prairie Loop", "length_miles": 4.0, "difficulty": "Easy to Moderate", "features": "Rolling grass dunes, hand-planted pine groves, Sandhills vistas"}],
    "public_reviews_summary": "Profound Sandhills prairie solitude near Valentine with hand-planted pine groves and usable 4G cell service.",
    "other_data": "116,000 acres of open Sandhills land.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "nebraska-008",
    "name": "Bessey Dispersed Area - Nebraska National Forest",
    "state": "Nebraska",
    "county": "Thomas",
    "coordinates": {"latitude": 41.8812, "longitude": -100.2812, "elevation_ft": 2800.0},
    "management_agency": {"name": "U.S. Forest Service - Bessey Ranger District", "type": "Federal", "phone": "(308) 533-2257", "website": "https://www.fs.usda.gov/nebraska"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside main campground)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along Middle Loup River access roads. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Middle Loup River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires strictly in metal fire pans. Extinguish cold.", "seasonal_fire_bans": "Strict USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Paved highway to gravel forest roads", "road_conditions": "Paved NE-2 Scenic Byway with smooth gravel forest side turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low along Middle Loup river valley", "distance_from_tower_corridor_miles": 5.5, "cellular_internet_dependable": True},
    "amenities": ["Hand-Planted Forest in Sandhills", "Middle Loup River Tubing & Canoeing", "Bessey Nursery Historic Site", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 5, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Halsey / Broken Bow, NE", "distance_miles": 12.0, "services_available": ["Grocery Store", "Hospital", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush Sandhills spring (55-68°F).", "summer": "Warm summer (85-92°F) with river tubing.", "fall": "Crisp dry autumn days.", "winter": "Cold windy winter (18-32°F)."},
    "dangers_and_hazards": ["High Sandhills Wildfire Hazard", "River Water Currents"],
    "acoustic_environment": {"quietness_rating": "Hand-Planted Forest Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Middle Loup River flow", "Pine wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Ponderosa Pine", "Jack Pine", "Eastern Red Cedar", "Sand Bluestem"], "common_animals": ["Mule Deer", "White-tailed Deer", "Wild Turkey", "Porcupine"]},
    "human_demographics_and_culture": "Lakota ancestral lands and historic 1902 Charles E. Bessey forest planting heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Oldest tree nursery in the US Forest Service system, founded in 1902 to reforest the Great Plains.", "energetic_and_spiritual_features": "90,000-acre hand-planted pine forest oasis rising directly out of the rolling Sandhills prairie."},
    "nearby_hiking_trails": [{"trail_name": "Scott Lookout Tower Trail", "length_miles": 3.0, "difficulty": "Easy to Moderate", "features": "Historic fire lookout tower, hand-planted forest canopy, 360-degree Sandhills views"}],
    "public_reviews_summary": "Incredible hand-planted forest oasis in the Sandhills near Halsey with river tubing and strong cell service.",
    "other_data": "Scott Lookout Tower offers 360-degree views.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "nebraska-009",
    "name": "Pine Ridge Dispersed Area - Pine Ridge National Rec Area",
    "state": "Nebraska",
    "county": "Dawes",
    "coordinates": {"latitude": 42.7123, "longitude": -103.0812, "elevation_ft": 4200.0},
    "management_agency": {"name": "U.S. Forest Service - Pine Ridge Ranger District", "type": "Federal", "phone": "(308) 432-0300", "website": "https://www.fs.usda.gov/nebraska"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along Table Road / FS roads across 6,600-acre recreation area. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from mountain streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires strictly in metal fire pans. Extinguish cold.", "seasonal_fire_bans": "Strict USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 2, "road_terrain_difficulty": 2, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low to Moderate on Pine Ridge plateau", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["Ponderosa Pine Ridge Scenery", "Chadron State Park Proximity", "Pine Ridge Trail Access", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 8, "distance_to_gym_score": 6, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Chadron, NE", "distance_miles": 10.0, "services_available": ["CSC Campus", "Full Groceries", "Hospital", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush pine ridge spring (55-68°F).", "summer": "Warm sunny summer (82-90°F) with cool pine nights.", "fall": "Crisp autumn foliage.", "winter": "Snowy winter (18-32°F)."},
    "dangers_and_hazards": ["Summer Wildfire Risk in Pines", "Rattlesnakes"],
    "acoustic_environment": {"quietness_rating": "Pine Ridge Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind through ponderosa needles", "Mountain bluebird calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Ponderosa Pine", "Narrowleaf Cottonwood", "Chokecherry", "Yucca"], "common_animals": ["Bighorn Sheep", "Elk", "Mule Deer", "Wild Turkey", "Golden Eagle"]},
    "human_demographics_and_culture": "Oglala Lakota ancestral lands and Chadron State College & Pine Ridge pioneer heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Ponderosa pine escarpment rising 1,000 feet above the surrounding High Plains prairie.", "energetic_and_spiritual_features": "Fragrant ponderosa pine bluffs commanding views across northern Nebraska."},
    "nearby_hiking_trails": [{"trail_name": "Pine Ridge National Recreation Trail", "length_miles": 6.0, "difficulty": "Moderate", "features": "Ponderosa pine ridges, bighorn sheep habitat, Butte views"}],
    "public_reviews_summary": "Top choice free ponderosa pine ridge camping near Chadron with blazing 5G cell service.",
    "other_data": "Bighorn sheep reintroduction area.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "nebraska-010",
    "name": "Harlan County WMA Dispersed Area",
    "state": "Nebraska",
    "county": "Harlan",
    "coordinates": {"latitude": 40.0812, "longitude": -99.2812, "elevation_ft": 1950.0},
    "management_agency": {"name": "Nebraska Game and Parks Commission / USACE", "type": "State", "phone": "(308) 799-2105", "website": "https://outdoornebraska.gov"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive state WMA dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on designated public WMA pullouts along Harlan County Reservoir. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from high water line. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to state fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel access road", "road_conditions": "Graded gravel access roads off US-136; smooth when dry.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low along reservoir shoreline", "distance_from_tower_corridor_miles": 4.5, "cellular_internet_dependable": True},
    "amenities": ["13,000-Acre Reservoir Shoreline", "Walleye & White Bass Fishing", "White Pelican Watching", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 7, "distance_to_gym_score": 5, "terrain_score": 8, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Alma, NE", "distance_miles": 8.0, "services_available": ["Grocery Store", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Breezy spring (58-70°F).", "summer": "Warm summer (85-92°F) with lake breezes.", "fall": "Crisp dry autumn fishing days.", "winter": "Cold windy winter (20-35°F)."},
    "dangers_and_hazards": ["High Prairie Winds", "Severe Thunderstorms"],
    "acoustic_environment": {"quietness_rating": "Reservoir Water Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Harlan reservoir wave lap", "White pelican calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Cottonwood", "Willow", "Big Bluestem", "Switchgrass"], "common_animals": ["Walleye", "White Bass", "White Pelican", "Bald Eagle", "White-tailed Deer"]},
    "human_demographics_and_culture": "Pawnee ancestral lands and Republican River valley reservoir culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Second largest lake in Nebraska protecting 13,000 acres of blue water along the Republican River valley.", "energetic_and_spiritual_features": "Vast prairie reservoir water reflecting southern Nebraska sunsets."},
    "nearby_hiking_trails": [{"trail_name": "Harlan Reservoir Shoreline Trail", "length_miles": 3.5, "difficulty": "Easy", "features": "Reservoir shore walking, pelican watching, cottonwood groves"}],
    "public_reviews_summary": "Uncrowded lake side camping near Alma with world-class walleye fishing and blazing 5G cell service.",
    "other_data": "Second largest lake in Nebraska.",
    "last_updated": "2026-09-12"
  }
])
save_state(ne, ne_path)
print("Updated Nebraska -> 10 sites.")

# 4. Iowa (+5 sites -> 10 total)
ia, ia_path = load_state("iowa")
ia.extend([
  {
    "id": "iowa-006",
    "name": "Paint Creek Dispersed Area - Yellow River State Forest",
    "state": "Iowa",
    "county": "Allamakee",
    "coordinates": {"latitude": 43.1812, "longitude": -91.2812, "elevation_ft": 850.0},
    "management_agency": {"name": "Iowa Department of Natural Resources (DNR)", "type": "State", "phone": "(563) 586-2254", "website": "https://www.iowadnr.gov"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive state forest dispersed camping outside fee loops)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on state forest pullouts along Paint Creek Road. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Paint Creek / Yellow River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to DNR fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel forest roads; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 2, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low to Moderate in Driftless valley", "distance_from_tower_corridor_miles": 6.5, "cellular_internet_dependable": True},
    "amenities": ["Driftless Region Sandstone Bluffs", "Trout Stream Fishing", "Hardwood Forest Canopy", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 5, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Waukon / Harpers Ferry, IA", "distance_miles": 12.0, "services_available": ["Grocery Store", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush Driftless spring (58-70°F).", "summer": "Warm pleasant summer (78-86°F) with trout fishing.", "fall": "Spectacular Driftless autumn foliage.", "winter": "Cool winter (20-32°F) with snow."},
    "dangers_and_hazards": ["Flash Floods in Creek Valley", "Timber Rattlesnakes"],
    "acoustic_environment": {"quietness_rating": "Driftless Valley Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Paint Creek trout stream flow", "Songbird calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Sugar Maple", "Red Oak", "White Pine", "Wild Ginger"], "common_animals": ["Trout", "White-tailed Deer", "Wild Turkey", "Bald Eagle"]},
    "human_demographics_and_culture": "Ioway and Ho-Chunk ancestral lands and Driftless Area unglaciated geology culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Located in Iowa's unglaciated Driftless Area, featuring 300-foot limestone and sandstone river bluffs untouched by ice age glaciers.", "energetic_and_spiritual_features": "Deep unglaciated hardwood forest valleys with cold spring-fed trout streams."},
    "nearby_hiking_trails": [{"trail_name": "Yellow River Backcountry Backpacking Trail", "length_miles": 5.0, "difficulty": "Moderate to Strenuous", "features": "Driftless bluffs, Paint Creek overlooks, hardwood canopy"}],
    "public_reviews_summary": "Iowa's premier mountain-like Driftless Area forest camping with cold trout streams and reliable cell service.",
    "other_data": "Driftless region unglaciated landscape.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "iowa-007",
    "name": "Stephens Dispersed Area - Stephens State Forest",
    "state": "Iowa",
    "county": "Lucas",
    "coordinates": {"latitude": 40.9812, "longitude": -93.3412, "elevation_ft": 980.0},
    "management_agency": {"name": "Iowa Department of Natural Resources (DNR)", "type": "State", "phone": "(641) 774-4559", "website": "https://www.iowadnr.gov"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive state forest dispersed camping outside pack-in fee loops)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free primitive dispersed camping allowed on state forest pullouts along forest roads. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to DNR fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel forest roads; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low under oak-hickory canopy", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["Oak-Hickory Forest Canopy", "Multi-Use Trail System", "Pine Plantation Groves", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 8, "distance_to_gym_score": 6, "terrain_score": 8, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Chariton, IA", "distance_miles": 10.0, "services_available": ["Grocery Store", "Hospital", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush hardwood spring (60-72°F).", "summer": "Warm summer (82-88°F) with forest shade.", "fall": "Crisp autumn foliage.", "winter": "Cool winter (22-35°F)."},
    "dangers_and_hazards": ["Ticks in Spring Brush"],
    "acoustic_environment": {"quietness_rating": "Oak Forest Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Wind through oak canopy", "Songbird calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["White Oak", "Red Oak", "Shagbark Hickory", "White Pine"], "common_animals": ["White-tailed Deer", "Wild Turkey", "Barred Owl", "Red Fox"]},
    "human_demographics_and_culture": "Ioway and Sac & Fox ancestral lands and Lucas County timber & agriculture heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Largest state forest in Iowa, protecting 15,000 acres of oak-hickory hills and pine plantations.", "energetic_and_spiritual_features": "Quiet rolling oak forest hills offering peaceful Midwest woodland solitude."},
    "nearby_hiking_trails": [{"trail_name": "Stephens Forest Woodmaster Trail", "length_miles": 4.5, "difficulty": "Easy to Moderate", "features": "Oak-hickory forest, pine plantations, ravine bridges"}],
    "public_reviews_summary": "Iowa's largest state forest basecamp near Chariton with extensive trails and blazing 5G cell service.",
    "other_data": "15,000 acres of state forest land.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "iowa-008",
    "name": "Shimek Dispersed Area - Shimek State Forest",
    "state": "Iowa",
    "county": "Lee",
    "coordinates": {"latitude": 40.6812, "longitude": -91.6412, "elevation_ft": 720.0},
    "management_agency": {"name": "Iowa Department of Natural Resources (DNR)", "type": "State", "phone": "(319) 878-3817", "website": "https://www.iowadnr.gov"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive state forest dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on state forest pullouts along forest roads. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Des Moines River / ponds. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to DNR fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel forest roads; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low under oak-pine canopy", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["Des Moines River Proximity", "Pine & Oak Shade", "Equestrian & Hike Trails", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 7, "distance_to_gym_score": 6, "terrain_score": 8, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Farmington / Fort Madison, IA", "distance_miles": 10.0, "services_available": ["Grocery Store", "Hospital", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush spring forest (60-72°F).", "summer": "Warm summer (82-88°F) with forest shade.", "fall": "Crisp autumn foliage.", "winter": "Cool winter (25-38°F)."},
    "dangers_and_hazards": ["Ticks in Spring Brush"],
    "acoustic_environment": {"quietness_rating": "Oak-Pine Forest Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Wind through pine canopy", "Songbird calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["White Pine", "Red Oak", "Shagbark Hickory", "Dogwood"], "common_animals": ["White-tailed Deer", "Wild Turkey", "Red Fox", "Great Horned Owl"]},
    "human_demographics_and_culture": "Sauk and Meskwaki ancestral lands and Des Moines River valley timber heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "9,000-acre state forest named after Dr. Bohumil Shimek, pioneer Iowa botanist and conservationist.", "energetic_and_spiritual_features": "Quiet oak and pine woods near the historic Des Moines River."},
    "nearby_hiking_trails": [{"trail_name": "Shimek Forest Loop Trail", "length_miles": 4.0, "difficulty": "Easy to Moderate", "features": "Pine plantations, oak-hickory ridges, ponds"}],
    "public_reviews_summary": "Peaceful Southeast Iowa forest camping near the Des Moines River with fast 5G cell service.",
    "other_data": "Named after botanist Bohumil Shimek.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "iowa-009",
    "name": "Loess Hills Dispersed Area - Loess Hills State Forest",
    "state": "Iowa",
    "county": "Monona",
    "coordinates": {"latitude": 41.9812, "longitude": -95.9412, "elevation_ft": 1250.0},
    "management_agency": {"name": "Iowa Department of Natural Resources (DNR)", "type": "State", "phone": "(712) 456-2924", "website": "https://www.iowadnr.gov"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive state forest dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on state forest pullouts along Loess Hills Scenic Byway forest roads. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from dry gullies. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to DNR fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel forest roads along ridge tops; slick loess soil when wet.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars when dry.", "scores": {"road_grade": 3, "road_terrain_difficulty": 3, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low on high Loess ridge tops", "distance_from_tower_corridor_miles": 4.5, "cellular_internet_dependable": True},
    "amenities": ["Loess Hills Ridge Top Views", "Missouri River Valley Panorama", "Native Prairie Bluffs", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 8, "distance_to_gym_score": 6, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Onawa / Pisgah, IA", "distance_miles": 10.0, "services_available": ["Grocery Store", "Gas Stations", "Hardware", "Diners", "I-29 Access"]}],
    "seasonal_weather_effects": {"spring": "Lush green prairie spring (60-72°F).", "summer": "Warm summer (84-90°F) with ridge breezes.", "fall": "Spectacular prairie & oak autumn foliage.", "winter": "Cool winter (22-35°F)."},
    "dangers_and_hazards": ["Slippery Loess Soil when Wet", "High Ridge Winds"],
    "acoustic_environment": {"quietness_rating": "Loess Ridge Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind over prairie ridges", "Meadowlark calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Bur Oak", "Little Bluestem", "Sideoats Grama", "Yucca"], "common_animals": ["White-tailed Deer", "Bobcat", "Wild Turkey", "Red-tailed Hawk"]},
    "human_demographics_and_culture": "Otoe-Missouria ancestral lands and Loess Hills wind-deposited geology culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Unique wind-deposited silt (loess) soil dunes 60 to 200 feet deep created at the end of the last ice age, found only here and in China.", "energetic_and_spiritual_features": "Dramatic steep prairie ridge bluffs overlooking the flat Missouri River valley."},
    "nearby_hiking_trails": [{"trail_name": "Preparation Canyon Ridge Trail", "length_miles": 3.5, "difficulty": "Moderate", "features": "Loess soil ridge bluffs, native prairie, Missouri River valley vistas"}],
    "public_reviews_summary": "Unbelievable ridge top prairie views overlooking the Missouri River valley with blazing 5G cell service.",
    "other_data": "Unique wind-blown silt geology.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "iowa-010",
    "name": "Preparation Canyon Dispersed Area - State Park",
    "state": "Iowa",
    "county": "Monona",
    "coordinates": {"latitude": 41.9123, "longitude": -95.8412, "elevation_ft": 1180.0},
    "management_agency": {"name": "Iowa Department of Natural Resources (DNR)", "type": "State", "phone": "(712) 456-2924", "website": "https://www.iowadnr.gov"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive state park hike-in dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Primitive hike-in dispersed camping allowed at designated remote backcountry sites. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to DNR fire bans."},
    "access_and_road_conditions": {"road_type": "Paved road to hike-in trailheads", "road_conditions": "Paved access road to smooth dirt hike-in trail parking.", "vehicle_recommendation": "Accessible by all low-clearance 2WD passenger cars.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low on Loess Ridge top", "distance_from_tower_corridor_miles": 4.5, "cellular_internet_dependable": True},
    "amenities": ["1850s Mormon Ghost Town Heritage Site", "Loess Hills Canyon Overlooks", "Hike-In Primitive Solitude", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 8, "distance_to_gym_score": 6, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Moorhead / Onawa, IA", "distance_miles": 8.0, "services_available": ["Grocery Store", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush green prairie spring (60-72°F).", "summer": "Warm summer (84-90°F) with canyon breezes.", "fall": "Spectacular autumn foliage.", "winter": "Cool winter (22-35°F)."},
    "dangers_and_hazards": ["Slippery Loess Slopes when Wet"],
    "acoustic_environment": {"quietness_rating": "Backcountry Canyon Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind through bur oak canopy", "Prairie bird calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Bur Oak", "Little Bluestem", "Leadplant", "Coneflower"], "common_animals": ["White-tailed Deer", "Wild Turkey", "Red Fox", "Coyote"]},
    "human_demographics_and_culture": "Otoe-Missouria ancestral lands and 1850s Charles B. Thompson Mormon breakaway colony history.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Site of the 1853 Mormon colony of 'Preparation' led by Charles B. Thompson before becoming a ghost town.", "energetic_and_spiritual_features": "Secluded loess canyon valley offering complete backcountry hike-in quiet."},
    "nearby_hiking_trails": [{"trail_name": "Preparation Canyon Backcountry Trail", "length_miles": 3.0, "difficulty": "Moderate", "features": "1850s ghost town site, loess canyon overlooks, bur oak forest"}],
    "public_reviews_summary": "Iowa's best primitive hike-in backcountry camping steeped in 1850s pioneer history with fast 5G cell service.",
    "other_data": "1850s Mormon settlement ghost town history.",
    "last_updated": "2026-09-12"
  }
])
save_state(ia, ia_path)
print("Updated Iowa -> 10 sites.")

# 5. Louisiana (+5 sites -> 10 total)
la, la_path = load_state("louisiana")
la.extend([
  {
    "id": "louisiana-006",
    "name": "Kisatchie Hills Dispersed Area - Kisatchie NF",
    "state": "Louisiana",
    "county": "Natchitoches",
    "coordinates": {"latitude": 31.4812, "longitude": -93.0812, "elevation_ft": 380.0},
    "management_agency": {"name": "U.S. Forest Service - Kisatchie National Forest (Kisatchie District)", "type": "Federal", "phone": "(318) 472-1840", "website": "https://www.fs.usda.gov/kisatchie"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside wilderness boundary)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free dispersed primitive camping allowed on national forest pullouts along Longleaf Trail Scenic Byway (FH 59). Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Kisatchie Bayou. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Paved scenic byway to gravel forest roads", "road_conditions": "Paved Longleaf Trail Scenic Byway with smooth gravel forest side turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low along Longleaf Scenic Byway crest", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["Longleaf Pine Sandhills Savanna", "Kisatchie Bayou Rapids Proximity", "Backbone Trail Access", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 5, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Natchitoches, LA", "distance_miles": 18.0, "services_available": ["NSU Campus", "Full Groceries", "Hospital", "Gas Stations", "Hardware", "Historic District"]}],
    "seasonal_weather_effects": {"spring": "Lush longleaf spring (68-78°F).", "summer": "Hot humid summer (90-95°F) with bayou swimming.", "fall": "Crisp pleasant autumn days.", "winter": "Mild winter (52-65°F)."},
    "dangers_and_hazards": ["Feral Hogs", "Venomous Snakes", "Humidity"],
    "acoustic_environment": {"quietness_rating": "Sandhills Pine Savanna Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind through longleaf pines", "Bayou rapids roar"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Longleaf Pine", "Shortleaf Pine", "Red Cockaded Woodpecker", "Orchid"], "common_animals": ["White-tailed Deer", "Feral Hog", "Red-cockaded Woodpecker", "Louisiana Black Bear"]},
    "human_demographics_and_culture": "Caddo and Adai ancestral lands and Natchitoches French Creole historic culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Known as the 'Little Grand Canyon of Louisiana', featuring 300-foot sandstone mesas and longleaf pine savannas.", "energetic_and_spiritual_features": "Rolling longleaf pine sandhills and sandstone rocky outcrops rare in Louisiana."},
    "nearby_hiking_trails": [{"trail_name": "Backbone Trail (Kisatchie Hills)", "length_miles": 7.0, "difficulty": "Moderate", "features": "Sandstone mesa ridges, longleaf pine savanna, Kisatchie bayou views"}],
    "public_reviews_summary": "Louisiana's premier mountain-like longleaf pine sandhills basecamp near Natchitoches with blazing 5G cell service.",
    "other_data": "Known as the 'Little Grand Canyon of Louisiana'.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "louisiana-007",
    "name": "Caney Lakes Dispersed Area - Kisatchie NF",
    "state": "Louisiana",
    "county": "Webster",
    "coordinates": {"latitude": 32.7123, "longitude": -93.2812, "elevation_ft": 280.0},
    "management_agency": {"name": "U.S. Forest Service - Caney Ranger District", "type": "Federal", "phone": "(318) 927-2061", "website": "https://www.fs.usda.gov/kisatchie"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside developed fee area)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along FS Road 158. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Caney Lakes. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low along Caney Lake shoreline", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["Caney Lakes Shoreline Views", "Bass & Crappie Fishing", "Pine Forest Shade", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 8, "distance_to_gym_score": 6, "terrain_score": 8, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Minden / Shreveport, LA", "distance_miles": 8.0, "services_available": ["Full City Services", "Hospital", "Walmart", "Gas Stations", "Hardware", "Gyms"]}],
    "seasonal_weather_effects": {"spring": "Lush pine spring (68-78°F).", "summer": "Warm humid summer (90-95°F) with lake breeze.", "fall": "Crisp pleasant autumn days.", "winter": "Mild winter (52-64°F)."},
    "dangers_and_hazards": ["Alligators in Lake Coves", "Venomous Snakes"],
    "acoustic_environment": {"quietness_rating": "Lake Shoreline Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Caney Lake wave lap", "Pine wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Loblolly Pine", "Shortleaf Pine", "Sweetgum", "Cypress"], "common_animals": ["Large-mouth Bass", "American Alligator", "White-tailed Deer", "Bald Eagle"]},
    "human_demographics_and_culture": "Caddo ancestral lands and Minden North Louisiana pine timber heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Twin freshwater reservoirs surrounded by loblolly pine hills in North Louisiana.", "energetic_and_spiritual_features": "Quiet pine-covered hills descending to clear lake coves under 45 minutes from Shreveport."},
    "nearby_hiking_trails": [{"trail_name": "Caney Lakes Summit Trail", "length_miles": 3.5, "difficulty": "Easy to Moderate", "features": "Lake shoreline, pine hardwood forest, fishing docks"}],
    "public_reviews_summary": "Super convenient free lake basecamp near Minden and Shreveport with fast 5G cell service.",
    "other_data": "8 miles from Minden.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "louisiana-008",
    "name": "Catahoula Dispersed Area - Kisatchie NF",
    "state": "Louisiana",
    "county": "Grant",
    "coordinates": {"latitude": 31.6123, "longitude": -92.4812, "elevation_ft": 210.0},
    "management_agency": {"name": "U.S. Forest Service - Catahoula Ranger District", "type": "Federal", "phone": "(318) 765-3554", "website": "https://www.fs.usda.gov/kisatchie"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside Stuart Lake fee loop)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free primitive dispersed camping allowed on national forest pullouts along FS Road 120. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Catahoula Creek. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low along forest corridor", "distance_from_tower_corridor_miles": 6.5, "cellular_internet_dependable": True},
    "amenities": ["Loblolly Pine Canopy", "Livingston Lake Nearby", "Breezy Hill Trail Access", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 5, "terrain_score": 8, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Pollock / Alexandria, LA", "distance_miles": 12.0, "services_available": ["Full City Services", "Hospital", "Walmart", "Gas Stations", "Hardware"]}],
    "seasonal_weather_effects": {"spring": "Lush pine spring (68-78°F).", "summer": "Warm humid summer (90-95°F) with forest shade.", "fall": "Crisp pleasant autumn days.", "winter": "Mild winter (52-64°F)."},
    "dangers_and_hazards": ["Feral Hogs", "Venomous Snakes"],
    "acoustic_environment": {"quietness_rating": "Pine Forest Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind through loblolly pine needles", "Bird calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Loblolly Pine", "Shortleaf Pine", "Post Oak", "Dogwood"], "common_animals": ["White-tailed Deer", "Feral Hog", "Red-cockaded Woodpecker", "Coyote"]},
    "human_demographics_and_culture": "Catahoula ancestral lands and Central Louisiana timber heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Catahoula district named after the Native American word for 'sacred clear lake'.", "energetic_and_spiritual_features": "Quiet loblolly pine woods framing small spring-fed creeks near Alexandria."},
    "nearby_hiking_trails": [{"trail_name": "Breezy Hill Trail", "length_miles": 3.0, "difficulty": "Easy", "features": "Loblolly pine canopy, rolling sandhills, wildflower swales"}],
    "public_reviews_summary": "Peaceful pine forest basecamp near Alexandria with easy access and reliable cell service.",
    "other_data": "12 miles north of Alexandria.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "louisiana-009",
    "name": "Winn Dispersed Area - Kisatchie NF",
    "state": "Louisiana",
    "county": "Winn",
    "coordinates": {"latitude": 31.9123, "longitude": -92.6412, "elevation_ft": 240.0},
    "management_agency": {"name": "U.S. Forest Service - Winn Ranger District", "type": "Federal", "phone": "(318) 628-4664", "website": "https://www.fs.usda.gov/kisatchie"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside Gum Springs fee lot)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along FS Road 500. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Saline Bayou. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low along forest corridor", "distance_from_tower_corridor_miles": 7.0, "cellular_internet_dependable": True},
    "amenities": ["Saline National Wild & Scenic Bayou Proximity", "Cypress Swamp & Pine Forest", "Canoeing & Kayaking", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 8, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Winnfield, LA", "distance_miles": 12.0, "services_available": ["Grocery Store", "Gas Stations", "Hardware", "Diner"]}],
    "seasonal_weather_effects": {"spring": "Lush cypress spring (68-78°F).", "summer": "Warm humid summer (90-95°F) with bayou shade.", "fall": "Crisp pleasant autumn days.", "winter": "Mild winter (52-64°F)."},
    "dangers_and_hazards": ["Alligators in Saline Bayou", "Venomous Snakes"],
    "acoustic_environment": {"quietness_rating": "Saline Bayou Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Saline Bayou water flow", "Pine wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Bald Cypress", "Loblolly Pine", "Shortleaf Pine", "Spanish Moss"], "common_animals": ["American Alligator", "White-tailed Deer", "Barred Owl", "Red-cockaded Woodpecker"]},
    "human_demographics_and_culture": "Caddo ancestral lands and Winnfield timber & political history.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Saline Bayou is Louisiana's only designated National Wild and Scenic River, winding through moss-draped cypress swamps.", "energetic_and_spiritual_features": "Ancient cypress bayou wetlands contrasting against high loblolly pine ridges."},
    "nearby_hiking_trails": [{"trail_name": "Saline Bayou Companion Trail", "length_miles": 4.0, "difficulty": "Easy", "features": "Cypress bayou boardwalks, moss-draped trees, canoe launch overlooks"}],
    "public_reviews_summary": "Peaceful bayou forest camping near Winnfield with great canoeing and dependable cell service.",
    "other_data": "Louisiana's only National Wild & Scenic River.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "louisiana-010",
    "name": "Calcasieu Dispersed Area - Kisatchie NF",
    "state": "Louisiana",
    "county": "Vernon",
    "coordinates": {"latitude": 31.0812, "longitude": -93.1412, "elevation_ft": 310.0},
    "management_agency": {"name": "U.S. Forest Service - Calcasieu Ranger District", "type": "Federal", "phone": "(337) 791-6000", "website": "https://www.fs.usda.gov/kisatchie"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside Fullerton fee lot)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free primitive dispersed camping allowed on national forest pullouts along FS Road 400. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low under longleaf pine canopy", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["Longleaf Pine Flatwoods", "Historic Fullerton Sawmill Ruins Nearby", "Enduro Trail Access", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 7, "distance_to_gym_score": 6, "terrain_score": 8, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Leesville / Fort Johnson, LA", "distance_miles": 14.0, "services_available": ["Full City Services", "Hospital", "Walmart", "Gas Stations", "Hardware", "Gyms"]}],
    "seasonal_weather_effects": {"spring": "Lush longleaf spring (68-78°F).", "summer": "Warm humid summer (90-95°F) with pine shade.", "fall": "Crisp pleasant autumn days.", "winter": "Mild winter (52-65°F)."},
    "dangers_and_hazards": ["Feral Hogs", "Venomous Snakes"],
    "acoustic_environment": {"quietness_rating": "Longleaf Pine Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Wind through longleaf pines", "Songbird calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Longleaf Pine", "Slash Pine", "Post Oak", "Saw Palmetto"], "common_animals": ["White-tailed Deer", "Feral Hog", "Red-cockaded Woodpecker", "Gopher Tortoise"]},
    "human_demographics_and_culture": "Atakapa and Choctaw ancestral lands and historic 1920s Fullerton lumber boomtown heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Fullerton Historic Sawmill site was once the largest lumber mill in the American South, processing longleaf pine virgin forests.", "energetic_and_spiritual_features": "Quiet longleaf pine flatwoods framing historic stone ruins of the 1920s lumber mill."},
    "nearby_hiking_trails": [{"trail_name": "Fullerton Mill Historic Interpretive Trail", "length_miles": 2.5, "difficulty": "Easy", "features": "1920s sawmill concrete ruins, longleaf pine forest, mill pond"}],
    "public_reviews_summary": "Top choice longleaf pine basecamp near Leesville and Fort Johnson with historic ruins and blazing 5G cell service.",
    "other_data": "Historic Fullerton Sawmill ruins nearby.",
    "last_updated": "2026-09-12"
  }
])
save_state(la, la_path)
print("Updated Louisiana -> 10 sites.")

print("Batch P10 execution complete!")
