import json
import os

STATES_DIR = "/home/volmarr/.gemini/antigravity/scratch/Camping_Nomad_Life/states"

def load_state(name):
    path = os.path.join(STATES_DIR, f"{name}.json")
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f), path

def save_state(data, path):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")

# Revert MN, WI, KY first to ensure no duplicates if partially appended
for state in ["minnesota", "wisconsin", "kentucky"]:
    fpath = os.path.join(STATES_DIR, f"{state}.json")
    with open(fpath, "r", encoding="utf-8") as f:
        d = json.load(f)
    if len(d) > 5:
        save_state(d[:5], fpath)

# 1. Minnesota (+5 sites -> 10 total)
mn, mn_path = load_state("minnesota")
mn.extend([
  {
    "id": "minnesota-006",
    "name": "Tomahawk Dispersed Area - Superior National Forest",
    "state": "Minnesota",
    "county": "Lake",
    "coordinates": {"latitude": 47.7123, "longitude": -91.4512, "elevation_ft": 1450.0},
    "management_agency": {"name": "U.S. Forest Service - Superior National Forest", "type": "Federal", "phone": "(218) 365-7600", "website": "https://www.fs.usda.gov/superior"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside BWCAW fee boundary)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free dispersed primitive camping on national forest pullouts along Tomahawk Road (FR 377). Pack out all trash. Food storage rules strictly enforced due to black bears."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from lakes and streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy. Bear safety mandatory."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low to Moderate under Northwoods pine canopy", "distance_from_tower_corridor_miles": 7.0, "cellular_internet_dependable": True},
    "amenities": ["Boundary Waters Wilderness Gateway", "Boreal Forest Canopy", "Freshwater Lake Fishing", "Dark Sky Aurora Borealis"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Ely, MN", "distance_miles": 18.0, "services_available": ["BWCA Outfitters", "Grocery Store", "Hospital", "Gas", "Hardware"]}],
    "seasonal_weather_effects": {"spring": "Cool Northwoods spring (50-62°F).", "summer": "Pleasant summer (72-82°F) with lake swimming.", "fall": "Spectacular northern autumn colors & Aurora.", "winter": "Cold snowy winter (10-25°F)."},
    "dangers_and_hazards": ["Black Bear Habitat", "Spring Mosquitoes & Blackflies"],
    "acoustic_environment": {"quietness_rating": "Northwoods Boreal Silence (Quietness Score: 9/10)", "common_human_made_sounds": ["Loon calls", "Wind through white pines"]},
    "flora_and_fauna": {"common_plants_and_trees": ["White Pine", "Red Pine", "Balsam Fir", "Paper Birch"], "common_animals": ["Black Bear", "Gray Wolf", "Moose", "Common Loon", "Walleye"]},
    "human_demographics_and_culture": "Ojibwe (Anishinaabe) ancestral lands and Voyageur canoe heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Historic Voyageur fur trade canoe routes connected through these glacial lakes.", "energetic_and_spiritual_features": "Pristine glacial boreal forest bordering the Boundary Waters Wilderness."},
    "nearby_hiking_trails": [{"trail_name": "Birch Lake Overlook Trail", "length_miles": 3.0, "difficulty": "Easy to Moderate", "features": "Glacial lake vistas, white pine groves, granite outcrops"}],
    "public_reviews_summary": "Top choice free basecamp on the edge of Ely and the Boundary Waters with solid cell service.",
    "other_data": "No BWCA permit required for camping outside wilderness boundary.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "minnesota-007",
    "name": "Suomi Hills Dispersed Area - Chippewa National Forest",
    "state": "Minnesota",
    "county": "Itasca",
    "coordinates": {"latitude": 47.4812, "longitude": -93.6412, "elevation_ft": 1380.0},
    "management_agency": {"name": "U.S. Forest Service - Chippewa National Forest", "type": "Federal", "phone": "(218) 326-7100", "website": "https://www.fs.usda.gov/chippewa"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along Scenic Highway (MN-38) forest roads. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from lakes/streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Paved scenic highway to gravel forest roads", "road_conditions": "Paved MN-38 Scenic Byway with smooth gravel forest side turnouts.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low along MN-38 corridor", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["Glacial Lake Shorelines", "MN-38 Edge of the Wilderness Scenic Byway", "Northern Pike Fishing", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 7, "distance_to_gym_score": 6, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Grand Rapids, MN", "distance_miles": 16.0, "services_available": ["Full Groceries", "Hospital", "Target", "Walmart", "Hardware"]}],
    "seasonal_weather_effects": {"spring": "Lush spring green (52-64°F).", "summer": "Warm pleasant summer (75-84°F) with lake swimming.", "fall": "Spectacular hardwood fall color panorama.", "winter": "Snowy winter (12-28°F)."},
    "dangers_and_hazards": ["Black Bear Habitat", "Ticks in Spring Brush"],
    "acoustic_environment": {"quietness_rating": "Glacial Lake Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind through red pines", "Loon calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Red Pine", "White Pine", "Sugar Maple", "Paper Birch"], "common_animals": ["Bald Eagle", "White-tailed Deer", "Black Bear", "Walleye", "Loon"]},
    "human_demographics_and_culture": "Ojibwe ancestral territory and Edge of the Wilderness scenic byway culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Chippewa National Forest holds the highest breeding population density of Bald Eagles in the lower 48 states.", "energetic_and_spiritual_features": "Rolling glacial moraine hills covered in old-growth red pines surrounding pristine clear lakes."},
    "nearby_hiking_trails": [{"trail_name": "Suomi Hills Semi-Primitive Hiking Trail", "length_miles": 4.5, "difficulty": "Easy to Moderate", "features": "Glacial lakes, old-growth red pines, boardwalks, eagle viewing"}],
    "public_reviews_summary": "Gorgeous glacial lake hiking area along the Edge of the Wilderness byway with fast 5G cell service.",
    "other_data": "High density of nesting bald eagles.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "minnesota-008",
    "name": "Finland Dispersed Area - Finland State Forest",
    "state": "Minnesota",
    "county": "Lake",
    "coordinates": {"latitude": 47.4123, "longitude": -91.2812, "elevation_ft": 1400.0},
    "management_agency": {"name": "Minnesota Department of Natural Resources (DNR)", "type": "State", "phone": "(218) 834-1400", "website": "https://www.dnr.state.mn.us"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive state forest dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on state forest lands along County Road 7 / forest roads. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to DNR fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel forest roads; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low to Moderate on elevated North Shore ridge", "distance_from_tower_corridor_miles": 6.0, "cellular_internet_dependable": True},
    "amenities": ["Lake Superior North Shore Proximity", "Superior Hiking Trail Access", "River Waterfalls", "Dark Sky Aurora"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Silver Bay, MN", "distance_miles": 12.0, "services_available": ["Grocery Store", "Gas Station", "Hardware", "Clinic"]}],
    "seasonal_weather_effects": {"spring": "Cool North Shore spring (48-60°F).", "summer": "Cool refreshing summer (68-78°F) with Lake Superior breezes.", "fall": "Spectacular North Shore autumn foliage.", "winter": "Deep snow sports winter (15-28°F)."},
    "dangers_and_hazards": ["Black Bear Habitat", "Spring Blackflies"],
    "acoustic_environment": {"quietness_rating": "North Shore Boreal Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Baptism River flow", "Pine wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["White Spruce", "Paper Birch", "Quaking Aspen", "Thimbleberry"], "common_animals": ["White-tailed Deer", "Black Bear", "Moose", "Ruffed Grouse", "Steelhead Trout"]},
    "human_demographics_and_culture": "Anishinaabe ancestral lands and Finnish pioneer homestead heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Settled by Finnish immigrants in the 1890s who built traditional log saunas along boreal riverbanks.", "energetic_and_spiritual_features": "High ridge boreal forest overlooking the vast blue waters of Lake Superior."},
    "nearby_hiking_trails": [{"trail_name": "Superior Hiking Trail (Finland Section)", "length_miles": 5.0, "difficulty": "Moderate", "features": "Baptism River gorges, birch forest, Lake Superior overlooks"}],
    "public_reviews_summary": "Incredible free North Shore basecamp minutes from Lake Superior and the Superior Hiking Trail with dependable cell service.",
    "other_data": "Close to Tettegouche State Park.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "minnesota-009",
    "name": "Paul Bunyan Dispersed Area - Paul Bunyan State Forest",
    "state": "Minnesota",
    "county": "Hubbard",
    "coordinates": {"latitude": 47.0812, "longitude": -94.8412, "elevation_ft": 1420.0},
    "management_agency": {"name": "Minnesota Department of Natural Resources (DNR)", "type": "State", "phone": "(218) 732-3309", "website": "https://www.dnr.state.mn.us"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive state forest dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free dispersed primitive camping on state forest lands along forest roads. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from lakes/streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to DNR fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel state forest roads; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low under pine forest canopy", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["Glacial Lake Shorelines", "Paul Bunyan State Trail Access", "Pine Forest Shade", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 7, "distance_to_gym_score": 6, "terrain_score": 8, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Park Rapids, MN", "distance_miles": 14.0, "services_available": ["Grocery Stores", "Hospital", "Gas Stations", "Hardware", "Restaurants"]}],
    "seasonal_weather_effects": {"spring": "Lush pine spring (52-65°F).", "summer": "Warm pleasant summer (76-85°F) with lake swimming.", "fall": "Crisp autumn foliage.", "winter": "Snowy winter (15-28°F)."},
    "dangers_and_hazards": ["Black Bear Habitat", "Ticks in Spring"],
    "acoustic_environment": {"quietness_rating": "Pine Forest Lake Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind through jack pines", "Loon calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Jack Pine", "Red Pine", "Paper Birch", "Wild Strawberry"], "common_animals": ["White-tailed Deer", "Black Bear", "Loon", "Walleye", "Red Squirrel"]},
    "human_demographics_and_culture": "Ojibwe ancestral lands and Paul Bunyan lumberjack folklore culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Heart of legendary Paul Bunyan and Babe the Blue Ox lumberjack folklore country.", "energetic_and_spiritual_features": "Quiet glacial pine forest rolling across sandy moraine hills."},
    "nearby_hiking_trails": [{"trail_name": "Paul Bunyan State Forest Trail", "length_miles": 5.0, "difficulty": "Easy to Moderate", "features": "Pine forests, glacial lake overlooks, wildflower swales"}],
    "public_reviews_summary": "Peaceful pine forest lake camping near Park Rapids with blazing 5G cell service.",
    "other_data": "Short drive to Itasca State Park (Headwaters of Mississippi River).",
    "last_updated": "2026-09-12"
  },
  {
    "id": "minnesota-010",
    "name": "Beltrami Dispersed Area - Beltrami Island State Forest",
    "state": "Minnesota",
    "county": "Lake of the Woods",
    "coordinates": {"latitude": 48.6123, "longitude": -95.2812, "elevation_ft": 1180.0},
    "management_agency": {"name": "Minnesota Department of Natural Resources (DNR)", "type": "State", "phone": "(218) 386-1304", "website": "https://www.dnr.state.mn.us"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive state forest dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on state forest lands along forest roads. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from peatland swales. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to DNR fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel forest roads; sandy turnouts.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars on main gravel roads.", "scores": {"road_grade": 1, "road_terrain_difficulty": 2, "supply_run_pain": 5}},
    "nomad_connectivity_rating": {"overall_rating": "Fair to Good (3.5/5 Stars)", "verizon_reliability": "3 bars 4G LTE", "att_reliability": "3 bars 4G LTE", "tmobile_reliability": "2 bars 4G LTE", "terrain_obstruction_risk": "Low - flat peatland pine ridge plain", "distance_from_tower_corridor_miles": 12.0, "cellular_internet_dependable": True},
    "amenities": ["Vast Northwoods Solitude", "Peatland Pine Islands", "Lake of the Woods Proximity", "Dark Sky Aurora"],
    "location_scores": {"distance_to_groceries_score": 5, "distance_to_library_score": 5, "distance_to_gym_score": 3, "terrain_score": 8, "quietness_score": 10},
    "nearest_supply_towns": [{"town_name": "Baudette, MN", "distance_miles": 22.0, "services_available": ["Grocery Store", "Hospital", "Gas Stations", "Hardware"]}],
    "seasonal_weather_effects": {"spring": "Breezy spring (48-60°F).", "summer": "Pleasant summer (72-82°F) with cool nights.", "fall": "Crisp autumn foliage & Aurora.", "winter": "Severe cold winter (5-20°F)."},
    "dangers_and_hazards": ["Black Bear & Wolf Habitat", "Spring Blackflies & Mosquitoes"],
    "acoustic_environment": {"quietness_rating": "Peatland Boreal Silence (Quietness Score: 10/10)", "common_human_made_sounds": ["Wind through jack pines", "Wolf howls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Jack Pine", "Tamarack", "Black Spruce", "Bog Laurel"], "common_animals": ["Gray Wolf", "Black Bear", "Moose", "Great Gray Owl", "Sharp-tailed Grouse"]},
    "human_demographics_and_culture": "Red Lake Ojibwe ancestral lands and 1930s Resettlement Administration homestead history.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Second largest state forest in Minnesota, protecting over 669,000 acres of peatlands and jack pine ridges.", "energetic_and_spiritual_features": "Profound remote boreal silence stretching north toward Lake of the Woods."},
    "nearby_hiking_trails": [{"trail_name": "Hayes Lake State Park Trail Connection", "length_miles": 4.0, "difficulty": "Easy", "features": "Jack pine ridges, bog boardwalks, river dam overlooks"}],
    "public_reviews_summary": "Vast, solitary boreal forest landscape with wolf pack howls and usable 4G cell service.",
    "other_data": "669,000 acres of public state forest land.",
    "last_updated": "2026-09-12"
  }
])
save_state(mn, mn_path)
print("Updated Minnesota -> 10 sites.")

# 2. Wisconsin (+5 sites -> 10 total)
wi, wi_path = load_state("wisconsin")
wi.extend([
  {
    "id": "wisconsin-006",
    "name": "Porcupine Lake Dispersed Area - Chequamegon NF",
    "state": "Wisconsin",
    "county": "Bayfield",
    "coordinates": {"latitude": 46.3512, "longitude": -91.1234, "elevation_ft": 1250.0},
    "management_agency": {"name": "U.S. Forest Service - Chequamegon-Nicolet National Forest", "type": "Federal", "phone": "(715) 634-4821", "website": "https://www.fs.usda.gov/cnnf"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside wilderness boundary)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along FR 213 outside wilderness boundary. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Porcupine Lake. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low to Moderate under Northwoods hardwood canopy", "distance_from_tower_corridor_miles": 7.0, "cellular_internet_dependable": True},
    "amenities": ["Porcupine Lake Wilderness Access", "North Country Trail Access", "Northwoods Hardwood Canopy", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Hayward / Cable, WI", "distance_miles": 16.0, "services_available": ["Grocery Stores", "Hospital", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush Northwoods spring (52-64°F).", "summer": "Pleasant summer (74-84°F) with lake swimming.", "fall": "Spectacular Northwoods autumn foliage.", "winter": "Snowy winter (15-28°F)."},
    "dangers_and_hazards": ["Black Bear Habitat", "Spring Mosquitoes"],
    "acoustic_environment": {"quietness_rating": "Wilderness Edge Silence (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind through hemlocks", "Loon calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Eastern Hemlock", "Sugar Maple", "Yellow Birch", "White Pine"], "common_animals": ["Black Bear", "White-tailed Deer", "Fisher", "Common Loon", "Walleye"]},
    "human_demographics_and_culture": "Ojibwe ancestral lands and Cable/Hayward Birkie ski & mountain bike culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Protecting 4,400 acres of old-growth hemlock and glacial lakes in the Northwoods.", "energetic_and_spiritual_features": "Quiet old-growth hemlock forest bordering pristine Porcupine Lake."},
    "nearby_hiking_trails": [{"trail_name": "North Country Trail (Porcupine Lake Section)", "length_miles": 5.5, "difficulty": "Moderate", "features": "Old-growth hemlocks, glacial lakes, North Country Trail vistas"}],
    "public_reviews_summary": "Incredible wilderness edge camping near Cable with North Country Trail access and dependable cell service.",
    "other_data": "Close to CAMBA mountain bike trail system.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "wisconsin-007",
    "name": "Moquah Barrens Dispersed Area - Chequamegon NF",
    "state": "Wisconsin",
    "county": "Bayfield",
    "coordinates": {"latitude": 46.5812, "longitude": -91.2123, "elevation_ft": 1100.0},
    "management_agency": {"name": "U.S. Forest Service - Washburn Ranger District", "type": "Federal", "phone": "(715) 373-2667", "website": "https://www.fs.usda.gov/cnnf"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along FR 236 in the Moquah Barrens area. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from dry washes. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires strictly in cleared stone rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded sandy gravel forest road", "road_conditions": "Graded gravel and sandy dirt forest roads; smooth when dry.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars on main gravel roads.", "scores": {"road_grade": 1, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low - wide open jack pine savanna", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["Pine Barrens Savanna Landscape", "Wild Blueberry Picking", "Sharptailed Grouse Viewing", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 5, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Washburn / Ashland, WI", "distance_miles": 14.0, "services_available": ["Full Groceries", "Hospital", "Gas Stations", "Hardware", "Lake Superior Harbor"]}],
    "seasonal_weather_effects": {"spring": "Breezy pine barrens spring (55-68°F).", "summer": "Warm sunny summer (76-85°F) with wild blueberry picking.", "fall": "Crisp clear autumn days.", "winter": "Snowy winter (15-28°F)."},
    "dangers_and_hazards": ["Summer Wildfire Risk in Pine Barrens", "Ticks in Spring"],
    "acoustic_environment": {"quietness_rating": "Pine Barrens Silence (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind through jack pines", "Bluebird calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Jack Pine", "Scrub Oak", "Wild Blueberry", "Sweetfern"], "common_animals": ["Sharptailed Grouse", "Upland Sandpiper", "Badger", "White-tailed Deer"]},
    "human_demographics_and_culture": "Red Cliff Ojibwe ancestral lands and pine barrens ecological restoration culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Globally rare glacial pine barrens ecosystem maintained by natural fire cycles for thousands of years.", "energetic_and_spiritual_features": "Wide open rolling jack pine savanna 15 minutes from Lake Superior."},
    "nearby_hiking_trails": [{"trail_name": "Moquah Barrens Savanna Trail", "length_miles": 3.0, "difficulty": "Easy", "features": "Jack pine savanna, prairie wildflowers, blueberry fields"}],
    "public_reviews_summary": "Beautiful solitary pine barrens basecamp close to Chequamegon Bay with fast 5G cell service.",
    "other_data": "Great blueberry picking in late July.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "wisconsin-008",
    "name": "Black River Dispersed Area - Black River State Forest",
    "state": "Wisconsin",
    "county": "Jackson",
    "coordinates": {"latitude": 44.2812, "longitude": -90.7412, "elevation_ft": 850.0},
    "management_agency": {"name": "Wisconsin Department of Natural Resources (DNR)", "type": "State", "phone": "(715) 284-4103", "website": "https://dnr.wisconsin.gov"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive state forest dispersed camping with free DNR permit)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on state forest pullouts along forest roads. Post free DNR permit. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Black River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to DNR fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel forest roads; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low under pine forest canopy", "distance_from_tower_corridor_miles": 4.5, "cellular_internet_dependable": True},
    "amenities": ["Black River Canoe Route", "Sandstone Ridge Overlooks", "Pine & Oak Shade", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 8, "distance_to_gym_score": 6, "terrain_score": 9, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Black River Falls, WI", "distance_miles": 10.0, "services_available": ["Grocery Stores", "Hospital", "Gas Stations", "Hardware", "Diners"]}],
    "seasonal_weather_effects": {"spring": "Lush green pine spring (58-70°F).", "summer": "Warm pleasant summer (80-88°F) with river canoeing.", "fall": "Crisp autumn foliage.", "winter": "Snowy winter (20-32°F)."},
    "dangers_and_hazards": ["Ticks in Spring Brush", "High Summer River Water"],
    "acoustic_environment": {"quietness_rating": "Pine Ridge Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Wind through jack pines", "Black River water flow"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Jack Pine", "White Pine", "Scrub Oak", "Blueberry"], "common_animals": ["Elk", "Karner Blue Butterfly", "White-tailed Deer", "Coyote"]},
    "human_demographics_and_culture": "Ho-Chunk Nation ancestral lands and Black River Falls lumber & elk herd restoration heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Ho-Chunk traditional territory; home to Wisconsin's restored wild elk herd.", "energetic_and_spiritual_features": "Sandstone bluffs rising out of central Wisconsin pine barrens along the Black River."},
    "nearby_hiking_trails": [{"trail_name": "Castle Mound Pine Ridge Trail", "length_miles": 2.5, "difficulty": "Easy to Moderate", "features": "Sandstone mound peak, 360-degree pine forest views, rock stairs"}],
    "public_reviews_summary": "Super easy I-94 access near Black River Falls with wild elk herd viewing and blazing 5G cell service.",
    "other_data": "Free state forest camping permit required.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "wisconsin-009",
    "name": "Flambeau River Dispersed Area - Flambeau River State Forest",
    "state": "Wisconsin",
    "county": "Sawyer",
    "coordinates": {"latitude": 45.8123, "longitude": -90.8412, "elevation_ft": 1300.0},
    "management_agency": {"name": "Wisconsin Department of Natural Resources (DNR)", "type": "State", "phone": "(715) 332-5271", "website": "https://dnr.wisconsin.gov"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive state forest dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on state forest lands along forest roads outside river canoe landings. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Flambeau River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to DNR fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel forest roads; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low under hemlock pine canopy", "distance_from_tower_corridor_miles": 6.5, "cellular_internet_dependable": True},
    "amenities": ["Flambeau River Whitewater Canoeing", "Old-Growth Hardwood Forest", "Musky Fishing", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Winter / Phillips, WI", "distance_miles": 14.0, "services_available": ["Grocery Store", "Gas Station", "Hardware", "Diner"]}],
    "seasonal_weather_effects": {"spring": "Lush Northwoods spring (52-64°F).", "summer": "Warm pleasant summer (75-84°F) with river canoeing.", "fall": "Spectacular northern hardwood fall color.", "winter": "Snowy winter (15-28°F)."},
    "dangers_and_hazards": ["Whitewater Rapids on River", "Black Bear Habitat"],
    "acoustic_environment": {"quietness_rating": "Flambeau River Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Flambeau River rapids", "Wind through hemlocks"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Sugar Maple", "Hemlock", "Yellow Birch", "White Pine"], "common_animals": ["Muskellunge (Musky)", "Bald Eagle", "Black Bear", "Timber Wolf", "White-tailed Deer"]},
    "human_demographics_and_culture": "Ojibwe ancestral territory and Flambeau River whitewater canoe & musky fishing culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Protecting 90,000 acres of Northwoods forest along the North and South forks of the Flambeau River.", "energetic_and_spiritual_features": "Pristine Northwoods river flowing through virgin hemlock hardwood forests."},
    "nearby_hiking_trails": [{"trail_name": "Flambeau River Bluff Trail", "length_miles": 3.5, "difficulty": "Easy to Moderate", "features": "River bluffs, hemlock canopy, rapids overlooks"}],
    "public_reviews_summary": "Pristine Northwoods river camping with world-class canoe paddling and reliable cell service.",
    "other_data": "90,000 acres of state forest land.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "wisconsin-010",
    "name": "Governor Knowles Dispersed Area - Governor Knowles Forest",
    "state": "Wisconsin",
    "county": "Burnett",
    "coordinates": {"latitude": 45.7123, "longitude": -92.7412, "elevation_ft": 920.0},
    "management_agency": {"name": "Wisconsin Department of Natural Resources (DNR)", "type": "State", "phone": "(715) 463-2898", "website": "https://dnr.wisconsin.gov"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive state forest dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on state forest lands along St. Croix River corridor forest roads. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from St. Croix River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to DNR fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel forest roads; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low along St. Croix river corridor", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["St. Croix National Scenic Riverway", "Pine & Oak Shade", "Canoeing & Kayaking", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 5, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Grantsburg, WI", "distance_miles": 10.0, "services_available": ["Grocery Store", "Gas Stations", "Hardware", "Diner"]}, {"town_name": "Twin Cities, MN", "distance_miles": 65.0, "services_available": ["Major Metropolitan Services"]}],
    "seasonal_weather_effects": {"spring": "Lush river valley spring (55-68°F).", "summer": "Warm pleasant summer (78-85°F) with river canoeing.", "fall": "Crisp autumn foliage.", "winter": "Snowy winter (18-30°F)."},
    "dangers_and_hazards": ["Ticks in Spring Brush", "River Water Hazards"],
    "acoustic_environment": {"quietness_rating": "St. Croix River Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["St. Croix river water lap", "Pine wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["White Pine", "Red Pine", "Red Oak", "Bracken Fern"], "common_animals": ["Bald Eagle", "White-tailed Deer", "River Otter", "Smallmouth Bass"]},
    "human_demographics_and_culture": "Ojibwe ancestral lands and St. Croix Riverway canoe & timber heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "St. Croix National Scenic Riverway border forest protecting 55 miles of pristine river corridor.", "energetic_and_spiritual_features": "Quiet pine terrace forest overlooking the clean waters of the St. Croix River."},
    "nearby_hiking_trails": [{"trail_name": "St. Croix River Terrace Trail", "length_miles": 4.0, "difficulty": "Easy", "features": "St. Croix River vistas, white pine forest, eagle watching"}],
    "public_reviews_summary": "Fantastic St. Croix River camping under 90 minutes from the Twin Cities with fast 5G cell service.",
    "other_data": "Bordered by Crex Meadows Wildlife Area.",
    "last_updated": "2026-09-12"
  }
])
save_state(wi, wi_path)
print("Updated Wisconsin -> 10 sites.")

# 3. Kentucky (+5 sites -> 10 total)
ky, ky_path = load_state("kentucky")
ky.extend([
  {
    "id": "kentucky-006",
    "name": "Red River Gorge Dispersed Area - Daniel Boone NF",
    "state": "Kentucky",
    "county": "Powell",
    "coordinates": {"latitude": 37.8123, "longitude": -83.6412, "elevation_ft": 1100.0},
    "management_agency": {"name": "U.S. Forest Service - Daniel Boone NF (Cumberland District)", "type": "Federal", "phone": "(606) 663-2852", "website": "https://www.fs.usda.gov/dbnf"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping with $5/night vehicle parking permit)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed 300 ft away from roads and 100 ft away from sandstone cliff bases / rock shelters. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Red River and streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Paved scenic byway to gravel forest roads", "road_conditions": "Paved KY-715 Scenic Byway with gravel forest side roads.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars and camper vans.", "scores": {"road_grade": 2, "road_terrain_difficulty": 3, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great on Ridge (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "High inside deep sandstone gorges / Low on ridges", "distance_from_tower_corridor_miles": 5.5, "cellular_internet_dependable": True},
    "amenities": ["Sandstone Rock Arches & Overhangs", "World-Class Rock Climbing", "Red River Canoeing", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 5, "terrain_score": 10, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Slade / Stanton, KY", "distance_miles": 8.0, "services_available": ["Miguel's Pizza", "Grocery Store", "Gas Stations", "Climbing Shops", "Hardware"]}],
    "seasonal_weather_effects": {"spring": "Lush green gorge spring (60-72°F).", "summer": "Warm humid summer (82-88°F) with rich forest shade.", "fall": "World-class Red River Gorge fall foliage.", "winter": "Cool winter (35-45°F)."},
    "dangers_and_hazards": ["Sheer Sandstone Cliff Drops", "Copperhead & Timber Rattlesnakes"],
    "acoustic_environment": {"quietness_rating": "Sandstone Gorge Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Red River flow", "Climber calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Tulip Poplar", "Hemlock", "White Pine", "Rhododendron"], "common_animals": ["White-tailed Deer", "Copperhead", "Black Bear", "Pileated Woodpecker"]},
    "human_demographics_and_culture": "Shawnee ancestral lands and world-famous Red River Gorge rock climbing culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Over 100 natural sandstone arches carved into ancient Appalachian plateau cliffs.", "energetic_and_spiritual_features": "Towering sandstone arches and rock shelters surrounded by lush hardwood forest."},
    "nearby_hiking_trails": [{"trail_name": "Auxier Ridge Trail", "length_miles": 4.2, "difficulty": "Moderate", "features": "Auxier Ridge razorback walk, Double Arch views, Haystack Rock panorama"}],
    "public_reviews_summary": "World-famous rock climbing and sandstone arch paradise with solid cell service on ridge pullouts.",
    "other_data": "USFS overnight parking permit ($5) required on vehicle.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "kentucky-007",
    "name": "Cave Run Dispersed Area - Daniel Boone NF",
    "state": "Kentucky",
    "county": "Rowan",
    "coordinates": {"latitude": 38.1412, "longitude": -83.5412, "elevation_ft": 820.0},
    "management_agency": {"name": "U.S. Forest Service - Cumberland Ranger District", "type": "Federal", "phone": "(606) 784-5624", "website": "https://www.fs.usda.gov/dbnf"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside fee campgrounds)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along Cave Run Lake access roads. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Cave Run Lake. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Paved access to gravel forest roads", "road_conditions": "Paved KY-801 leads to well-maintained gravel forest roads.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low along Cave Run lake shoreline", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["Cave Run Lake Shoreline", "Musky Fishing Capital", "Boating & Kayaking", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 8, "distance_to_gym_score": 6, "terrain_score": 9, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Morehead, KY", "distance_miles": 10.0, "services_available": ["MSU Campus", "Full Groceries", "Hospital", "Walmart", "Hardware", "Gyms"]}],
    "seasonal_weather_effects": {"spring": "Lush green lake spring (60-72°F).", "summer": "Warm summer (82-88°F) with lake swimming.", "fall": "Crisp autumn foliage.", "winter": "Cool winter (35-48°F)."},
    "dangers_and_hazards": ["Lake Water Hazards", "Copperhead Snakes"],
    "acoustic_environment": {"quietness_rating": "Lake Shoreline Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Cave Run lake wave lap", "Occasional motorboat hum"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Shortleaf Pine", "White Oak", "Sugar Maple", "Dogwood"], "common_animals": ["Muskellunge (Musky)", "White-tailed Deer", "Bald Eagle", "Osprey"]},
    "human_demographics_and_culture": "Shawnee ancestral lands and Morehead State University & musky fishing culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "8,270-acre reservoir surrounded by rolling Daniel Boone forest ridges, known as the 'Musky Capital of the South'.", "energetic_and_spiritual_features": "Quiet hardwood forest ridges trailing down to blue water lake coves."},
    "nearby_hiking_trails": [{"trail_name": "Sheltowee Trace National Recreation Trail (Cave Run Section)", "length_miles": 5.0, "difficulty": "Easy to Moderate", "features": "Cave Run shoreline, hardwood ridges, Sheltowee Trace trail access"}],
    "public_reviews_summary": "Fantastic lake side basecamp near Morehead with world-class musky fishing and blazing 5G cell service.",
    "other_data": "Sheltowee Trace trail runs directly through area.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "kentucky-008",
    "name": "Stearns Dispersed Area - Daniel Boone NF",
    "state": "Kentucky",
    "county": "McCreary",
    "coordinates": {"latitude": 36.7123, "longitude": -84.4812, "elevation_ft": 1200.0},
    "management_agency": {"name": "U.S. Forest Service - Stearns Ranger District", "type": "Federal", "phone": "(606) 376-5323", "website": "https://www.fs.usda.gov/dbnf"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on national forest pullouts along Cumberland River corridor forest roads. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Cumberland River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road; smooth dirt turnouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 2, "road_terrain_difficulty": 3, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low to Moderate on plateau pullouts", "distance_from_tower_corridor_miles": 6.5, "cellular_internet_dependable": True},
    "amenities": ["Big South Fork National River Proximity", "Cumberland River Views", "Sandstone Rock Bluffs", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Whitley City / Stearns, KY", "distance_miles": 10.0, "services_available": ["Grocery Store", "Gas Stations", "Hardware", "Diner", "Historic Railway"]}],
    "seasonal_weather_effects": {"spring": "Lush green plateau spring (60-72°F).", "summer": "Warm summer (82-88°F) with river swimming.", "fall": "Crisp autumn foliage.", "winter": "Cool winter (35-48°F)."},
    "dangers_and_hazards": ["Sandstone Cliff Overhang Drops", "Copperhead Snakes"],
    "acoustic_environment": {"quietness_rating": "Appalachian Plateau Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Cumberland River flow", "Pine wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Shortleaf Pine", "White Oak", "Hemlock", "Rhododendron"], "common_animals": ["White-tailed Deer", "Black Bear", "Copperhead", "Wild Turkey"]},
    "human_demographics_and_culture": "Cherokee ancestral lands and Big South Fork coal mining & logging history.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Big South Fork National River and Recreation Area protects 125,000 acres of rugged Cumberland Plateau gorge country.", "energetic_and_spiritual_features": "Sandstone bluff rim overlooks commanding views of the Cumberland River gorge."},
    "nearby_hiking_trails": [{"trail_name": "Yahoo Falls Trail", "length_miles": 1.2, "difficulty": "Easy to Moderate", "features": "113-foot Yahoo Falls waterfall, giant sandstone rock shelter, hemlock gorge"}],
    "public_reviews_summary": "Peaceful Cumberland Plateau basecamp near Big South Fork with 113-foot Yahoo Falls nearby and reliable cell service.",
    "other_data": "Yahoo Falls is 113 feet tall.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "kentucky-009",
    "name": "Laurel River Dispersed Area - Daniel Boone NF",
    "state": "Kentucky",
    "county": "Laurel",
    "coordinates": {"latitude": 36.9812, "longitude": -84.1412, "elevation_ft": 1020.0},
    "management_agency": {"name": "U.S. Forest Service - London Ranger District", "type": "Federal", "phone": "(606) 864-4163", "website": "https://www.fs.usda.gov/dbnf"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside developed fee sites)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free primitive dispersed camping on national forest pullouts along Laurel River Lake access roads. Pack out all trash. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Laurel River Lake. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Paved road to gravel forest roads", "road_conditions": "Paved KY-192 leads to well-maintained gravel forest roads.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low along Laurel River Lake shoreline", "distance_from_tower_corridor_miles": 4.5, "cellular_internet_dependable": True},
    "amenities": ["Laurel River Lake Shoreline", "Scuba Diving & Swimming", "Boating & Fishing", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 8, "distance_to_gym_score": 7, "terrain_score": 9, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "London / Corbin, KY", "distance_miles": 12.0, "services_available": ["Full City Services", "Hospital", "Walmart", "Gas Stations", "Hardware"]}],
    "seasonal_weather_effects": {"spring": "Lush lake spring (60-72°F).", "summer": "Warm summer (82-88°F) with clear lake swimming.", "fall": "Crisp autumn foliage.", "winter": "Cool winter (35-48°F)."},
    "dangers_and_hazards": ["Lake Water Hazards", "Copperhead Snakes"],
    "acoustic_environment": {"quietness_rating": "Lake Shoreline Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Laurel River lake wave lap", "Occasional motorboat hum"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Shortleaf Pine", "White Pine", "Tulip Poplar", "Dogwood"], "common_animals": ["White-tailed Deer", "Rainbow Trout", "Large-mouth Bass", "Bald Eagle"]},
    "human_demographics_and_culture": "Cherokee ancestral lands and London/Corbin Daniel Boone heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "5,600-acre deep clear lake surrounded by cliff walls, famous for exceptionally clean water and freshwater scuba diving.", "energetic_and_spiritual_features": "Deep turquoise lake waters surrounded by pine-covered sandstone cliffs."},
    "nearby_hiking_trails": [{"trail_name": "Laurel River Lake Trail", "length_miles": 4.0, "difficulty": "Easy to Moderate", "features": "Lake shoreline, pine forest, sandstone cliff overlooks"}],
    "public_reviews_summary": "Exceptionally clear lake camping near I-75 and London with blazing 5G cell service.",
    "other_data": "Known for exceptionally clear water.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "kentucky-010",
    "name": "Kuttawa Dispersed Area - Land Between the Lakes",
    "state": "Kentucky",
    "county": "Lyon",
    "coordinates": {"latitude": 37.0812, "longitude": -88.0812, "elevation_ft": 420.0},
    "management_agency": {"name": "U.S. Forest Service - Land Between the Lakes NRA", "type": "Federal", "phone": "(270) 924-2000", "website": "https://www.landbetweenthelakes.us"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping with $10/3-day LBL basic camping permit)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on designated forest pullouts along Kentucky Lake & Lake Barkley shorelines outside fee campgrounds. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from lake high water line. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood locally.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Paved trace highway to gravel forest roads", "road_conditions": "Paved Woodlands Trace National Scenic Byway with gravel side roads.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 5G", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low along open lake shorelines", "distance_from_tower_corridor_miles": 4.5, "cellular_internet_dependable": True},
    "amenities": ["Kentucky Lake & Lake Barkley Shoreline", "Bison & Elk Prairie Proximity", "Boating & Swimming", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 7, "distance_to_gym_score": 6, "terrain_score": 9, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Eddyville / Kuttawa, KY", "distance_miles": 8.0, "services_available": ["Grocery Store", "Gas Stations", "Hardware", "Diner", "Marinas"]}],
    "seasonal_weather_effects": {"spring": "Lush green lake spring (62-74°F).", "summer": "Warm summer (84-90°F) with lake swimming.", "fall": "Crisp autumn foliage.", "winter": "Cool winter (38-50°F)."},
    "dangers_and_hazards": ["Lake Water Hazards", "Ticks in Spring"],
    "acoustic_environment": {"quietness_rating": "Lake Peninsula Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Kentucky Lake wave lap", "Eagle calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["White Oak", "Post Oak", "Shortleaf Pine", "Dogwood"], "common_animals": ["American Bison", "Elk", "Bald Eagle", "White-tailed Deer", "Crappie"]},
    "human_demographics_and_culture": "Chickasaw ancestral lands and Land Between the Lakes national recreation heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "170,000-acre national recreation peninsula situated between Kentucky Lake and Lake Barkley.", "energetic_and_spiritual_features": "Vast freshwater lake peninsula offering quiet oak woodland shoreline camping."},
    "nearby_hiking_trails": [{"trail_name": "Central Hardwoods Scenic Trail", "length_miles": 11.0, "difficulty": "Easy to Moderate", "features": "Lake views, hardwood forest canopy, wildlife viewing"}],
    "public_reviews_summary": "Incredible freshwater lake peninsula camping with bison viewing and blazing 5G cell service.",
    "other_data": "LBL basic camping permit ($10/3-days) required.",
    "last_updated": "2026-09-12"
  }
])
save_state(ky, ky_path)
print("Updated Kentucky -> 10 sites.")

print("Fixed Batch P7 execution complete!")
