import json
import os

STATES_DIR = "/home/volmarr/.gemini/antigravity/scratch/Camping_Nomad_Life/states"

def load_state(name):
    path = os.path.join(STATES_DIR, f"{name}.json")
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f), path

def save_state(data, path):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")

# 1. New Mexico (+5 sites -> 10 total)
nm, nm_path = load_state("new_mexico")
nm.extend([
  {
    "id": "new_mexico-006",
    "name": "Box Canyon Dispersed Camping Area - BLM Socorro",
    "state": "New Mexico",
    "county": "Socorro",
    "coordinates": {"latitude": 34.0289, "longitude": -107.0142, "elevation_ft": 5350.0},
    "management_agency": {"name": "Bureau of Land Management (BLM) - Socorro Field Office", "type": "Federal", "phone": "(575) 835-0412", "website": "https://www.blm.gov/new-mexico"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive BLM dispersed camping)", "stay_limit": "14 days maximum stay within a 28-day window", "guidelines": "Free dispersed primitive camping on BLM lands surrounding Box Canyon. Leave No Trace. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from dry washes. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead and down wood locally.", "safety_requirements": "Campfires permitted in cleared metal or stone fire rings. Extinguish cold.", "seasonal_fire_bans": "Subject to BLM Stage 1 & 2 fire restrictions during dry spring months."},
    "access_and_road_conditions": {"road_type": "Gravel dirt access road", "road_conditions": "Graded gravel access road; smooth lower pullouts.", "vehicle_recommendation": "Accessible by standard FWD passenger car and camper vans.", "scores": {"road_grade": 2, "road_terrain_difficulty": 3, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3-4 bars 4G LTE", "terrain_obstruction_risk": "Low on canyon rim pullouts", "distance_from_tower_corridor_miles": 6.5, "cellular_internet_dependable": True},
    "amenities": ["Rock Climbing Crags", "Desert Mountain Views", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 7, "distance_to_gym_score": 6, "terrain_score": 8, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Socorro, NM", "distance_miles": 9.0, "services_available": ["Grocery Stores", "Gas Stations", "Hospital", "Hardware Store", "Restaurants"]}],
    "seasonal_weather_effects": {"spring": "Sunny mild spring (65-78°F).", "summer": "Hot summer days (92-100°F) with afternoon monsoons.", "fall": "Crisp autumn weather (70-80°F).", "winter": "Cool winter (45-55°F) with cold desert nights."},
    "dangers_and_hazards": ["Flash Floods in Washes", "Rattlesnakes", "Summer Heat"],
    "acoustic_environment": {"quietness_rating": "Canyon Basin Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Occasional climber voices", "Distant Highway 60 hum"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Creosote Bush", "Ocotillo", "Yucca", "Prickly Pear"], "common_animals": ["Coyote", "Red-tailed Hawk", "Gambel's Quail", "Mule Deer"]},
    "human_demographics_and_culture": "Socorro tech and mining heritage combined with rock climbing outdoor culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Magdalena Mountains held deep spiritual reverence for ancient Mogollon and Apache peoples.", "energetic_and_spiritual_features": "Dramatic volcanic canyon walls radiating deep earth energy."},
    "nearby_hiking_trails": [{"trail_name": "Box Canyon Climber's Access Trail", "length_miles": 2.5, "difficulty": "Moderate", "features": "Canyon walls, rock climbing routes, desert vistas"}],
    "public_reviews_summary": "Incredible rock climbing hotspot with fast 5G cellular internet and instant access to Socorro.",
    "other_data": "Popular weekend rock climbing destination; quiet during weekdays.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "new_mexico-007",
    "name": "Mills Canyon Dispersed Camping - Kiowa National Grassland",
    "state": "New Mexico",
    "county": "Harding",
    "coordinates": {"latitude": 36.0456, "longitude": -104.3618, "elevation_ft": 5200.0},
    "management_agency": {"name": "U.S. Forest Service - Kiowa National Grassland (Cibola NF)", "type": "Federal", "phone": "(575) 485-2270", "website": "https://www.fs.usda.gov/cibola"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive dispersed grassland camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed camping allowed along canyon rim and lower primitive pullouts. Pack out all waste."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Canadian River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Dirt mountain switchback road", "road_conditions": "Rim road gravel; canyon descent road steep, narrow, and slick when wet.", "vehicle_recommendation": "Rim accessible by 2WD; high clearance / 4WD required for canyon bottom.", "scores": {"road_grade": 7, "road_terrain_difficulty": 8, "supply_run_pain": 7}},
    "nomad_connectivity_rating": {"overall_rating": "Fair on Rim / Poor in Canyon (3/5 Stars)", "verizon_reliability": "2-3 bars 4G LTE on Rim", "att_reliability": "2 bars 4G LTE on Rim", "tmobile_reliability": "1-2 bars 4G LTE on Rim", "terrain_obstruction_risk": "High in canyon bottom / Low on rim", "distance_from_tower_corridor_miles": 14.0, "cellular_internet_dependable": False},
    "amenities": ["Canadian River Gorge Views", "Historic Orchard Ruins", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 3, "distance_to_library_score": 3, "distance_to_gym_score": 2, "terrain_score": 9, "quietness_score": 10},
    "nearest_supply_towns": [{"town_name": "Roy, NM", "distance_miles": 14.0, "services_available": ["Gas Station", "Small Store", "Post Office"]}, {"town_name": "Springer, NM", "distance_miles": 38.0, "services_available": ["Groceries", "Hardware Store", "Gas Stations", "Diner"]}],
    "seasonal_weather_effects": {"spring": "Breezy spring (60-75°F).", "summer": "Warm summer (85-92°F) in canyon.", "fall": "Crisp clear autumn days.", "winter": "Cold winter (30-45°F) with snow on rim."},
    "dangers_and_hazards": ["Steep Switchback Drops", "Flash Floods along Canadian River", "Extreme Mud when Wet"],
    "acoustic_environment": {"quietness_rating": "Grassland Wilderness Solitude (Quietness Score: 10/10)", "common_human_made_sounds": ["Wind rustling prairie grass", "Canyon river flow"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Ponderosa Pine", "Cottonwood", "Shortgrass Prairie", "Cholla Cactus"], "common_animals": ["Barbary Sheep", "Elk", "Wild Turkey", "Mule Deer"]},
    "human_demographics_and_culture": "Historic 1880s Melvin Mills orchard ruins and ranching history.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Kiowa and Comanche ancestral hunting grounds.", "energetic_and_spiritual_features": "Deep canyon isolation echoing historical ghost town memories."},
    "nearby_hiking_trails": [{"trail_name": "Mills Canyon River Trail", "length_miles": 4.2, "difficulty": "Moderate", "features": "Canadian River gorge, orchard ruins, cliff walls"}],
    "public_reviews_summary": "Profound canyon wilderness solitude; rim sites offer good cell service while canyon bottom offers complete disconnection.",
    "other_data": "Avoid canyon descent during heavy rainfall due to clay mud.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "new_mexico-008",
    "name": "Datil Well Dispersed Area - BLM / Cibola National Forest",
    "state": "New Mexico",
    "county": "Catron",
    "coordinates": {"latitude": 34.1481, "longitude": -107.8483, "elevation_ft": 7400.0},
    "management_agency": {"name": "Bureau of Land Management (BLM) / USFS Cibola NF", "type": "Federal", "phone": "(575) 835-0412", "website": "https://www.blm.gov/new-mexico"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on surrounding BLM and National Forest spur tracks. Pack out all garbage."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from dry washes. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down pinyon/juniper wood.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to stage fire bans in dry summer."},
    "access_and_road_conditions": {"road_type": "Gravel forest spur road", "road_conditions": "Well-maintained gravel roads off US Highway 60.", "vehicle_recommendation": "Accessible by low-clearance FWD sedans and camper vans.", "scores": {"road_grade": 2, "road_terrain_difficulty": 2, "supply_run_pain": 5}},
    "nomad_connectivity_rating": {"overall_rating": "Good (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "3 bars 4G LTE", "tmobile_reliability": "2-3 bars 4G LTE", "terrain_obstruction_risk": "Low - open pinyon savanna", "distance_from_tower_corridor_miles": 4.2, "cellular_internet_dependable": True},
    "amenities": ["Pinyon & Ponderosa Shade", "Continental Divide Trail Access", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 5, "distance_to_library_score": 4, "distance_to_gym_score": 3, "terrain_score": 8, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Pie Town, NM", "distance_miles": 21.0, "services_available": ["Pie Cafes", "General Store", "Gas Station"]}, {"town_name": "Magdalena, NM", "distance_miles": 36.0, "services_available": ["Groceries", "Hardware", "Gas Stations", "Cafes"]}],
    "seasonal_weather_effects": {"spring": "Breezy mountain spring (60-72°F).", "summer": "Pleasant high-elevation summer (78-85°F).", "fall": "Crisp autumn weather (65-75°F).", "winter": "Cold winter (35-48°F) with light snow."},
    "dangers_and_hazards": ["High Altitude Sun", "Sudden Evening Temperature Drops"],
    "acoustic_environment": {"quietness_rating": "High Mountain Savanna Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Occasional US-60 vehicle pass"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Ponderosa Pine", "Pinyon Pine", "Utah Juniper", "Blue Grama"], "common_animals": ["Pronghorn Antelope", "Mule Deer", "Elk", "Gray Fox"]},
    "human_demographics_and_culture": "Continental Divide trail culture and historic Magdalena livestock driveway history.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Ancient Puebloan trade routes connected through these mountain passes.", "energetic_and_spiritual_features": "High elevation clarity near the Continental Divide spine."},
    "nearby_hiking_trails": [{"trail_name": "Datil Mountain Trail Loop", "length_miles": 4.8, "difficulty": "Moderate", "features": "Pine forest, mountain vistas, Continental Divide views"}],
    "public_reviews_summary": "Cool high elevation summer relief, steady cell service, and easy highway access.",
    "other_data": "Great stopover for nomads traveling along US-60 across New Mexico.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "new_mexico-009",
    "name": "Cosmic Campground Dispersed Area - Gila National Forest",
    "state": "New Mexico",
    "county": "Catron",
    "coordinates": {"latitude": 33.4797, "longitude": -108.9228, "elevation_ft": 5400.0},
    "management_agency": {"name": "U.S. Forest Service - Gila National Forest (Glenwood District)", "type": "Federal", "phone": "(575) 539-2481", "website": "https://www.fs.usda.gov/gila"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive camping at International Dark Sky Sanctuary)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed camping at Cosmic Dark Sky Sanctuary. Red light flashlights required after dark to preserve night vision."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from drainages. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared metal or stone fire rings. Douse cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans in dry spring/summer."},
    "access_and_road_conditions": {"road_type": "Paved highway to gravel loop", "road_conditions": "Paved US-180 access directly to smooth gravel entrance loop.", "vehicle_recommendation": "Accessible by all vehicles including low-clearance sedans and large rigs.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 6}},
    "nomad_connectivity_rating": {"overall_rating": "Weak / Spotty (2/5 Stars)", "verizon_reliability": "1-2 bars 4G LTE (Spotty)", "att_reliability": "1 bar 4G LTE", "tmobile_reliability": "0-1 bar (No Data)", "terrain_obstruction_risk": "Moderate due to Gila mountain valley walls", "distance_from_tower_corridor_miles": 13.5, "cellular_internet_dependable": False},
    "amenities": ["International Dark Sky Sanctuary", "Concrete Telescope Pads", "Smooth Road Access"],
    "location_scores": {"distance_to_groceries_score": 4, "distance_to_library_score": 4, "distance_to_gym_score": 2, "terrain_score": 10, "quietness_score": 10},
    "nearest_supply_towns": [{"town_name": "Glenwood, NM", "distance_miles": 12.0, "services_available": ["Gas Station", "Small Store", "Cafe", "Post Office"]}, {"town_name": "Reserve, NM", "distance_miles": 26.0, "services_available": ["Groceries", "Hardware Store", "Gas Stations", "Diner"]}],
    "seasonal_weather_effects": {"spring": "Clear spring skies (68-78°F).", "summer": "Warm days (85-90°F) with afternoon monsoons.", "fall": "Crisp autumn stargazing weather.", "winter": "Cool winter days (45-55°F) with freezing night temps."},
    "dangers_and_hazards": ["Extreme Night Darkness", "Monsoon Lightning"],
    "acoustic_environment": {"quietness_rating": "Pristine Dark Sky Silence (Quietness Score: 10/10)", "common_human_made_sounds": ["Absolute night silence", "Occasional breeze"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Piñon Pine", "Oak Woodland", "Blue Grama", "Yucca"], "common_animals": ["Coatimundi", "Javelina", "Black Bear", "Mountain Lion", "Great Horned Owl"]},
    "human_demographics_and_culture": "Mogollon culture archaeology and international astronomy stargazing culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Ancestral Mogollon stargazing grounds held sacred celestial connections.", "energetic_and_spiritual_features": "Zero light pollution creates awe-inspiring connection to the Milky Way galaxy."},
    "nearby_hiking_trails": [{"trail_name": "Catwalk National Recreation Trail", "length_miles": 2.0, "difficulty": "Easy to Moderate", "features": "Whitewater Creek canyon, suspended metal walkway, waterfalls"}],
    "public_reviews_summary": "World-class stargazing destination; cell service is weak so bring Starlink if remote working.",
    "other_data": "First dark sky sanctuary located on US public land.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "new_mexico-010",
    "name": "Wild Rivers Dispersed Primitive Area - Rio Grande del Norte",
    "state": "New Mexico",
    "county": "Taos",
    "coordinates": {"latitude": 36.7389, "longitude": -105.6881, "elevation_ft": 7600.0},
    "management_agency": {"name": "Bureau of Land Management (BLM) - Taos Field Office", "type": "Federal", "phone": "(575) 758-8851", "website": "https://www.blm.gov/new-mexico"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive dispersed camping outside fee loops)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping permitted on BLM lands along Wild Rivers Backcountry Byway outside developed fee loops. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from gorge rim. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to BLM stage fire restrictions in spring."},
    "access_and_road_conditions": {"road_type": "Paved backcountry byway to dirt pullouts", "road_conditions": "Paved NM-515 highway with smooth dirt rim pullouts.", "vehicle_recommendation": "Accessible by all low-clearance vehicles and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 4}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "3-4 bars 4G LTE", "tmobile_reliability": "3 bars 5G", "terrain_obstruction_risk": "Low on high plateau rim", "distance_from_tower_corridor_miles": 7.5, "cellular_internet_dependable": True},
    "amenities": ["Rio Grande Gorge Overlook Views", "Paved Access Byway", "Canyon Trails", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 5, "distance_to_gym_score": 4, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Questa, NM", "distance_miles": 10.0, "services_available": ["Grocery Store", "Gas Station", "Hardware", "Restaurants"]}, {"town_name": "Taos, NM", "distance_miles": 34.0, "services_available": ["Full City Services", "Hospital", "Gear Shops", "Walmart"]}],
    "seasonal_weather_effects": {"spring": "Breezy spring (58-70°F).", "summer": "Mild high-elevation summer (78-85°F).", "fall": "Crisp autumn days with yellow cottonwoods.", "winter": "Cold winter (30-45°F) with snow on gorge rim."},
    "dangers_and_hazards": ["800-Foot Sheer Cliff Gorge Drops", "High Altitude Sun Exposure"],
    "acoustic_environment": {"quietness_rating": "Rio Grande Canyon Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Distant river roar in gorge", "Occasional byway car pass"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Piñon Pine", "Utah Juniper", "Big Sagebrush", "Wild Buckwheat"], "common_animals": ["Bighorn Sheep", "Golden Eagle", "Prairie Dog", "Mule Deer"]},
    "human_demographics_and_culture": "Taos Pueblo ancestral heritage, Rio Grande National Monument conservation culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Confluence of Red River and Rio Grande held sacred spiritual power for Taos Pueblo ancestors.", "energetic_and_spiritual_features": "Breath-taking 800-foot gorge drop exposing millions of years of earth geology."},
    "nearby_hiking_trails": [{"trail_name": "La Junta Gorge Confluence Trail", "length_miles": 2.4, "difficulty": "Strenuous", "features": "Descends 800 feet into river confluence, volcanic basalt cliffs"}],
    "public_reviews_summary": "Unmatched gorge views, paved road access, and rock-solid cell service make this an absolute nomad favorite.",
    "other_data": "Watch for bighorn sheep grazing near the road.",
    "last_updated": "2026-09-12"
  }
])
save_state(nm, nm_path)
print("Updated New Mexico -> 10 sites.")

# 2. Oregon (+5 sites -> 10 total)
ore, ore_path = load_state("oregon")
ore.extend([
  {
    "id": "oregon-006",
    "name": "Alvord Desert Dispersed Area - BLM Burns",
    "state": "Oregon",
    "county": "Harney",
    "coordinates": {"latitude": 42.5321, "longitude": -118.4608, "elevation_ft": 4000.0},
    "management_agency": {"name": "Bureau of Land Management (BLM) - Burns District", "type": "Federal", "phone": "(541) 573-4400", "website": "https://www.blm.gov/oregon"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive BLM dispersed camping)", "stay_limit": "14 days maximum stay within a 28-day window", "guidelines": "Dispersed camping allowed on open dry playa and desert edges. Do not drive on wet playa surface. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Pack out human waste via wag-bag or portable toilet system due to hard-baked playa surface.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Bring firewood; no wood gathering on playa.", "safety_requirements": "Campfires must be contained in portable fire pans. Do not leave ash on playa. Extinguish cold.", "seasonal_fire_bans": "Subject to BLM fire bans."},
    "access_and_road_conditions": {"road_type": "Gravel road to dry alkali playa", "road_conditions": "Fields-Denio gravel road; dry playa surface is flat as glass, wet playa becomes impassable clay mud.", "vehicle_recommendation": "Accessible by all vehicles when playa is dry; high clearance / 4WD recommended during wet season.", "scores": {"road_grade": 1, "road_terrain_difficulty": 4, "supply_run_pain": 8}},
    "nomad_connectivity_rating": {"overall_rating": "Poor / Spotty (2/5 Stars)", "verizon_reliability": "1-2 bars 4G LTE (Near Fields-Denio road)", "att_reliability": "1 bar 4G LTE", "tmobile_reliability": "0-1 bar (No Data)", "terrain_obstruction_risk": "Low on playa / High under Steens mountain wall shadow", "distance_from_tower_corridor_miles": 22.0, "cellular_internet_dependable": False},
    "amenities": ["Flat Alkali Lake Bed", "Steens Mountain Scenery Wall", "Dark Sky Astronomy", "Land-Sailing Area"],
    "location_scores": {"distance_to_groceries_score": 2, "distance_to_library_score": 2, "distance_to_gym_score": 1, "terrain_score": 10, "quietness_score": 10},
    "nearest_supply_towns": [{"town_name": "Fields, OR", "distance_miles": 22.0, "services_available": ["Gas Station", "Famous Milkshake Diner", "Small Store"]}, {"town_name": "Burns, OR", "distance_miles": 105.0, "services_available": ["Full Groceries", "Hospital", "Hardware", "Auto Repair"]}],
    "seasonal_weather_effects": {"spring": "Spring rains create wet mud on playa.", "summer": "Warm to hot summer (85-95°F) with dry playa.", "fall": "Crisp autumn days with clear skies.", "winter": "Cold freezing winter with dust storms."},
    "dangers_and_hazards": ["Dust Storms", "Getting Stuck in Wet Mud", "Remote Distance from Emergency Services"],
    "acoustic_environment": {"quietness_rating": "Absolute Desert Silence (Quietness Score: 10/10)", "common_human_made_sounds": ["Wind blowing across dry lake bed"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Grease Wood", "Big Sagebrush", "Saltbush"], "common_animals": ["Wild Horses (Mustangs)", "Pronghorn Antelope", "Coyote", "Golden Eagle"]},
    "human_demographics_and_culture": "Paiute ancestral history, land speed record trials, and high desert solitude culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Northern Paiute traditions honor the surrounding Steens Mountain range.", "energetic_and_spiritual_features": "Unending flat horizon providing feeling of otherworldly spatial freedom."},
    "nearby_hiking_trails": [{"trail_name": "Pike Creek Canyon Trail", "length_miles": 5.4, "difficulty": "Moderate to Strenuous", "features": "Steens mountain canyon, perennial stream, desert wildflowers"}],
    "public_reviews_summary": "Surreal desert landscape like nowhere else on Earth; cell service is weak so Starlink is mandatory for working.",
    "other_data": "Never drive on wet playa surface.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "oregon-007",
    "name": "Leslie Gulch Dispersed Area - BLM Vale District",
    "state": "Oregon",
    "county": "Malheur",
    "coordinates": {"latitude": 43.3189, "longitude": -117.3214, "elevation_ft": 2650.0},
    "management_agency": {"name": "Bureau of Land Management (BLM) - Vale District", "type": "Federal", "phone": "(541) 473-3144", "website": "https://www.blm.gov/oregon"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive BLM dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed camping allowed in designated pullouts along Leslie Gulch Road outside delicate ACEC botanical zones. Pack out all waste."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Owyhee Reservoir high water mark. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Bring firewood; wood gathering prohibited inside canyon ACEC.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to BLM fire bans."},
    "access_and_road_conditions": {"road_type": "Gravel canyon dirt road", "road_conditions": "15 miles of dirt gravel canyon road with washboards and loose rock.", "vehicle_recommendation": "Accessible by standard 2WD when dry; high clearance recommended.", "scores": {"road_grade": 4, "road_terrain_difficulty": 5, "supply_run_pain": 7}},
    "nomad_connectivity_rating": {"overall_rating": "No Service inside Canyon (1/5 Stars)", "verizon_reliability": "0-1 bar (No Data)", "att_reliability": "0 bars", "tmobile_reliability": "0 bars", "terrain_obstruction_risk": "Extreme inside steep volcanic tuff canyon walls", "distance_from_tower_corridor_miles": 28.0, "cellular_internet_dependable": False},
    "amenities": ["Volcanic Ash Tuff Formations", "Owyhee Reservoir Access", "Boat Ramp Nearby", "Bighorn Sheep Habitat"],
    "location_scores": {"distance_to_groceries_score": 3, "distance_to_library_score": 3, "distance_to_gym_score": 2, "terrain_score": 10, "quietness_score": 10},
    "nearest_supply_towns": [{"town_name": "Jordan Valley, OR", "distance_miles": 35.0, "services_available": ["Gas Station", "Small Grocery", "Diner"]}, {"town_name": "Ontario, OR", "distance_miles": 65.0, "services_available": ["Superstores", "Hospital", "Hardware", "All Urban Services"]}],
    "seasonal_weather_effects": {"spring": "Mild spring (62-75°F) with wildflower blooms.", "summer": "Intense summer heat (95-105°F) inside canyon.", "fall": "Crisp pleasant autumn days.", "winter": "Cold winter (30-45°F) with mud on road."},
    "dangers_and_hazards": ["Flash Floods in Narrow Canyons", "Extreme Summer Heat", "Zero Cell Service"],
    "acoustic_environment": {"quietness_rating": "Volcanic Cathedral Quiet (Quietness Score: 10/10)", "common_human_made_sounds": ["Echoing canyon breeze", "Chukar calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Packard's Milkvetch", "Big Sagebrush", "Western Juniper"], "common_animals": ["California Bighorn Sheep", "Golden Eagle", "Chukar", "Coyote"]},
    "human_demographics_and_culture": "Owyhee canyonlands wilderness conservation and geology heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Northern Paiute legends honor the honeycomb volcanic spires as natural sacred columns.", "energetic_and_spiritual_features": "Towering red and pink ash spires creating cathedral-like natural acoustic resonance."},
    "nearby_hiking_trails": [{"trail_name": "Juniper Gulch Trail", "length_miles": 1.6, "difficulty": "Moderate", "features": "Honeycomb rock formations, rare desert plants, canyon walls"}],
    "public_reviews_summary": "Mind-blowing volcanic rock formations; zero cell service means absolute off-grid disconnection.",
    "other_data": "Do not enter canyon during severe flash flood warnings.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "oregon-008",
    "name": "Skull Hollow Dispersed Area - Crooked River National Grassland",
    "state": "Oregon",
    "county": "Jefferson",
    "coordinates": {"latitude": 44.4753, "longitude": -120.8261, "elevation_ft": 3100.0},
    "management_agency": {"name": "U.S. Forest Service - Crooked River National Grassland (Ochoco NF)", "type": "Federal", "phone": "(541) 416-6500", "website": "https://www.fs.usda.gov/ochoco"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive dispersed camping on adjacent grassland spur tracks)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed camping allowed on forest spur tracks surrounding Skull Hollow. Keep vehicles within 30 ft of roads. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from dry washes. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Strict USFS stage fire bans in dry summer/fall."},
    "access_and_road_conditions": {"road_type": "Paved road to graded gravel spurs", "road_conditions": "Paved Lone Pine Road leads to well-maintained gravel grassland spurs.", "vehicle_recommendation": "Accessible by low-clearance passenger cars and camper vans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 2, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "4 bars 4G LTE", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low - open juniper savanna plain", "distance_from_tower_corridor_miles": 6.8, "cellular_internet_dependable": True},
    "amenities": ["Proximity to Smith Rock State Park", "Juniper Savanna Views", "Trailhead Access", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 8, "distance_to_gym_score": 7, "terrain_score": 8, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Redmond, OR", "distance_miles": 14.0, "services_available": ["Fred Meyer", "Home Depot", "Hospital", "Gyms", "Restaurants"]}, {"town_name": "Prineville, OR", "distance_miles": 18.0, "services_available": ["Groceries", "Hardware Store", "Gas Stations", "Outdoor Supplies"]}],
    "seasonal_weather_effects": {"spring": "Lush high desert spring (60-72°F).", "summer": "Warm sunny summer (82-90°F) with cool nights.", "fall": "Crisp autumn weather (65-75°F).", "winter": "Cool winter (38-48°F) with light snow."},
    "dangers_and_hazards": ["Summer Wildfire Risk", "Rattlesnakes", "Ticks in Spring Brush"],
    "acoustic_environment": {"quietness_rating": "High Desert Savanna Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Occasional Lone Pine Road vehicle pass", "Coyote howling"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Western Juniper", "Big Sagebrush", "Bitterbrush", "Bluebunch Wheatgrass"], "common_animals": ["Mule Deer", "Coyote", "Golden Eagle", "Red-tailed Hawk"]},
    "human_demographics_and_culture": "Central Oregon rock climbing and high desert outdoor culture near Smith Rock.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Wasco and Paiute traditional hunting grounds.", "energetic_and_spiritual_features": "Panoramic views of Gray Butte radiating high desert clarity."},
    "nearby_hiking_trails": [{"trail_name": "Gray Butte Trail", "length_miles": 7.0, "difficulty": "Moderate", "features": "Juniper savanna, Smith Rock vistas, Cascade mountain panorama"}],
    "public_reviews_summary": "Perfect free basecamp for climbing at Smith Rock State Park with blazing 5G cell service.",
    "other_data": "3 miles from Smith Rock State Park entrance.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "oregon-009",
    "name": "Steens Mountain Loop Dispersed Area - BLM Burns",
    "state": "Oregon",
    "county": "Harney",
    "coordinates": {"latitude": 42.6375, "longitude": -118.5789, "elevation_ft": 7800.0},
    "management_agency": {"name": "Bureau of Land Management (BLM) - Burns District", "type": "Federal", "phone": "(541) 573-4400", "website": "https://www.blm.gov/oregon"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive BLM dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed camping allowed along Steens Mountain Loop Road outside designated fee campgrounds. Camp only in previously impacted pullouts."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to BLM fire bans during dry summer."},
    "access_and_road_conditions": {"road_type": "Gravel mountain loop road", "road_conditions": "Steep gravel mountain road reaching ~9,700 ft; closed by snow Oct-July.", "vehicle_recommendation": "High clearance 2WD/4WD required due to steep gravel grades and rocks.", "scores": {"road_grade": 8, "road_terrain_difficulty": 7, "supply_run_pain": 8}},
    "nomad_connectivity_rating": {"overall_rating": "Fair on Crest / Poor in Gorges (2.5/5 Stars)", "verizon_reliability": "2-3 bars 4G LTE on high ridges", "att_reliability": "1-2 bars 4G LTE on high ridges", "tmobile_reliability": "1 bar 4G LTE on high ridges", "terrain_obstruction_risk": "High in Kiger Gorge / Low on crest", "distance_from_tower_corridor_miles": 18.0, "cellular_internet_dependable": False},
    "amenities": ["Glacial U-Shaped Gorges View", "Subalpine Lakes", "Wild Mustang Herds", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 2, "distance_to_library_score": 2, "distance_to_gym_score": 1, "terrain_score": 10, "quietness_score": 10},
    "nearest_supply_towns": [{"town_name": "Frenchglen, OR", "distance_miles": 18.0, "services_available": ["Historic Hotel", "Small Store", "Gas Pump"]}, {"town_name": "Burns, OR", "distance_miles": 78.0, "services_available": ["Full Groceries", "Hospital", "Hardware", "Auto Repair"]}],
    "seasonal_weather_effects": {"spring": "Snow blocks road until late June/July.", "summer": "Cool subalpine summer (65-75°F).", "fall": "Crisp autumn foliage before snow arrives.", "winter": "Impassable; closed by heavy snow."},
    "dangers_and_hazards": ["Sudden Alpine Blizzards", "2,000-Foot Vertical Glacial Drop-offs", "Severe Brake Overheating"],
    "acoustic_environment": {"quietness_rating": "Subalpine Crest Silence (Quietness Score: 10/10)", "common_human_made_sounds": ["Mountain wind gusts", "Glacial stream flow"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Quaking Aspen", "Subalpine Sagebrush", "Mountain Big Sagebrush"], "common_animals": ["California Bighorn Sheep", "Wild Horses", "Mule Deer", "Elk", "Redband Trout"]},
    "human_demographics_and_culture": "Paiute traditional lands and historic Frenchglen livestock heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Paiute tradition reveres Steens Mountain as a sacred high mountain weather spine.", "energetic_and_spiritual_features": "30-mile massive fault-block mountain towering 5,000 feet above the Alvord Desert floor."},
    "nearby_hiking_trails": [{"trail_name": "Kiger Gorge Overlook Trail", "length_miles": 0.5, "difficulty": "Easy", "features": "Perpendicular view into 2,000-foot glacial U-shaped gorge"}],
    "public_reviews_summary": "Unrivaled alpine mountain scenery; summer only destination with usable ridge cell service.",
    "other_data": "Check road status in Frenchglen before driving upper loop.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "oregon-010",
    "name": "Lake Owyhee Overlook Dispersed - BLM Vale District",
    "state": "Oregon",
    "county": "Malheur",
    "coordinates": {"latitude": 43.6412, "longitude": -117.2348, "elevation_ft": 3200.0},
    "management_agency": {"name": "Bureau of Land Management (BLM) - Vale District", "type": "Federal", "phone": "(541) 473-3144", "website": "https://www.blm.gov/oregon"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive BLM dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free primitive dispersed camping on BLM ridge pullouts overlooking Lake Owyhee. Leave No Trace. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from high water line. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to BLM fire bans."},
    "access_and_road_conditions": {"road_type": "Gravel dirt plateau road", "road_conditions": "Unpaved gravel plateau road with loose rock near overlooks.", "vehicle_recommendation": "High clearance vehicle recommended due to rocky dirt tracks.", "scores": {"road_grade": 4, "road_terrain_difficulty": 5, "supply_run_pain": 5}},
    "nomad_connectivity_rating": {"overall_rating": "Great on Ridge (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "3 bars 4G LTE", "tmobile_reliability": "2-3 bars 4G LTE", "terrain_obstruction_risk": "Moderate", "distance_from_tower_corridor_miles": 16.0, "cellular_internet_dependable": True},
    "amenities": ["Lake Owyhee Panoramic Views", "Volcanic Canyon Rim", "Boating Access Nearby", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 5, "distance_to_library_score": 4, "distance_to_gym_score": 3, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Adrian, OR", "distance_miles": 24.0, "services_available": ["Gas Station", "Small Store", "Diner"]}, {"town_name": "Nyssa, OR", "distance_miles": 36.0, "services_available": ["Groceries", "Hardware Store", "Gas Stations", "Restaurants"]}],
    "seasonal_weather_effects": {"spring": "Mild spring (60-72°F).", "summer": "Warm to hot summer (88-98°F) with canyon winds.", "fall": "Crisp autumn weather (65-75°F).", "winter": "Cool winter (35-45°F)."},
    "dangers_and_hazards": ["Sheer Reservoir Cliff Drops", "High Canyon Winds", "Rattlesnakes"],
    "acoustic_environment": {"quietness_rating": "Reservoir Canyon Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Occasional distant motorboat hum", "Canyon wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Big Sagebrush", "Rabbitbrush", "Wheatgrass"], "common_animals": ["Bighorn Sheep", "Chukar", "Coyote", "Golden Eagle", "Bass"]},
    "human_demographics_and_culture": "Owyhee River fur trapper history and desert water reservoir culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Named after 1819 Hawaiian fur trappers who explored the wild canyon.", "energetic_and_spiritual_features": "Vast desert water basin contrasting against stark volcanic badland canyon walls."},
    "nearby_hiking_trails": [{"trail_name": "Owyhee Dam Overlook Trail", "length_miles": 2.0, "difficulty": "Easy to Moderate", "features": "Historic 1930s dam overlook, reservoir vistas"}],
    "public_reviews_summary": "Stunning clifftop lake views with surprisingly solid line-of-sight cell coverage across the Snake River plain.",
    "other_data": "Bring fresh drinking water.",
    "last_updated": "2026-09-12"
  }
])
save_state(ore, ore_path)
print("Updated Oregon -> 10 sites.")

# 3. Utah (+5 sites -> 10 total)
ut, ut_path = load_state("utah")
ut.extend([
  {
    "id": "utah-006",
    "name": "Valley of the Gods Dispersed Camping Area - BLM Monticello",
    "state": "Utah",
    "county": "San Juan",
    "coordinates": {"latitude": 37.2418, "longitude": -109.8164, "elevation_ft": 4800.0},
    "management_agency": {"name": "Bureau of Land Management (BLM) - Monticello Field Office", "type": "Federal", "phone": "(435) 587-1500", "website": "https://www.blm.gov/utah"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive BLM dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free primitive dispersed camping along 17-mile dirt loop road. Camp ONLY in designated pullouts with existing stone fire rings. Pack out all waste."},
    "waste_disposal_rules": {"poop_disposal": "Pack out human waste via wag-bag or portable toilet system (mandatory in Bears Ears BLM zone).", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Bring firewood; no wood gathering in desert.", "safety_requirements": "Campfires in cleared metal or stone rings. Extinguish cold.", "seasonal_fire_bans": "Subject to BLM stage fire bans in dry summer."},
    "access_and_road_conditions": {"road_type": "Unpaved dirt and gravel loop road", "road_conditions": "17-mile dirt loop road featuring sandy dry-wash crossings; ruts after heavy rain.", "vehicle_recommendation": "High clearance 2WD when dry; 4WD recommended after rain events.", "scores": {"road_grade": 4, "road_terrain_difficulty": 5, "supply_run_pain": 4}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "3 bars 4G LTE", "tmobile_reliability": "2 bars 4G LTE", "terrain_obstruction_risk": "Moderate near massive sandstone monoliths", "distance_from_tower_corridor_miles": 11.0, "cellular_internet_dependable": True},
    "amenities": ["Iconic Sandstone Butte Scenery", "17-Mile Scenic Dirt Loop", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 4, "distance_to_library_score": 4, "distance_to_gym_score": 2, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Mexican Hat, UT", "distance_miles": 10.0, "services_available": ["Gas Station", "Small Store", "Diner"]}, {"town_name": "Bluff, UT", "distance_miles": 22.0, "services_available": ["Groceries", "Cafes", "Gas Stations", "Outfitters"]}],
    "seasonal_weather_effects": {"spring": "Lush red rock spring (65-78°F).", "summer": "Extremely hot summer (95-104°F).", "fall": "Crisp pleasant autumn days.", "winter": "Cold freezing winter (35-48°F)."},
    "dangers_and_hazards": ["Flash Floods in Sandy Washes", "Extreme Summer Heat", "Lack of Water"],
    "acoustic_environment": {"quietness_rating": "Red Rock Monolith Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Occasional dirt loop car pass", "Desert wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Blackbrush", "Mormon Tea", "Prickly Pear", "Yucca"], "common_animals": ["Desert Bighorn Sheep", "Kit Fox", "Raven", "Lizard"]},
    "human_demographics_and_culture": "Diné (Navajo) sacred culture and Bears Ears red rock conservation heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Diné sacred tradition views the red sandstone monoliths as ancient frozen warriors guarding the land.", "energetic_and_spiritual_features": "Miniature Monument Valley landscape radiating intense red rock desert grounding energy."},
    "nearby_hiking_trails": [{"trail_name": "Valley of the Gods Loop Road Walk", "length_miles": 17.0, "difficulty": "Easy to Moderate", "features": "Battleship Butte, Rooster Butte, iconic sandstone spires"}],
    "public_reviews_summary": "Unbelievable red rock scenery rivaling Monument Valley for free with dependable Verizon cell signal.",
    "other_data": "Pack out ALL waste mandatory.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "utah-007",
    "name": "Wedge Overlook Dispersed Area - San Rafael Swell BLM",
    "state": "Utah",
    "county": "Emery",
    "coordinates": {"latitude": 39.0933, "longitude": -110.7589, "elevation_ft": 6200.0},
    "management_agency": {"name": "Bureau of Land Management (BLM) - Price Field Office", "type": "Federal", "phone": "(435) 636-3600", "website": "https://www.blm.gov/utah"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive BLM dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed camping allowed along canyon rim pullouts. Camp in existing disturbed pullouts. Pack out all waste."},
    "waste_disposal_rules": {"poop_disposal": "Pack out human waste via wag-bag or portable toilet system mandatory along canyon rim zone.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Bring firewood; no wood gathering on rim.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to BLM fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel access road", "road_conditions": "Smooth gravel Buckhorn Draw road for 20 miles from Castle Dale; clay ruts when wet.", "vehicle_recommendation": "Accessible by standard low-clearance FWD sedans when dry.", "scores": {"road_grade": 2, "road_terrain_difficulty": 2, "supply_run_pain": 4}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "3 bars 4G LTE", "tmobile_reliability": "2 bars 4G LTE", "terrain_obstruction_risk": "Low on high canyon rim", "distance_from_tower_corridor_miles": 15.0, "cellular_internet_dependable": True},
    "amenities": ["'Little Grand Canyon' Overlook Views", "San Rafael River Access Nearby", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 5, "distance_to_library_score": 5, "distance_to_gym_score": 3, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Castle Dale, UT", "distance_miles": 21.0, "services_available": ["Grocery Store", "Gas Stations", "Hardware", "Diner"]}, {"town_name": "Price, UT", "distance_miles": 48.0, "services_available": ["Full Urban Services", "Hospital", "Walmart", "Auto Repair"]}],
    "seasonal_weather_effects": {"spring": "Pleasant spring (60-74°F).", "summer": "Warm days (85-92°F) with canyon breezes.", "fall": "Crisp autumn weather (65-75°F).", "winter": "Cold freezing winter (28-42°F)."},
    "dangers_and_hazards": ["1,200-Foot Vertical Canyon Rim Drops", "Wind Gusts"],
    "acoustic_environment": {"quietness_rating": "Canyon Rim Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind blowing over canyon rim", "Distant river echo"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Piñon Pine", "Utah Juniper", "Mormon Tea", "Prickly Pear"], "common_animals": ["Desert Bighorn Sheep", "Mountain Lion", "Coyote", "Golden Eagle"]},
    "human_demographics_and_culture": "Fremont rock art culture and San Rafael Swell wilderness conservation.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Fremont culture pictographs in nearby Buckhorn Draw date back over 2,000 years.", "energetic_and_spiritual_features": "Dramatic 1,200-foot drop into the San Rafael River canyon canyonlands."},
    "nearby_hiking_trails": [{"trail_name": "Wedge Canyon Rim Trail", "length_miles": 4.0, "difficulty": "Easy", "features": "Little Grand Canyon views, petroglyph panels nearby"}],
    "public_reviews_summary": "Mind-boggling canyon view often called the Little Grand Canyon with rock-solid cell service.",
    "other_data": "Buckhorn Draw pictograph panel located 10 miles down canyon.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "utah-008",
    "name": "Sage Hen Dispersed Area - Little Sahara BLM",
    "state": "Utah",
    "county": "Juab",
    "coordinates": {"latitude": 39.7125, "longitude": -112.3856, "elevation_ft": 5100.0},
    "management_agency": {"name": "Bureau of Land Management (BLM) - Fillmore Field Office", "type": "Federal", "phone": "(435) 743-3100", "website": "https://www.blm.gov/utah"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive dispersed camping on BLM land outside fee gate)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping allowed on open BLM lands surrounding dune complex outside main OHV fee boundary. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from roads/dunes. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Bring firewood; gather dead down wood.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to BLM fire bans."},
    "access_and_road_conditions": {"road_type": "Paved access to gravel dirt tracks", "road_conditions": "Paved road leads to hard-packed dirt/gravel side pullouts.", "vehicle_recommendation": "Accessible by low-clearance 2WD on hard gravel; 4WD if pulling onto loose sand.", "scores": {"road_grade": 1, "road_terrain_difficulty": 3, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "3-4 bars 4G LTE", "tmobile_reliability": "3 bars 4G LTE", "terrain_obstruction_risk": "Low - open desert plain", "distance_from_tower_corridor_miles": 8.0, "cellular_internet_dependable": True},
    "amenities": ["Sand Dune Views", "Flat Open Parking", "OHV Trail Access Nearby", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 6, "distance_to_gym_score": 4, "terrain_score": 8, "quietness_score": 7},
    "nearest_supply_towns": [{"town_name": "Eureka, UT", "distance_miles": 22.0, "services_available": ["Gas Station", "Diner", "Convenience Store"]}, {"town_name": "Nephi, UT", "distance_miles": 32.0, "services_available": ["Groceries", "Hardware Store", "Medical Clinic", "Restaurants"]}],
    "seasonal_weather_effects": {"spring": "Mild spring (60-72°F).", "summer": "Warm to hot summer (88-96°F) on open sand.", "fall": "Crisp autumn weather (65-75°F).", "winter": "Cold winter (32-45°F)."},
    "dangers_and_hazards": ["Getting Stuck in Soft Sand", "High Wind Dust Storms"],
    "acoustic_environment": {"quietness_rating": "Desert Plain (Quietness Score: 7/10)", "common_human_made_sounds": ["Occasional distant OHV motor hum during weekends"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Big Sagebrush", "Indian Ricegrass", "Utah Juniper"], "common_animals": ["Kangaroo Rat", "Kit Fox", "Pronghorn Antelope", "Lizard"]},
    "human_demographics_and_culture": "Ancient Lake Bonneville sand dune geology and Great Basin OHV outdoor culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Remnant sand dunes deposited by wind from prehistoric Lake Bonneville 15,000 years ago.", "energetic_and_spiritual_features": "Vast rolling white sand dunes set against the blue Utah sky."},
    "nearby_hiking_trails": [{"trail_name": "White Sand Dune Ridge Hike", "length_miles": 3.0, "difficulty": "Moderate", "features": "Rolling sand dunes, Great Basin desert panorama"}],
    "public_reviews_summary": "Incredible dune scenery, super easy flat access, and lightning fast cell service.",
    "other_data": "Do not drive off hard tracks without checking sand depth.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "utah-009",
    "name": "Notch Peak / Tule Valley Dispersed - BLM Fillmore",
    "state": "Utah",
    "county": "Millard",
    "coordinates": {"latitude": 39.1412, "longitude": -113.3489, "elevation_ft": 5500.0},
    "management_agency": {"name": "Bureau of Land Management (BLM) - Fillmore Field Office", "type": "Federal", "phone": "(435) 743-3100", "website": "https://www.blm.gov/utah"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive BLM dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free primitive dispersed camping on open BLM desert lands at base of Notch Peak. Leave No Trace. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from dry washes. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to BLM fire bans."},
    "access_and_road_conditions": {"road_type": "Unpaved dirt wash access road", "road_conditions": "10 miles of dirt gravel wash road off US-50/6; rocky with ruts.", "vehicle_recommendation": "High clearance 2WD/4WD recommended.", "scores": {"road_grade": 5, "road_terrain_difficulty": 6, "supply_run_pain": 8}},
    "nomad_connectivity_rating": {"overall_rating": "Weak / Spotty (2/5 Stars)", "verizon_reliability": "1-2 bars 4G LTE (Elevated ground only)", "att_reliability": "1 bar 4G LTE", "tmobile_reliability": "0-1 bar (No Data)", "terrain_obstruction_risk": "High beneath 2,200-foot Notch Peak cliff wall", "distance_from_tower_corridor_miles": 26.0, "cellular_internet_dependable": False},
    "amenities": ["2,200-Foot Vertical Cliff View", "Bristlecone Pine Forest Nearby", "Dark Sky Astronomy", "Wilderness Solitude"],
    "location_scores": {"distance_to_groceries_score": 2, "distance_to_library_score": 2, "distance_to_gym_score": 1, "terrain_score": 10, "quietness_score": 10},
    "nearest_supply_towns": [{"town_name": "Delta, UT", "distance_miles": 50.0, "services_available": ["Full Groceries", "Hospital", "Gas Stations", "Hardware Store"]}],
    "seasonal_weather_effects": {"spring": "Mild spring (60-72°F).", "summer": "Hot summer (92-100°F) in valley.", "fall": "Crisp autumn hiking days.", "winter": "Cold winter (30-42°F)."},
    "dangers_and_hazards": ["Extreme Solitude", "Flash Floods in Sawtooth Canyon", "2,200-Foot Cliff Drop-offs"],
    "acoustic_environment": {"quietness_rating": "Profound Great Basin Silence (Quietness Score: 10/10)", "common_human_made_sounds": ["Absolute mountain silence", "Cliff wind Echoes"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Ancient Bristlecone Pine", "Utah Juniper", "Piñon Pine", "Sagebrush"], "common_animals": ["Desert Bighorn Sheep", "Golden Eagle", "Mountain Lion", "Coyote"]},
    "human_demographics_and_culture": "Great Basin wilderness exploration and geology heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Second highest pure vertical cliff drop in North America behind El Capitan.", "energetic_and_spiritual_features": "2,200-foot sheer vertical limestone wall looming directly overhead."},
    "nearby_hiking_trails": [{"trail_name": "Notch Peak Summit Trail", "length_miles": 9.0, "difficulty": "Strenuous", "features": "Sawtooth Canyon, ancient bristlecone pines, 2,200-ft cliff edge"}],
    "public_reviews_summary": "One of the most awe-inspiring vertical cliffs in America; remote off-grid solitude requires Starlink for connectivity.",
    "other_data": "Carry plenty of water for summit hike.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "utah-010",
    "name": "Nine Mile Canyon Dispersed Area - BLM Price & Vernal",
    "state": "Utah",
    "county": "Carbon",
    "coordinates": {"latitude": 39.7754, "longitude": -110.4512, "elevation_ft": 5600.0},
    "management_agency": {"name": "Bureau of Land Management (BLM) - Price Field Office", "type": "Federal", "phone": "(435) 636-3600", "website": "https://www.blm.gov/utah"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive BLM dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed camping allowed on BLM side pullouts. Strictly illegal to touch, deface, or camp under rock art panels. Leave No Trace."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Nine Mile Creek. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Bring firewood; do not gather wood from historic sites.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to BLM fire bans."},
    "access_and_road_conditions": {"road_type": "Paved main canyon road to gravel spurs", "road_conditions": "Paved main canyon road with gravel side canyon pullouts.", "vehicle_recommendation": "Accessible by all low-clearance vehicles on main paved road.", "scores": {"road_grade": 1, "road_terrain_difficulty": 2, "supply_run_pain": 5}},
    "nomad_connectivity_rating": {"overall_rating": "Poor inside Canyon (2/5 Stars)", "verizon_reliability": "1-2 bars 4G LTE (Spotty)", "att_reliability": "1 bar 4G LTE", "tmobile_reliability": "0-1 bar (No Data)", "terrain_obstruction_risk": "High inside 1,000-foot sandstone canyon walls", "distance_from_tower_corridor_miles": 20.0, "cellular_internet_dependable": False},
    "amenities": ["'World's Longest Art Gallery' (10,000+ Petroglyphs)", "Paved Scenic Drive", "Fremont Culture Ruins", "Stream Side Camping"],
    "location_scores": {"distance_to_groceries_score": 4, "distance_to_library_score": 4, "distance_to_gym_score": 2, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Wellington, UT", "distance_miles": 28.0, "services_available": ["Gas Station", "Diner", "Convenience Store"]}, {"town_name": "Price, UT", "distance_miles": 36.0, "services_available": ["Full Urban Services", "Hospital", "Walmart", "Auto Repair"]}],
    "seasonal_weather_effects": {"spring": "Mild spring (60-72°F).", "summer": "Warm summer (88-95°F) with canyon downdrafts.", "fall": "Crisp autumn foliage.", "winter": "Cold winter (28-40°F)."},
    "dangers_and_hazards": ["Flash Floods in Narrow Side Canyons", "Coal Truck Traffic on Road"],
    "acoustic_environment": {"quietness_rating": "Canyon Wall Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Occasional passing vehicle", "Creek flow"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Cottonwood", "Piñon Pine", "Utah Juniper", "Willow"], "common_animals": ["Elk", "Mule Deer", "Wild Turkey", "Bighorn Sheep"]},
    "human_demographics_and_culture": "Fremont and Ute ancestral petroglyph culture spanning thousands of years.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Contains over 10,000 ancient Fremont and Ute rock art images including the famous 'Great Hunt' panel.", "energetic_and_spiritual_features": "Sacred rock art gallery walls carved into sandstone over 1,500 years."},
    "nearby_hiking_trails": [{"trail_name": "Cottonwood Canyon Rock Art Walk", "length_miles": 2.0, "difficulty": "Easy", "features": "Ancient Fremont pictographs, cliff alcoves"}],
    "public_reviews_summary": "World-class archaeological petroglyph canyon; cell service is spotty inside canyon bottom.",
    "other_data": "Never touch petroglyphs or use wet rags on rock art.",
    "last_updated": "2026-09-12"
  }
])
save_state(ut, ut_path)
print("Updated Utah -> 10 sites.")

# 4. Washington (+5 sites -> 10 total)
wa, wa_path = load_state("washington")
wa.extend([
  {
    "id": "washington-006",
    "name": "Smackout Pass Dispersed Camping - Colville National Forest",
    "state": "Washington",
    "county": "Pend Oreille",
    "coordinates": {"latitude": 48.7845, "longitude": -117.5123, "elevation_ft": 3600.0},
    "management_agency": {"name": "U.S. Forest Service - Colville National Forest", "type": "Federal", "phone": "(509) 442-3141", "website": "https://www.fs.usda.gov/colville"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed camping allowed along Forest Service roads. Food storage rules strictly enforced due to Grizzly bear recovery zone. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy. Bear canister mandatory."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Graded gravel Forest Service road (FR 1900); minor potholes.", "vehicle_recommendation": "Accessible by standard low-clearance FWD sedans.", "scores": {"road_grade": 2, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Good (3.5/5 Stars)", "verizon_reliability": "2-3 bars 4G LTE", "att_reliability": "2 bars 4G LTE", "tmobile_reliability": "1-2 bars 4G LTE", "terrain_obstruction_risk": "Moderate under dense timber canopy", "distance_from_tower_corridor_miles": 12.0, "cellular_internet_dependable": True},
    "amenities": ["Cedar & Pine Forest Canopy", "Mountain Meadow Solitude", "Huckleberry Picking", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 6, "distance_to_library_score": 5, "distance_to_gym_score": 4, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Ione, WA", "distance_miles": 12.0, "services_available": ["Gas Station", "General Store", "Cafe", "Post Office"]}, {"town_name": "Colville, WA", "distance_miles": 45.0, "services_available": ["Full City Services", "Walmart", "Hospital", "Hardware"]}],
    "seasonal_weather_effects": {"spring": "Rainy mountain spring (52-64°F).", "summer": "Pleasant sunny summer (75-85°F).", "fall": "Crisp autumn days.", "winter": "Snow blocks pass Nov-May."},
    "dangers_and_hazards": ["Grizzly and Black Bear Habitat", "Moose Encounters", "Winter Snow Blockage"],
    "acoustic_environment": {"quietness_rating": "Northwest Forest Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind through tall cedar canopy", "Bird calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Western Red Cedar", "Douglas Fir", "Huckleberry", "Sword Fern"], "common_animals": ["Grizzly Bear", "Black Bear", "Gray Wolf", "Moose", "Lynx"]},
    "human_demographics_and_culture": "Kalispel Tribe traditional territory and Selkirk mountain timber culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Traditional huckleberry harvesting and medicine gathering grounds of the Kalispel Tribe.", "energetic_and_spiritual_features": "Deep ancient cedar forest canopy providing profound tranquility."},
    "nearby_hiking_trails": [{"trail_name": "Smackout Pass Trail", "length_miles": 3.5, "difficulty": "Easy to Moderate", "features": "Ancient cedar groves, huckleberry patches, mountain views"}],
    "public_reviews_summary": "Peaceful lush mountain forest with usable cell service in elevated clearings.",
    "other_data": "Certified bear canister or food hanging mandatory.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "washington-007",
    "name": "Toats Coulee Dispersed Area - Okanogan National Forest",
    "state": "Washington",
    "county": "Okanogan",
    "coordinates": {"latitude": 48.8812, "longitude": -119.7418, "elevation_ft": 2800.0},
    "management_agency": {"name": "U.S. Forest Service - Okanogan-Wenatchee NF", "type": "Federal", "phone": "(509) 486-2186", "website": "https://www.fs.usda.gov/okawen"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed camping allowed along Toats Coulee Creek forest road. Keep camp 100 ft back from creek bank. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from creek. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel forest road", "road_conditions": "Well-maintained Forest Service gravel road.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars.", "scores": {"road_grade": 2, "road_terrain_difficulty": 2, "supply_run_pain": 4}},
    "nomad_connectivity_rating": {"overall_rating": "Fair / Spotty (2.5/5 Stars)", "verizon_reliability": "2-3 bars 4G LTE", "att_reliability": "2 bars 4G LTE", "tmobile_reliability": "1-2 bars 4G LTE", "terrain_obstruction_risk": "Moderate inside coulee canyon", "distance_from_tower_corridor_miles": 14.0, "cellular_internet_dependable": False},
    "amenities": ["Creek Side Camping", "Aspen & Ponderosa Canopy", " Pasayten Wilderness Gateway", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 5, "distance_to_library_score": 4, "distance_to_gym_score": 3, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Loomis, WA", "distance_miles": 8.0, "services_available": ["General Store", "Gas Pump", "Tavern"]}, {"town_name": "Tonasket, WA", "distance_miles": 26.0, "services_available": ["Groceries", "Hardware Store", "Gas Stations", "Medical Clinic"]}],
    "seasonal_weather_effects": {"spring": "Sunny dry spring (60-72°F).", "summer": "Warm sunny summer (82-90°F).", "fall": "Crisp autumn foliage.", "winter": "Cold winter (25-38°F) with snow."},
    "dangers_and_hazards": ["Late Summer Wildfire Risk", "Black Bears", "Rattlesnakes in Lower Coulee"],
    "acoustic_environment": {"quietness_rating": "Mountain Creek Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Creek water flow", "Wind through ponderosas"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Ponderosa Pine", "Quaking Aspen", "Douglas Fir"], "common_animals": ["Mule Deer", "Black Bear", "Bighorn Sheep", "Rainbow Trout"]},
    "human_demographics_and_culture": "Okanogan valley gold mining and ranching heritage.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Okanogan tribe traditional valley hunting grounds.", "energetic_and_spiritual_features": "Pristine mountain stream flowing through dry interior forest coulee."},
    "nearby_hiking_trails": [{"trail_name": "Toats Coulee Creek Trail", "length_miles": 4.0, "difficulty": "Easy to Moderate", "features": "Creek side walking, aspen groves, bighorn sheep viewing"}],
    "public_reviews_summary": "Gorgeous creek side camping gateway to the Pasayten Wilderness; spotty cell service.",
    "other_data": "Bring fishing rod for creek trout.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "washington-008",
    "name": "Middle Fork Snoqualmie Dispersed Area - Mount Baker-Snoqualmie NF",
    "state": "Washington",
    "county": "King",
    "coordinates": {"latitude": 47.5512, "longitude": -121.5412, "elevation_ft": 1100.0},
    "management_agency": {"name": "U.S. Forest Service - Mount Baker-Snoqualmie NF", "type": "Federal", "phone": "(425) 888-1421", "website": "https://www.fs.usda.gov/mbs"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping in pullouts beyond paved section)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed camping allowed in designated pullouts along Middle Fork Road past paved corridor. Pack out all garbage."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Snoqualmie River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Paved road transitioning to smooth gravel", "road_conditions": "Paved for first 12 miles; smooth gravel pullouts beyond.", "vehicle_recommendation": "Accessible by all low-clearance FWD sedans.", "scores": {"road_grade": 1, "road_terrain_difficulty": 1, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "3 bars 4G LTE", "tmobile_reliability": "2-3 bars 4G LTE", "terrain_obstruction_risk": "Moderate under tall rainforest canopy", "distance_from_tower_corridor_miles": 10.0, "cellular_internet_dependable": True},
    "amenities": ["Old-Growth Rainforest Canopy", "River Swimming & Kayaking", "Close to Seattle Metro", "Trailhead Access"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 8, "distance_to_gym_score": 7, "terrain_score": 9, "quietness_score": 7},
    "nearest_supply_towns": [{"town_name": "North Bend, WA", "distance_miles": 14.0, "services_available": ["Full Groceries", "Gas Stations", "Gear Shops", "Urgent Care"]}, {"town_name": "Seattle, WA", "distance_miles": 42.0, "services_available": ["Major Metropolitan Services"]}],
    "seasonal_weather_effects": {"spring": "Lush rainy spring (55-65°F).", "summer": "Mild sunny summer (72-80°F).", "fall": "Rainy autumn with glowing bigleaf maples.", "winter": "Cool rainy winter (38-45°F)."},
    "dangers_and_hazards": ["Swift River Currents", "Falling Tree Branches during Storms", "Black Bears"],
    "acoustic_environment": {"quietness_rating": "Temperate Rainforest (Quietness Score: 7/10)", "common_human_made_sounds": ["Occasional hiker car pass", "Snoqualmie River roar"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Douglas Fir", "Western Hemlock", "Mossy Bigleaf Maple", "Sword Fern"], "common_animals": ["Roosevelt Elk", "Black Bear", "Bald Eagle", "Salmon"]},
    "human_demographics_and_culture": "Snoqualmie Tribe ancestral heritage and Cascade rainforest outdoor recreation culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Snoqualmie Tribe sacred traditions honor the river valley as ancestral life source.", "energetic_and_spiritual_features": "Giant moss-draped old growth hemlock trees creating deep rainforest stillness."},
    "nearby_hiking_trails": [{"trail_name": "Middle Fork Snoqualmie River Trail", "length_miles": 6.0, "difficulty": "Easy to Moderate", "features": "Old-growth rainforest, river suspension bridges, mountain views"}],
    "public_reviews_summary": "Unbelievable old-growth rainforest camping under an hour from Seattle with dependable cell service.",
    "other_data": "Extremely popular on summer weekends.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "washington-009",
    "name": "Babyshoe Pass Dispersed Area - Gifford Pinchot NF",
    "state": "Washington",
    "county": "Skamania",
    "coordinates": {"latitude": 46.2214, "longitude": -121.5889, "elevation_ft": 4300.0},
    "management_agency": {"name": "U.S. Forest Service - Gifford Pinchot NF", "type": "Federal", "phone": "(509) 395-3400", "website": "https://www.fs.usda.gov/giffordpinchot"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed primitive camping along Forest Road 23 near Babyshoe Pass. Camp in established turnouts. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Paved forest road to gravel spurs", "road_conditions": "Paved and hard-packed gravel Forest Road 23.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars.", "scores": {"road_grade": 2, "road_terrain_difficulty": 2, "supply_run_pain": 5}},
    "nomad_connectivity_rating": {"overall_rating": "Fair / Spotty (2.5/5 Stars)", "verizon_reliability": "2-3 bars 4G LTE", "att_reliability": "2 bars 4G LTE", "tmobile_reliability": "1-2 bars 4G LTE", "terrain_obstruction_risk": "Moderate under high mountain forest canopy", "distance_from_tower_corridor_miles": 15.0, "cellular_internet_dependable": False},
    "amenities": ["Mount Adams Volcano Views", "Huckleberry Fields", "Subalpine Meadows", "PCT Access Nearby"],
    "location_scores": {"distance_to_groceries_score": 4, "distance_to_library_score": 4, "distance_to_gym_score": 3, "terrain_score": 10, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Trout Lake, WA", "distance_miles": 16.0, "services_available": ["General Store", "Gas Station", "Cafe"]}, {"town_name": "White Salmon, WA", "distance_miles": 42.0, "services_available": ["Full Groceries", "Gear Shops", "Hospital", "Restaurants"]}],
    "seasonal_weather_effects": {"spring": "Snow blocks pass until June.", "summer": "Pleasant alpine summer (70-78°F).", "fall": "Crisp autumn huckleberry season.", "winter": "Impassable; heavy snow."},
    "dangers_and_hazards": ["Active Volcano Proximity (Mt. Adams)", "Black Bears", "Snow Blockage into June"],
    "acoustic_environment": {"quietness_rating": "Subalpine Cascade Quiet (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind through noble fir canopy", "Bird calls"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Noble Fir", "Mountain Hemlock", "Huckleberry", "Beargrass"], "common_animals": ["Elk", "Black Bear", "Cascade Frog", "Pika"]},
    "human_demographics_and_culture": "Yakama Nation traditional territory and Cascade volcano outdoor climbing culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Yakama Nation tradition reveres Mount Adams (Pahto) as a sacred medicine mountain.", "energetic_and_spiritual_features": "Panoramic views of Mount Adams snowcap looming over subalpine meadows."},
    "nearby_hiking_trails": [{"trail_name": "Pacific Crest Trail (Babyshoe Pass Section)", "length_miles": 5.0, "difficulty": "Moderate", "features": "PCT alpine ridge hike, Mount Adams vistas, huckleberry fields"}],
    "public_reviews_summary": "Incredible Mount Adams volcano views and huckleberry picking with spotty cell service.",
    "other_data": "PCT hikers frequently pass through in late summer.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "washington-010",
    "name": "Yakima River Canyon Dispersed Area - BLM Wenatchee",
    "state": "Washington",
    "county": "Kittitas",
    "coordinates": {"latitude": 46.8123, "longitude": -120.4612, "elevation_ft": 1400.0},
    "management_agency": {"name": "Bureau of Land Management (BLM) - Wenatchee Field Office", "type": "Federal", "phone": "(509) 665-2100", "website": "https://www.blm.gov/washington"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive BLM dispersed camping on ridge roads above canyon)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free primitive dispersed camping on BLM ridge lands above the canyon outside fee recreation sites. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from canyon rim. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Bring firewood; no wood gathering in cheatgrass.", "safety_requirements": "Campfires strictly contained in metal fire pans. Douse cold.", "seasonal_fire_bans": "Extremely strict BLM summer burn bans due to high cheatgrass wildfire hazard."},
    "access_and_road_conditions": {"road_type": "Paved canyon road to dirt ridge tracks", "road_conditions": "Paved SR-821 leads to steep dirt/gravel ridge pullouts.", "vehicle_recommendation": "High clearance 2WD/4WD recommended for top ridge pullouts.", "scores": {"road_grade": 4, "road_terrain_difficulty": 5, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "3-4 bars 4G LTE", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low on high ridge tops", "distance_from_tower_corridor_miles": 5.5, "cellular_internet_dependable": True},
    "amenities": ["Basalt Canyon Rim Views", "Yakima River Fishing Nearby", "Bighorn Sheep Habitat", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 8, "distance_to_gym_score": 7, "terrain_score": 9, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Ellensburg, WA", "distance_miles": 12.0, "services_available": ["CWU Campus", "Full Groceries", "Hospital", "Hardware", "Gyms"]}, {"town_name": "Yakima, WA", "distance_miles": 22.0, "services_available": ["Regional Urban Services", "Airport", "Medical Centers"]}],
    "seasonal_weather_effects": {"spring": "Lush green canyon spring (62-74°F).", "summer": "Warm to hot summer (85-95°F) with bright sun.", "fall": "Crisp golden autumn days.", "winter": "Cool winter (35-45°F)."},
    "dangers_and_hazards": ["High Summer Wildfire Hazard", "Rattlesnakes", "High Canyon Winds"],
    "acoustic_environment": {"quietness_rating": "Basalt Canyon Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Distant SR-821 vehicle pass", "Canyon wind"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Big Sagebrush", "Bluebunch Wheatgrass", "Cheatgrass"], "common_animals": ["Rocky Mountain Bighorn Sheep", "Golden Eagle", "Blueback Trout", "Coyote"]},
    "human_demographics_and_culture": "Yakama Nation ancestral territory and Columbia Basin fly fishing culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Deep basalt gorge carved through Columbia River basalt flows over millions of years.", "energetic_and_spiritual_features": "High ridge overlooks commanding 360-degree views of the Yakima River canyon."},
    "nearby_hiking_trails": [{"trail_name": "Umtanum Creek Canyon Trail", "length_miles": 3.0, "difficulty": "Easy to Moderate", "features": "Suspension bridge over Yakima River, basalt canyon walls, apple orchards"}],
    "public_reviews_summary": "Incredible desert canyon sunset views and world-class blue-ribbon fly fishing with blazing 5G cell service.",
    "other_data": "Extremely strict summer campfire bans enforced.",
    "last_updated": "2026-09-12"
  }
])
save_state(wa, wa_path)
print("Updated Washington -> 10 sites.")

# 5. Wyoming (+5 sites -> 10 total)
wy, wy_path = load_state("wyoming")
wy.extend([
  {
    "id": "wyoming-006",
    "name": "Vedauwoo Dispersed Area - Medicine Bow National Forest",
    "state": "Wyoming",
    "county": "Albany",
    "coordinates": {"latitude": 41.1612, "longitude": -105.3789, "elevation_ft": 8000.0},
    "management_agency": {"name": "U.S. Forest Service - Medicine Bow NF", "type": "Federal", "phone": "(307) 745-2300", "website": "https://www.fs.usda.gov/mbnf"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping outside recreation fee boundary)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed camping allowed on Forest Service lands outside developed Vedauwoo fee campground. Camp in existing pullouts. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from rock formations. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Gravel forest road", "road_conditions": "Gravel forest roads off I-80; smooth with minor washboard.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars.", "scores": {"road_grade": 2, "road_terrain_difficulty": 2, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "3-4 bars 4G LTE", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low to Moderate around granite domes", "distance_from_tower_corridor_miles": 5.0, "cellular_internet_dependable": True},
    "amenities": ["Granite Dome Rock Climbing", "Iconic Sherman Granite Formations", "Aspen Groves", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 8, "distance_to_gym_score": 7, "terrain_score": 10, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Laramie, WY", "distance_miles": 16.0, "services_available": ["UW Campus", "Full Groceries", "Hospital", "Gear Shops"]}, {"town_name": "Cheyenne, WY", "distance_miles": 30.0, "services_available": ["State Capital Services", "Full Urban Amenities"]}],
    "seasonal_weather_effects": {"spring": "Cool windy spring (48-60°F).", "summer": "Crisp mountain summer (70-80°F).", "fall": "Golden autumn aspens.", "winter": "Snow blocks forest roads; freezing cold."},
    "dangers_and_hazards": ["High Wind Gusts", "Summer Afternoon Lightning", "Severe Cold outside Summer"],
    "acoustic_environment": {"quietness_rating": "Granite Dome Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Distant I-80 freeway hum", "Climber voices"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Quaking Aspen", "Lodgepole Pine", "Limber Pine", "Sherman Granite"], "common_animals": ["Moose", "Mule Deer", "Pronghorn Antelope", "Bobcat"]},
    "human_demographics_and_culture": "Arapaho and Cheyenne indigenous history and rock climbing outdoors culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Sacred place to Arapaho and Cheyenne peoples known as 'Land of the Earthborn Spirits'.", "energetic_and_spiritual_features": "1.4 billion-year-old weathered granite domes radiating ancient geological power."},
    "nearby_hiking_trails": [{"trail_name": "Turtle Rock Trail", "length_miles": 2.8, "difficulty": "Easy to Moderate", "features": "Granite bouldering domes, aspen groves, beaver ponds"}],
    "public_reviews_summary": "World-class rock climbing landscape right off I-80 with lightning fast cell service.",
    "other_data": "High winds common year-round.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "wyoming-007",
    "name": "Upper Green River Dispersed Area - Bridger-Teton NF",
    "state": "Wyoming",
    "county": "Sublette",
    "coordinates": {"latitude": 43.2845, "longitude": -109.9812, "elevation_ft": 7800.0},
    "management_agency": {"name": "U.S. Forest Service - Bridger-Teton NF", "type": "Federal", "phone": "(307) 367-4326", "website": "https://www.fs.usda.gov/btnf"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive USFS dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed camping allowed along Green River Lakes road (FR 600). Food storage rules strictly enforced due to Grizzly bear territory. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from Green River. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy. Bear canister mandatory."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to USFS stage fire bans."},
    "access_and_road_conditions": {"road_type": "Unpaved washboard gravel forest road", "road_conditions": "25 miles of unpaved washboard gravel road off US-191.", "vehicle_recommendation": "Accessible by low-clearance 2WD passenger cars in summer.", "scores": {"road_grade": 3, "road_terrain_difficulty": 4, "supply_run_pain": 7}},
    "nomad_connectivity_rating": {"overall_rating": "No Service (1/5 Stars)", "verizon_reliability": "0-1 bar (Weak/No Data)", "att_reliability": "0 bars", "tmobile_reliability": "0 bars", "terrain_obstruction_risk": "High in deep river valley beneath Wind River peaks", "distance_from_tower_corridor_miles": 32.0, "cellular_internet_dependable": False},
    "amenities": ["Squaretop Mountain Views", "Green River Fly Fishing", "Wind River Wilderness Gateway", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 3, "distance_to_library_score": 3, "distance_to_gym_score": 2, "terrain_score": 10, "quietness_score": 10},
    "nearest_supply_towns": [{"town_name": "Pinedale, WY", "distance_miles": 38.0, "services_available": ["Groceries", "Hardware Store", "Outfitters", "Medical Clinic", "Restaurants"]}],
    "seasonal_weather_effects": {"spring": "Snow blocks road until June.", "summer": "Pristine mountain summer (70-78°F) with crisp nights (35°F).", "fall": "Crisp autumn foliage before snow.", "winter": "Impassable; heavy snow."},
    "dangers_and_hazards": ["Grizzly and Black Bear Territory", "High Altitude Cold", "Extreme Remote Distance"],
    "acoustic_environment": {"quietness_rating": "Wind River Wilderness Silence (Quietness Score: 10/10)", "common_human_made_sounds": ["Green River water flow", "Wind through lodgepole pines"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Lodgepole Pine", "Engelmann Spruce", "Quaking Aspen"], "common_animals": ["Grizzly Bear", "Gray Wolf", "Moose", "Trumpeter Swan", "Cutthroat Trout"]},
    "human_demographics_and_culture": "Mountain man fur trapper Rendezvous history and Wind River wilderness conservation.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Headwaters of the 730-mile Green River; historic 1830s mountain man rendezvous grounds.", "energetic_and_spiritual_features": "Squaretop Mountain sheer glacial peak looming over pristine emerald lake waters."},
    "nearby_hiking_trails": [{"trail_name": "Green River Lakes Loop Trail", "length_miles": 4.5, "difficulty": "Easy to Moderate", "features": "Glacial lake shore, Squaretop Mountain reflections, cutthroat trout fishing"}],
    "public_reviews_summary": "One of the most postcard-perfect mountain landscapes in North America; zero cell service requires Starlink.",
    "other_data": "Certified bear canisters or food hanging mandatory.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "wyoming-008",
    "name": "Red Gulch Dispersed Camping Area - BLM Worland",
    "state": "Wyoming",
    "county": "Big Horn",
    "coordinates": {"latitude": 44.2812, "longitude": -107.8214, "elevation_ft": 4500.0},
    "management_agency": {"name": "Bureau of Land Management (BLM) - Worland Field Office", "type": "Federal", "phone": "(307) 347-5100", "website": "https://www.blm.gov/wyoming"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive BLM dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free primitive dispersed camping on BLM land along Red Gulch Byway. Protect dinosaur tracksite fossils. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from dry gullies. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Bring firewood; no wood gathering in badlands.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to BLM fire bans."},
    "access_and_road_conditions": {"road_type": "Unpaved gravel and clay scenic byway", "road_conditions": "32-mile unpaved gravel and clay scenic byway; bentonite clay impassable when wet.", "vehicle_recommendation": "High clearance 2WD/4WD recommended.", "scores": {"road_grade": 4, "road_terrain_difficulty": 6, "supply_run_pain": 6}},
    "nomad_connectivity_rating": {"overall_rating": "Great on Ridge (4/5 Stars)", "verizon_reliability": "3-4 bars 4G LTE", "att_reliability": "2 bars 4G LTE", "tmobile_reliability": "1-2 bars 4G LTE", "terrain_obstruction_risk": "Moderate in badland canyons", "distance_from_tower_corridor_miles": 18.0, "cellular_internet_dependable": True},
    "amenities": ["Red Rock Canyon Badlands", "Dinosaur Trackway Nearby", "Red Gulch Scenic Byway", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 4, "distance_to_library_score": 4, "distance_to_gym_score": 2, "terrain_score": 9, "quietness_score": 9},
    "nearest_supply_towns": [{"town_name": "Greybull, WY", "distance_miles": 22.0, "services_available": ["Groceries", "Gas Station", "Hardware", "Diner"]}, {"town_name": "Worland, WY", "distance_miles": 38.0, "services_available": ["Full Groceries", "Hospital", "Gas Stations", "Auto Parts"]}],
    "seasonal_weather_effects": {"spring": "Mild spring (60-72°F).", "summer": "Warm to hot summer (88-95°F) with zero shade.", "fall": "Crisp autumn weather (65-75°F).", "winter": "Cold winter (25-38°F)."},
    "dangers_and_hazards": ["Bentonite Clay Slick Roads when Wet", "Flash Floods in Badlands", "Zero Shade"],
    "acoustic_environment": {"quietness_rating": "Badland Canyon Silence (Quietness Score: 9/10)", "common_human_made_sounds": ["Wind blowing through red rock canyons"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Utah Juniper", "Big Sagebrush", "Wild Buckwheat"], "common_animals": ["Pronghorn Antelope", "Horned Lizard", "Golden Eagle", "Coyote"]},
    "human_demographics_and_culture": "Middle Jurassic paleontology heritage and Bighorn Basin ranching culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Site of 167-million-year-old Middle Jurassic dinosaur footprints preserved in limestone.", "energetic_and_spiritual_features": "Vast red canyon badlands revealing millions of years of earth history."},
    "nearby_hiking_trails": [{"trail_name": "Dinosaur Trackway Boardwalk Hike", "length_miles": 0.8, "difficulty": "Easy", "features": "Middle Jurassic dinosaur footprints in limestone bed"}],
    "public_reviews_summary": "Surreal red rock badlands with real dinosaur tracks and solid ridge cell service.",
    "other_data": "Never drive on bentonite road during heavy rain.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "wyoming-009",
    "name": "Muddy Mountain Dispersed Area - BLM Casper",
    "state": "Wyoming",
    "county": "Natrona",
    "coordinates": {"latitude": 42.6612, "longitude": -106.2845, "elevation_ft": 8200.0},
    "management_agency": {"name": "Bureau of Land Management (BLM) - Casper Field Office", "type": "Federal", "phone": "(307) 261-7600", "website": "https://www.blm.gov/wyoming"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive BLM dispersed camping outside developed campgrounds)", "stay_limit": "14 days maximum stay limit", "guidelines": "Dispersed camping allowed on BLM lands along Muddy Mountain Road outside fee campgrounds. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from streams. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to BLM fire bans."},
    "access_and_road_conditions": {"road_type": "Paved road transitioning to graded gravel", "road_conditions": "Paved Casper Mountain road transitioning to well-graded gravel Muddy Mountain road.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars in summer.", "scores": {"road_grade": 2, "road_terrain_difficulty": 2, "supply_run_pain": 3}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "3-4 bars 4G LTE", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low on mountain plateau", "distance_from_tower_corridor_miles": 7.0, "cellular_internet_dependable": True},
    "amenities": ["Cool Mountain Pine Forest", "Casper City Lights Overlook Views", "Interpretive Trails", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 7, "distance_to_library_score": 7, "distance_to_gym_score": 6, "terrain_score": 9, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Casper, WY", "distance_miles": 20.0, "services_available": ["Full Urban Services", "Hospital", "Walmart", "REI", "Regional Airport"]}],
    "seasonal_weather_effects": {"spring": "Snow blocks road until late May.", "summer": "Cool mountain summer (70-78°F).", "fall": "Crisp mountain autumn.", "winter": "Impassable; heavy snow."},
    "dangers_and_hazards": ["Sudden Mountain Thunderstorms", "Black Bears"],
    "acoustic_environment": {"quietness_rating": "Mountain Forest Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Wind through lodgepole pine canopy", "Distant city lightglow"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Lodgepole Pine", "Subalpine Fir", "Quaking Aspen", "Mountain Meadows"], "common_animals": ["Elk", "Mule Deer", "Wild Turkey", "Black Bear"]},
    "human_demographics_and_culture": "Oregon Trail history and Casper outdoor recreation culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Prominent mountain landmark overlooking historic Oregon and Mormon emigrant trails.", "energetic_and_spiritual_features": "High elevation mountain plateau escape offering 360-degree views of the North Platte river valley."},
    "nearby_hiking_trails": [{"trail_name": "Rim Rock Interpretive Trail", "length_miles": 2.0, "difficulty": "Easy", "features": "Pine forest, limestone rim cliffs, valley overlooks"}],
    "public_reviews_summary": "Cool mountain pine air escape from summer valley heat with blazing fast cell service overlooking Casper.",
    "other_data": "Road closed by snow in winter.",
    "last_updated": "2026-09-12"
  },
  {
    "id": "wyoming-010",
    "name": "Oregon Basin Dispersed Area - BLM Cody",
    "state": "Wyoming",
    "county": "Park",
    "coordinates": {"latitude": 44.3812, "longitude": -108.9812, "elevation_ft": 5200.0},
    "management_agency": {"name": "Bureau of Land Management (BLM) - Cody Field Office", "type": "Federal", "phone": "(307) 578-5900", "website": "https://www.blm.gov/wyoming"},
    "rules_and_regulations": {"cost": "Free ($0/night primitive BLM dispersed camping)", "stay_limit": "14 days maximum stay limit", "guidelines": "Free primitive dispersed camping on BLM badland tracks outside active oil lease operations. Leave No Trace. Pack out all trash."},
    "waste_disposal_rules": {"poop_disposal": "Bury waste 6-8 inches deep 200 ft from dry drainages. Pack out toilet paper.", "trash_policy": "Strict Pack-It-In Pack-It-Out policy."},
    "campfire_rules": {"permitted": True, "firewood_policy": "Gather dead down wood only.", "safety_requirements": "Campfires in cleared rock rings. Extinguish cold.", "seasonal_fire_bans": "Subject to BLM fire bans."},
    "access_and_road_conditions": {"road_type": "Graded gravel access road", "road_conditions": "Well-graded gravel access roads off WY-120.", "vehicle_recommendation": "Accessible by standard 2WD passenger cars on main gravel tracks.", "scores": {"road_grade": 2, "road_terrain_difficulty": 2, "supply_run_pain": 2}},
    "nomad_connectivity_rating": {"overall_rating": "Great (4.5/5 Stars)", "verizon_reliability": "4 bars 5G/4G LTE", "att_reliability": "3-4 bars 4G LTE", "tmobile_reliability": "3-4 bars 5G", "terrain_obstruction_risk": "Low - open desert basin", "distance_from_tower_corridor_miles": 6.0, "cellular_internet_dependable": True},
    "amenities": ["Absaroka Mountain Panorama Views", "Yellowstone Gateway Proximity", "Open High Desert", "Dark Sky Astronomy"],
    "location_scores": {"distance_to_groceries_score": 8, "distance_to_library_score": 8, "distance_to_gym_score": 7, "terrain_score": 8, "quietness_score": 8},
    "nearest_supply_towns": [{"town_name": "Cody, WY", "distance_miles": 14.0, "services_available": ["Full Groceries", "Hospital", "Rodeo", "Outdoor Gear", "Cody Airport"]}],
    "seasonal_weather_effects": {"spring": "Breezy spring (55-68°F).", "summer": "Warm summer (82-90°F) with mountain breezes.", "fall": "Crisp clear autumn days.", "winter": "Cold winter (22-38°F)."},
    "dangers_and_hazards": ["High Wind Gusts", "Rattlesnakes"],
    "acoustic_environment": {"quietness_rating": "High Desert Basin Quiet (Quietness Score: 8/10)", "common_human_made_sounds": ["Distant WY-120 highway hum", "Wind gusts"]},
    "flora_and_fauna": {"common_plants_and_trees": ["Big Sagebrush", "Rabbitbrush", "Wheatgrass"], "common_animals": ["Pronghorn Antelope", "Sage Grouse", "Coyote", "Mule Deer"]},
    "human_demographics_and_culture": "Buffalo Bill Cody western frontier heritage and Yellowstone gateway culture.",
    "spiritual_and_folklore_data": {"nature_spirits_and_mythological_lore": "Crow and Shoshone traditional territory.", "energetic_and_spiritual_features": "Panoramic views of the rugged Absaroka snowcaps framing the high desert basin."},
    "nearby_hiking_trails": [{"trail_name": "Oregon Basin Badland Trail", "length_miles": 3.5, "difficulty": "Easy", "features": "Badland rock formations, Absaroka views, pronghorn watching"}],
    "public_reviews_summary": "Super convenient free basecamp just minutes from Cody with fast cell service and stunning mountain views.",
    "other_data": "14 miles south of Cody.",
    "last_updated": "2026-09-12"
  }
])
save_state(wy, wy_path)
print("Updated Wyoming -> 10 sites.")
